### ISSUE TITLE
game crashed when i click on import scheme

### ISSUE THREAD

**Issue by DERKEROR** [Anuken/Mindustry#10084]
### Platforms

Windows

### Build

steam build 146

### Issue

crash

### Steps to reproduce

clicked on the import scheme button

### Mods used

vanilla

### (Crash) logs

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4078mb
Cores: 16
Mods: none (vanilla)

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(Unknown Source)
	at java.base/java.util.TimSort.mergeAt(Unknown Source)
	at java.base/java.util.TimSort.mergeForceCollapse(Unknown Source)
	at java.base/java.util.TimSort.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at mindustry.ui.dialogs.FileChooser.getFileNames(FileChooser.java:167)
	at mindustry.ui.dialogs.FileChooser.updateFiles(FileChooser.java:193)
	at mindustry.ui.dialogs.FileChooser.setupWidgets(FileChooser.java:98)
	at mindustry.ui.dialogs.FileChooser.lambda$new$1(FileChooser.java:49)
	at arc.scene.ui.Dialog$5.shown(Dialog.java:397)
	at arc.scene.event.VisibilityListener.handle(VisibilityListener.java:11)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Dialog.show(Dialog.java:468)
	at arc.scene.ui.Dialog.show(Dialog.java:507)
	at arc.scene.ui.Dialog.show(Dialog.java:502)
	at mindustry.core.Platform.defaultFileDialog(Platform.java:211)
	at mindustry.core.Platform.showFileChooser(Platform.java:147)
	at mindustry.core.Platform.showFileChooser(Platform.java:215)
	at mindustry.ui.dialogs.SchematicsDialog.lambda$showImport$27(SchematicsDialog.java:237)
	at arc.scene.Element.lambda$clicked$2(Element.java:913)
	at arc.scene.Element$4.clicked(Element.java:922)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
 

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4078mb
Cores: 16
Mods: none (vanilla)

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(Unknown Source)
	at java.base/java.util.TimSort.mergeAt(Unknown Source)
	at java.base/java.util.TimSort.mergeForceCollapse(Unknown Source)
	at java.base/java.util.TimSort.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at mindustry.ui.dialogs.FileChooser.getFileNames(FileChooser.java:167)
	at mindustry.ui.dialogs.FileChooser.updateFiles(FileChooser.java:193)
	at mindustry.ui.dialogs.FileChooser.lambda$updateFiles$14(FileChooser.java:230)
	at arc.scene.Element.lambda$clicked$2(Element.java:913)
	at arc.scene.Element$4.clicked(Element.java:922)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
Seems like you sent the same log twice

Also it's better to send it as a file and include video proof

**Comment by DERKEROR** [comment]
[crash-report-08_04_2024_19_52_33.txt](https://github.com/user-attachments/files/16488152/crash-report-08_04_2024_19_52_33.txt)

[crash-report-08_04_2024_19_43_45.txt](https://github.com/user-attachments/files/16488153/crash-report-08_04_2024_19_43_45.txt)

**Comment by Anuken** [comment]
This crash isn't relevant anymore either way; Mindustry uses a native file chooser now.
