### ISSUE TITLE
Cannot load map file

### ISSUE THREAD

**Issue by NoSanityHere** [Anuken/Mindustry#10117]
### Platforms

Mac

### Build

146

### Issue

trying to import the ground zero save file gives the error
```
[E] Failed to load custom map file '/game data path/Mindustry/maps/groundZero.msav'!
[E] java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.region(String, java.io.DataInput, arc.util.io.CounterInputStream, mindustry.io.SaveFileReader$IORunner)" because "ver" is null
	at mindustry.io.MapIO.createMap(MapIO.java:43)
	at mindustry.maps.Maps.loadMap(Maps.java:464)
	at mindustry.maps.Maps.load(Maps.java:140)
	at mindustry.Vars.init(Vars.java:338)
	at mindustry.Vars.loadAsync(Vars.java:258)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:352)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:52)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:16)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

ver becomes null in SaveIO.getSaveWriter(int version), the version is 8, but versions.get returns null, and the underlying code is rather confusing

### Steps to reproduce

try to import the ground zero save file provided or in https://github.com/Anuken/Mindustry/tree/master/core/assets/maps

### Mods used

none

### Save file

[groundZero.msav.zip](https://github.com/user-attachments/files/16605292/groundZero.msav.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
You're trying to load a map for a newer version of the game.

**Comment by NoSanityHere** [comment]
oh yeah, sorry to waste your time. could you add a message like line 170 of [SaveIO](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/io/SaveIO.java)

**Comment by Anuken** [comment]
I already added a message *to the newer version*, but you're not using it.
