### ISSUE TITLE
Map marker load error

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#10161]
### Platforms

Android

### Build

BE 25225

### Issue

Error loading map markers on save file

### Steps to reproduce

Create a save file of the map and try load the save file
### OR
Load the save file map attached 

### Mods used

Vanilla

### Save file

[Original map - DSC.msav.zip](https://github.com/user-attachments/files/16814275/DSC.msav.zip)
[Save file - save.msav.zip](https://github.com/user-attachments/files/16814285/save.msav.zip)

### (Crash) logs

[E] mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "markers".
	at mindustry.io.SaveIO.load(SaveIO.java:21)
	at mindustry.io.SaveIO.load(SaveIO.java:3)
	at mindustry.io.MapIO.loadMap(MapIO.java:2)
	at mindustry.editor.MapEditor.lambda$beginEdit$0(MapEditor.java:3)
	at mindustry.editor.MapEditor.$r8$lambda$wZLU99WjhKSnqSNMXuJSPd1_1BY(MapEditor.java:1)
	at mindustry.editor.WaveGraph$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:134)
	at mindustry.editor.MapEditor.load(MapEditor.java:4)
	at mindustry.editor.MapEditor.beginEdit(MapEditor.java:8)
	at mindustry.editor.MapEditorDialog.lambda$beginEditMap$36(MapEditorDialog.java:10)
	at mindustry.editor.MapEditorDialog.$r8$lambda$jU-b6TIvARARVoTbrq-yb6nSzTs(MapEditorDialog.java:1)
	at mindustry.editor.WaveGraph$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:94)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:1)
	at mindustry.core.UI.$r8$lambda$vS15sqdYoigm_getKIWpuONO3uA(UI.java:1)
	at mindustry.core.UI$$ExternalSyntheticLambda7.run(R8$$SyntheticClass:62)
	at arc.util.Timer$1.run(Timer.java:3)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:89)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)
Caused by: java.io.IOException: Error reading region "markers".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:7)
	at mindustry.io.SaveVersion.read(SaveVersion.java:60)
	at mindustry.io.SaveIO.load(SaveIO.java:14)
	... 17 more
Caused by: arc.util.ArcRuntimeException: Unrecognized data type, string expected
	at arc.util.serialization.UBJsonReader.parseString(UBJsonReader.java:6)
	at arc.util.serialization.UBJsonReader.parseObject(UBJsonReader.java:77)
	at arc.util.serialization.UBJsonReader.parse(UBJsonReader.java:13)
	at arc.util.serialization.UBJsonReader.parseObject(UBJsonReader.java:89)
	at arc.util.serialization.UBJsonReader.parse(UBJsonReader.java:13)
	at arc.util.serialization.UBJsonReader.parseWihoutClosing(UBJsonReader.java:5)
	at mindustry.io.JsonIO.readBytes(JsonIO.java:8)
	at mindustry.game.MapMarkers.read(MapMarkers.java:12)
	at mindustry.io.SaveVersion.readMarkers(SaveVersion.java:5)
	at mindustry.io.MapIO$$ExternalSyntheticLambda1.accept(R8$$SyntheticClass:46)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:3)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:1)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:2)
	... 19 more

[E] mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "markers".
	at mindustry.io.SaveIO.load(SaveIO.java:8)
	at mindustry.io.MapIO.loadMap(MapIO.java:2)
	at mindustry.editor.MapEditor.lambda$beginEdit$0(MapEditor.java:3)
	at mindustry.editor.MapEditor.$r8$lambda$wZLU99WjhKSnqSNMXuJSPd1_1BY(MapEditor.java:1)
	at mindustry.editor.WaveGraph$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:134)
	at mindustry.editor.MapEditor.load(MapEditor.java:4)
	at mindustry.editor.MapEditor.beginEdit(MapEditor.java:8)
	at mindustry.editor.MapEditorDialog.lambda$beginEditMap$36(MapEditorDialog.java:10)
	at mindustry.editor.MapEditorDialog.$r8$lambda$jU-b6TIvARARVoTbrq-yb6nSzTs(MapEditorDialog.java:1)
	at mindustry.editor.WaveGraph$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:94)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:1)
	at mindustry.core.UI.$r8$lambda$vS15sqdYoigm_getKIWpuONO3uA(UI.java:1)
	at mindustry.core.UI$$ExternalSyntheticLambda7.run(R8$$SyntheticClass:62)
	at arc.util.Timer$1.run(Timer.java:3)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:89)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)
Caused by: java.io.IOException: Error reading region "markers".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:7)
	at mindustry.io.SaveVersion.read(SaveVersion.java:60)
	at mindustry.io.SaveIO.load(SaveIO.java:14)
	at mindustry.io.SaveIO.load(SaveIO.java:3)
	... 16 more
Caused by: arc.util.ArcRuntimeException: Unrecognized data type, string expected
	at arc.util.serialization.UBJsonReader.parseString(UBJsonReader.java:6)
	at arc.util.serialization.UBJsonReader.parseObject(UBJsonReader.java:77)
	at arc.util.serialization.UBJsonReader.parse(UBJsonReader.java:13)
	at arc.util.serialization.UBJsonReader.parseObject(UBJsonReader.java:89)
	at arc.util.serialization.UBJsonReader.parse(UBJsonReader.java:13)
	at arc.util.serialization.UBJsonReader.parseWihoutClosing(UBJsonReader.java:5)
	at mindustry.io.JsonIO.readBytes(JsonIO.java:8)
	at mindustry.game.MapMarkers.read(MapMarkers.java:12)
	at mindustry.io.SaveVersion.readMarkers(SaveVersion.java:5)
	at mindustry.io.MapIO$$ExternalSyntheticLambda1.accept(R8$$SyntheticClass:46)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:3)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:1)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:2)
	... 19 more

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
Error log is from lastlog.txt

**Comment by Anuken** [comment]
Fixed.
