### ISSUE TITLE
start crash from texture pack with environment textures

### ISSUE THREAD

**Issue by hortiSquash** [Anuken/Mindustry#10186]
### Platforms

Windows

### Build

25254

### Issue

the game crashes at startup when trying to load a texture pack that overrides the environment sprites
### Steps to reproduce

just load the mod i linked underneath -> insta crash before even reaching the menu

### Mods used

[hortiDefinition_x0.5.zip](https://github.com/user-attachments/files/16914073/hortiDefinition_x0.5.zip)

### (Crash) logs

[I] Initialized Discord rich presence.
[I] [Core] Initialized SDL v2.0.20
[I] [Audio] Initialized SoLoud 202002 using MiniAudio at 44100hz / 2048 samples / 2 channels
[I] [GL] Version: OpenGL 3.1.0 / NVIDIA Corporation / NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 3 context.
[I] [JAVA] Version: 16.0.2
[I] [RAM] Available: 3.9 GB
[I] [Mindustry] Version: 25254
[I] Loaded mod 'hortiDefinition' in 6.4067ms
[I] Total time to load: 3283ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_be.json
[E] java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at mindustry.world.blocks.environment.StaticWall.drawBase(StaticWall.java:33)
        at mindustry.graphics.MenuRenderer.cache(MenuRenderer.java:202)
        at mindustry.graphics.MenuRenderer.<init>(MenuRenderer.java:37)
        at mindustry.ui.fragments.MenuFragment.build(MenuFragment.java:33)
        at mindustry.core.UI.init(UI.java:230)
        at mindustry.ClientLauncher.update(ClientLauncher.java:227)
        at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:205)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:193)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
Please send log and crash log as a 
.txt file
