### ISSUE TITLE
Rare server crash | Crash when setting core in logic.update

### ISSUE THREAD

**Issue by Agzam-Ar** [Anuken/Mindustry#10249]
### Platforms

Linux

### Build

7.0 Build 146 (server-release from Jul 18)

### Issue

Unfortunately, I was not on the server at the time of the crash, and all I can say is that the plugin replaced the storage block (`setNet(...)`) with the core-shard during the update event (`Events.run(Trigger.update, ...)`)

Error does not always occur, this is the first time in a very long period of time

Given the rarity of the bug, I'm not sure if it needs a fix if there is a new BlockIndexer system in v8

### Steps to reproduce

I couldn't reproduce the crash

### Mods used

https://github.com/Agzam4/Mindustry-plugin/blob/main/src/example/events/LuckyPlaceEvent.java

### (Crash) logs

```
[E] java.lang.ArrayIndexOutOfBoundsException: Index 12 out of bounds for length 10
	at mindustry.ai.BlockIndexer.addIndex(BlockIndexer.java:154)
	at mindustry.ai.BlockIndexer.lambda$new$1(BlockIndexer.java:53)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.world.Tile.fireChanged(Tile.java:651)
	at mindustry.world.Tile.changed(Tile.java:641)
	at mindustry.world.Tile.setBlock(Tile.java:271)
	at mindustry.world.Tile.setBlock(Tile.java:215)
	at mindustry.world.Tile.setTile(Tile.java:712)
	at mindustry.gen.Call.setTile(Call.java:1368)
	at mindustry.world.Tile.setNet(Tile.java:363)
	at example.events.LuckyPlaceEvent.updateMiniEvent(LuckyPlaceEvent.java:942)
	at example.events.LuckyPlaceEvent.update(LuckyPlaceEvent.java:265)
	at example.events.ServerEventsManager.update(ServerEventsManager.java:177)
	at example.ExamplePlugin.lambda$init$0(ExamplePlugin.java:69)
	at arc.Events.lambda$run$2(Events.java:20)
	at arc.Events.fire(Events.java:36)
	at mindustry.core.Logic.update(Logic.java:406)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:87)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
There have been significant changes since v146, and this crash doesn't make sense. Unless this re-occurs in BE/v8, I won't be looking into it further.
