### ISSUE TITLE
Mindustry releases don't run on musl systems

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#10258]
### Platforms

Linux

### Build

146

### Issue

Arc doesn't have any fallbacks to launch under `musl`, resulting in a link crash. Tested on a Gentoo machine.
```
$ uname -a
Linux benby 6.11.1-linux-cachyos #1 SMP PREEMPT_DYNAMIC Mon Oct 7 00:15:07 EEST 2024 x86_64 AMD Ryzen Threadripper 7960X 24-core Processor AuthenticAMD GNU/Linux
```

### Steps to reproduce

```
wget https://github.com/Anuken/Mindustry/releases/v146/download/Mindustry.jar
java -jar Mindustry.jar
```

### Mods used

None

### Save file

None

### (Crash) logs

```
arc.util.ArcRuntimeException: Couldn't load shared library 'libarc64.so' for target: Linux, 64-bit
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:84)
        at arc.util.ArcNativesLoader.load(ArcNativesLoader.java:14)
        at arc.backend.sdl.SdlApplication.init(SdlApplication.java:107)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:35)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: java.lang.UnsatisfiedLinkError: /tmp/arc/c0f137d/libarc64.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/arc/c0f137d/li>
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:288)
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
        ... 4 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/arc/c0f137d/libarc64.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/arc/c0f137d/libarc64.so)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1957)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:294)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:260)
        ... 5 more
```
![image](https://github.com/user-attachments/assets/08eb4c74-40a4-4209-a91d-5c7184a72dd8)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by BasedUser** [comment]
![image](https://github.com/user-attachments/assets/6c6edcd3-45bd-4c2b-8369-408356f00c53)

**Comment by Anuken** [comment]
Musl systems aren't supported; I have no interest in working on this.
