### ISSUE TITLE
Building Units Crashes Game BE 25380

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry#10261]
### Platforms

Windows

### Build

bleeding-edge build 25380

### Issue

Whenever an [air] unit factory finishes building, it will crash the game. (I've only tested the air factory)

### Steps to reproduce

I was playing the saved game below. I tried to make monos and then polies. However, I noticed that the game would crash upon completing any of these said units. 

### Mods used

https://github.com/Anuken/MindustryBuilds/releases/tag/25380

### Save file

(Don't bother. Just try making units in sandbox, no need to download.)

[gamegamegame.zip](https://github.com/user-attachments/files/17348667/gamegamegame.zip)
This zip file contains two files, the saved game "savegame" and the original map itself. 

### (Crash) logs

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: bleeding-edge build 25380
OS: Windows 10 x32 (x86)
Java Version: 1.8.0_421
Runtime Available Memory: 247mb
Cores: 20
Mods: none (vanilla)

java.lang.NullPointerException
	at mindustry.world.blocks.units.UnitFactory$UnitFactoryBuild.updateTile(UnitFactory.java:392)
	at mindustry.gen.Building.update(Building.java:2263)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:84)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:488)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:244)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:205)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:193)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by xpossed-you** [comment]
face the same issue after updating
