### ISSUE TITLE
Crash while trying to place buildplan while unit is dead

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#10305]
### Platforms

Android

### Build

25412

### Issue

Placed buildplans while dying and i crashed

### Steps to reproduce

No need, just look at crash report

### (Crash) logs

https://cdn.discordapp.com/attachments/1005298122253140000/1301378179788701708/crash_1730342639392.txt?ex=67244260&is=6722f0e0&hm=5abf5b24f090ec1d142ed30e08dc4b3baa8976e48d820ba0ed98aa7e5b4a3c95&

This is the crash report file, github wont let me upload the file on my phone

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by 50275** [comment]
(taken from above crash file)
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: bleeding-edge build 25412 (1d68f99)
OS: Linux xnull (aarch64)
Android API level: 33
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: none (vanilla)

java.lang.NullPointerException: Attempt to read from field 'arc.struct.Queue mindustry.gen.Unit.plans' on a null object reference in method 'boolean mindustry.input.InputHandler.validPlace(int, int, mindustry.world.Block, int, mindustry.entities.units.BuildPlan, boolean)'
	at mindustry.input.InputHandler.validPlace(InputHandler.java:3)
	at mindustry.input.MobileInput.lambda$buildPlacementUI$10(MobileInput.java:52)
	at mindustry.input.MobileInput.$r8$lambda$88Vq7x3BYqOURkPAYFCmA_wg7GE(MobileInput.java:1)
	at mindustry.input.MobileInput$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:36)
	at arc.scene.Element.lambda$clicked$2(Element.java:1)
	at arc.scene.Element.$r8$lambda$HTGgyzI_sft57MMc4a-IcKQNKts(Element.java:1)
	at arc.Events$$ExternalSyntheticLambda1.get(R8$$SyntheticClass:34)
	at arc.scene.Element$4.clicked(Element.java:21)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:58)
	at arc.scene.event.InputListener.handle(InputListener.java:116)
	at arc.scene.Scene.touchUp(Scene.java:106)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:19)
	at arc.backend.android.AndroidInput.processEvents(AndroidInput.java:139)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:99)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)
