### ISSUE TITLE
Client throw a exception when server sent zero-length string array

### ISSUE THREAD

**Issue by SITUVNgcd** [Anuken/Mindustry#10311]
### Platforms

Android

### Build

v7-official-146 / v7-bleeding-edge-25418

### Issue

Exception when server sent a 2d-array contains atleast 1 1d-array with zero-length.

Example on server:
```java
      // When player join or text command
      int mid = Menus.registerMenu((pl, opt)->{
        
      });
      // Menu contains atleast 1 1d-array with zero-length
      String[][] opts = {
        {"1", "2", "3"},
        {"4", "5", "6"},
        {"7", "8", "9"},
        {} // Empty string array
      };
      // Sent this menu to client
      Call.menu(player.con(), mid, "Exception", "This menu will throw Divide by zero exception and kick client", opts);
```

This caused by `int width = fullWidth / optionsRow.length;`
BE (25418): https://github.com/Anuken/Mindustry/blob/fdcdd117ddf6fa997a6392352ed65e2064de2bef/core/src/mindustry/core/UI.java#L633
v146: https://github.com/Anuken/Mindustry/blob/26b66f9bdbd3a77b32f10f3cb350a9a737d5f012/core/src/mindustry/core/UI.java#L623

### Steps to reproduce

- Create a server with above code.
- Wait to client recive that menu data.

### Mods used

None

### Save file

Not save related

### (Crash) logs

No crash, caught exception!

```
[E] java.lang.ArithmeticException: divide by zero
	at mindustry.core.UI$12.lambda$new$1(UI.java:6)
	at mindustry.core.UI$12.$r8$lambda$B98W7THZo41KWfZcorf4FExuzIA(Unknown Source:0)
	at mindustry.core.UI$12$$ExternalSyntheticLambda0.get(Unknown Source:10)
	at arc.scene.ui.layout.Table.pane(Table.java:3)
	at arc.scene.ui.layout.Table.pane(Table.java:1)
	at mindustry.core.UI$12.<init>(UI.java:8)
	at mindustry.core.UI.newMenuDialog(Unknown Source:8)
	at mindustry.core.UI.showMenu(UI.java:1)
	at mindustry.ui.Menus.menu(Menus.java:2)
	at mindustry.gen.MenuCallPacket.handleClient(Unknown Source:8)
	at mindustry.net.Net.handleClientReceived(Net.java:20)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:1)
	at mindustry.net.ArcNetProvider$1.$r8$lambda$fbfCvJnrrnJCD6dXciAW82P46Nc(Unknown Source:0)
	at mindustry.net.Net$$ExternalSyntheticLambda1.run(Unknown Source:26)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:15)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)
```
![Screenshot_20241103_213653_Mindustry](https://github.com/user-attachments/assets/e49eaa8e-cae1-4fa3-a911-4fe7e929233f)
![Screenshot_20241103_213750_Termux](https://github.com/user-attachments/assets/45a31e61-40ae-43d7-b930-33aad4cc832d)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
I think a menu with zero options is a plugin bug and should not be considered valid. There is never a valid reason to send such an array, and it doesn't make sense. I can "fix" it, but the real fix here is to *not* send zero-length arrays on your end.
