### ISSUE TITLE
NullPointerException BuilderTrait.shouldSkip

### ISSUE THREAD

**Issue by smarek** [Anuken/Mindustry#1074]
**Platform**: *Linux*

**Build**: *1f6ef9d9a*

**Issue**: *Placing conveyor belt in desert wastes over destroyed (30 something wave), local campaign*

```
> gradle desktop:run
No local.properties found. Not loading Android module.

> Configure project :
Compiling with build: 'custom build'

> Task :desktop:run
Initialized Discord rich presence.
Total time to load: 1274
Time to generate menu: 29.367014
Time to cache: 32.66638
AL lib: (WW) FreeDevice: (0x7f8c7dbdd660) Deleting 14 Buffer(s)
java.lang.NullPointerException
        at io.anuke.mindustry.entities.traits.BuilderTrait.shouldSkip(BuilderTrait.java:117)
        at io.anuke.mindustry.entities.traits.BuilderTrait.updateBuilding(BuilderTrait.java:56)
        at io.anuke.mindustry.entities.type.Player.updateMechanics(Player.java:458)
        at io.anuke.mindustry.entities.type.Player.update(Player.java:562)
        at io.anuke.mindustry.entities.EntityGroup.update(EntityGroup.java:49)
        at io.anuke.mindustry.core.Logic.update(Logic.java:251)
        at io.anuke.arc.ApplicationCore.update(ApplicationCore.java:36)
        at io.anuke.mindustry.ClientLauncher.update(ClientLauncher.java:130)
        at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:158)
        at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:146)
        at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:52)
        at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:52)
```

**Comment by Anuken** [comment]
Should be fixed now, let me know if it's not.
