### ISSUE TITLE
Server v99 died with exception

### ISSUE THREAD

**Issue by vgaming** [Anuken/Mindustry#1100]
**Platform**: Debian 9

**Build**:
```
Version: Mindustry 5-release official / build 99
Java Version: 1.8.0_222
```

**Issue**: Server died sometime when I wasn't paying attention to it, during the night.

**Steps to reproduce**: No idea. I started the server and left it running. I've been doing that for some weeks now. The server is public and there are people playing there

The exception itself:
```txt
java.lang.ArithmeticException: / by zero
        at io.anuke.mindustry.ai.Pathfinder.run(Pathfinder.java:133)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
        at io.anuke.mindustry.entities.traits.BuilderTrait.updateBuilding(BuilderTrait.java:49)
        at io.anuke.mindustry.entities.type.Player.updateMechanics(Player.java:457)
        at io.anuke.mindustry.entities.type.Player.update(Player.java:540)
        at io.anuke.mindustry.entities.EntityGroup.update(EntityGroup.java:49)
        at io.anuke.mindustry.core.Logic.update(Logic.java:251)
        at io.anuke.arc.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:99)
        at io.anuke.arc.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:64)
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
        at io.anuke.arc.util.NetJavaImpl.lambda$http$0(NetJavaImpl.java:66)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Stdout before it crashed:
```
[11-19-2019 | 00:13:13] [INFO] Game over!
[11-19-2019 | 00:13:13] [INFO] Selected next map to be 0cutter.
[11-19-2019 | 00:13:14] [INFO] Auto-assigned player Mario to team crux.
[11-19-2019 | 00:13:14] [INFO] [qzDi67Cgj60=] Mario has connected. 
[11-19-2019 | 00:15:32] [INFO] [qzDi67Cgj60=] Mario has disconnected. (closed)
[11-19-2019 | 00:39:47] [INFO] Auto-assigned player MR.DEADSHOT to team crux.
[11-19-2019 | 00:39:49] [INFO] [THvQGLvG4JY=] MR.DEADSHOT has connected. 
[11-19-2019 | 00:39:50] [INFO] Auto-assigned player killergamerpro47 to team sharded.
[11-19-2019 | 00:39:52] [INFO] [UW8EZqo6gs8=] killergamerpro47 has connected. 
[11-19-2019 | 00:40:08] [INFO] Sending crash report.
```

**Comment by vgaming** [comment]
BTW, what is the HttpClient that tries to connect? Is it to send the crash report? If it is and it's failing, then it's an indication of another, unrelated problem?

**Comment by Anuken** [comment]
The crash report server has been down for a while now, I'm aware of that. As for the crash itself, that should have been fixed recently, before this issue was reported.

**Comment by vgaming** [comment]
Good that it's fixed already.)
