### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by Fauli1221** [Anuken/Mindustry#1115]
**Platform**:Windows

**Build**: The game crashes before I can see the number but it is the newest steam build

**Issue**: the game crashes during start

**Steps to reproduce**:I started the game 

**crashlog**:
io.anuke.arc.util.ArcRuntimeException: io.anuke.arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sounds/squish,.mp3
	at io.anuke.arc.assets.AssetManager.handleTaskError(AssetManager.java:656)
	at io.anuke.arc.assets.AssetManager.update(AssetManager.java:429)
	at io.anuke.arc.assets.AssetManager.update(AssetManager.java:452)
	at io.anuke.mindustry.ClientLauncher.update(ClientLauncher.java:118)
	at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:158)
	at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:146)
	at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:52)
Caused by: io.anuke.arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sounds/squish,.mp3
	at io.anuke.arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:105)
	at io.anuke.arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at io.anuke.arc.assets.AssetManager.updateTask(AssetManager.java:578)
	at io.anuke.arc.assets.AssetManager.update(AssetManager.java:427)
	... 6 more
Caused by: io.anuke.arc.util.ArcRuntimeException: io.anuke.arc.util.ArcRuntimeException: File not found: sounds\squish,.mp3 (Internal)
	at io.anuke.arc.util.async.AsyncResult.get(AsyncResult.java:34)
	at io.anuke.arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:103)
	... 9 more
Caused by: io.anuke.arc.util.ArcRuntimeException: File not found: sounds\squish,.mp3 (Internal)
	at io.anuke.arc.files.FileHandle.read(FileHandle.java:191)
	at io.anuke.arc.backends.sdl.audio.Mp3$Sound.<init>(Mp3.java:92)
	at io.anuke.arc.backends.sdl.audio.ALAudio.newSound(ALAudio.java:88)
	at io.anuke.arc.backends.sdl.audio.ALAudio.newSound(ALAudio.java:15)
	at io.anuke.arc.assets.loaders.SoundLoader.loadAsync(SoundLoader.java:35)
	at io.anuke.arc.assets.loaders.SoundLoader.loadAsync(SoundLoader.java:15)
	at io.anuke.arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at io.anuke.arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Anuken** [comment]
This is caused by a broken mod, not the game. "squish," is not a valid name for a sound.
