### ISSUE TITLE
NullPointerException at ItemBridge.acceptLiquid

### ISSUE THREAD

**Issue by fgaz** [Anuken/Mindustry#1157]
**Platform**: Linux

**Build**: 100

**Issue**: Crash report:

```
java.lang.NullPointerException
	at io.anuke.mindustry.world.blocks.distribution.ItemBridge.acceptLiquid(ItemBridge.java:315)
	at io.anuke.mindustry.world.blocks.liquid.LiquidJunction.getLiquidDestination(LiquidJunction.java:43)
	at io.anuke.mindustry.world.BlockStorage.tryMoveLiquid(BlockStorage.java:152)
	at io.anuke.mindustry.world.blocks.liquid.Conduit.update(Conduit.java:115)
	at io.anuke.mindustry.entities.type.TileEntity.update(TileEntity.java:314)
	at io.anuke.mindustry.entities.EntityGroup.update(EntityGroup.java:49)
	at io.anuke.mindustry.core.Logic.update(Logic.java:241)
	at io.anuke.arc.ApplicationCore.update(ApplicationCore.java:36)
	at io.anuke.mindustry.ClientLauncher.update(ClientLauncher.java:130)
	at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:158)
	at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:146)
	at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:52)
```

**Steps to reproduce**:

Sadly I don't know what the game was doing at the time. I was playing on a a server and went afk for a bit. When I came back the game had crashed.

edit: user "not purple" said that this has to do with how liquid junctions and item bridges interact. I linked the issue to them, hopefully they post some more info

edit edit: seems like this is used by some people to DoS servers :-/

**Comment by Arkanic** [comment]
liquid from a liquid router going into an item bridge

**Comment by fgaz** [comment]
Duh, it was even written in the stack trace :man_facepalming:. Good catch

**Comment by Anuken** [comment]
Duplicate.
