### ISSUE TITLE
Generate map preview error (include #1400)

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#1403]
**Platform**: Windows

**Build**: 102.2

**Issue**: See animated gif
![bug](https://user-images.githubusercontent.com/44261958/72727332-fc924400-3bcd-11ea-8675-fd30e00a888a.gif)

**Steps to reproduce**:
1. Open incorrect map file and make new map and generate map
2. Done.

#1400

**Comment by Kieaer** [comment]
When draw any blocks in current status, show this stacktrace.
![1](https://user-images.githubusercontent.com/44261958/72727526-732f4180-3bce-11ea-9bf0-8e669dfaa628.PNG)

```
java.lang.ArithmeticException: / by zero
	at mindustry.editor.MapRenderer.draw(MapRenderer.java:67)
	at mindustry.editor.MapView.draw(MapView.java:246)
	at arc.scene.Group.drawChildren(Group.java:126)
	at arc.scene.Group.draw(Group.java:52)
	at arc.scene.ui.layout.WidgetGroup.draw(WidgetGroup.java:141)
	at arc.scene.ui.layout.Table.draw(Table.java:114)
	at arc.scene.Group.drawChildren(Group.java:126)
	at arc.scene.Group.draw(Group.java:52)
	at arc.scene.ui.layout.WidgetGroup.draw(WidgetGroup.java:141)
	at arc.scene.ui.layout.Table.draw(Table.java:114)
	at arc.scene.Group.drawChildren(Group.java:110)
	at arc.scene.ui.layout.Table.draw(Table.java:109)
	at arc.scene.ui.Dialog.draw(Dialog.java:278)
	at arc.scene.Group.drawChildren(Group.java:126)
	at arc.scene.Group.draw(Group.java:52)
	at arc.scene.Scene.draw(Scene.java:108)
	at mindustry.core.UI.update(UI.java:190)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:133)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
```

**Comment by Anuken** [comment]
This should be posted in #1400, as it is caused by the same issue.
