### ISSUE TITLE
Server "save" command generates corrupt savefile.

### ISSUE THREAD

**Issue by snizzo** [Anuken/Mindustry#1701]
**Platform**: Linux server (and client)

**Build**: 03-13-2020 | 02:00:29] [I] Version: Mindustry 5-release official / build 104.5
[03-13-2020 | 02:00:29] [I] Java Version: 14-ea

**Issue**: Played for a couple hours with vps mindustry linux server Ubuntu 19.10 (hosted on ovh). Issued "save 0" command on server.
[03-13-2020 | 01:47:10] [I] Saved to config/saves/0.msav.

Then "load 0":load 0
[03-13-2020 | 01:57:56] [I] Save loaded.
[03-13-2020 | 01:57:56] [I] Opened a server on port 6567.
[03-13-2020 | 01:58:04] [I] [jwb3XrcGGfQAAAAApqWwog==] Alial has disconnected. (closed)
[03-13-2020 | 01:58:06] [I] [MJvrdFQ7KwQAAAAAYL2oaA==] snz0 has disconnected. (closed)
[03-13-2020 | 01:58:28] [I] [MJvrdFQ7KwQAAAAAYL2oaA==] snz0 has disconnected. (closed)
[03-13-2020 | 01:58:55] [I] [jwb3XrcGGfQAAAAApqWwog==] Alial has disconnected. (closed)

When attempting a connection from Mindustry client Linux, server reports a disconnection. Server output as above.

Client output:
snizzo@snizzo-P65-P67SE:~/Downloads/mindustry-linux-64-bit$ ./Mindustry 
[I] Initialized Discord rich presence.
[I] Total time to load: 2088
[I] Time to generate menu: 37.15619
[I] Fetched 13 global servers.
[I] Connecting to server: mlem.ovh/51.255.175.212:6567
[I] Recieved world data: 101525 bytes.
[I] Time to cache: 109.00703
[E] java.lang.ArrayIndexOutOfBoundsException: 350
	at mindustry.core.World$Context.tile(World.java:412)
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:204)
	at mindustry.net.NetworkIO.loadWorld(NetworkIO.java:56)
	at mindustry.core.NetClient.lambda$new$3(NetClient.java:125)
	at mindustry.net.Net.handleClientReceived(Net.java:247)
	at mindustry.net.Net.handleClientReceived(Net.java:240)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:60)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

Server sometimes says:
Errore di rete sconosciuto (350)  (Unrecognized server error (350))
>ArrayIndexOutOfBounds: '350'
World$Context.tile: 412
SaveVersion.readMap: 204
NetworkIO.loadWorld: 56
NetClient.lambda$new$3: 125
Net.handleClientReceived: 247
Net.handleClientReceived: 240
ArcNetProvider$1.lambda$received$2: 60
TaskQueue.run: 17
SdlApplication.loop: 148
SdlApplication.<init>:52
DesktopLauncher.main: 46

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

load attached map.
[savegame.zip](https://github.com/Anuken/Mindustry/files/4327374/savegame.zip)

**Comment by Anuken** [comment]
Loads and connects fine for me for a 104.5 server. 

I see you are using:
> Java Version: 14-ea

Mindustry is only supposed to be run on Java 8. While it isn't very likely to be the cause of your problem, I would advise against using different versions.

**Comment by snizzo** [comment]
Client wasn't updated. My bad.
