### ISSUE TITLE
server crash after red core has been destroyed 

### ISSUE THREAD

**Issue by hribik100** [Anuken/Mindustry#1719]
**In console:**
java.lang.NullPointerException
        at hexed.HexedMod.lambda$init$2(HexedMod.java:136)
        at arc.Events.lambda$fire$2(Events.java:26)
        at arc.struct.Array.each(Array.java:175)
        at arc.Events.fire(Events.java:26)
        at arc.Events.fire(Events.java:21)
        at mindustry.entities.type.TileEntity.onDeath(TileEntity.java:286)
        at mindustry.entities.type.TileEntity.onTileDestroyed(TileEntity.java:64)
        at mindustry.gen.Call.onTileDestroyed(Call.java:866)
        at mindustry.entities.type.TileEntity.damage(TileEntity.java:184)
        at mindustry.entities.Damage.tileDamage(Damage.java:242)
        at mindustry.entities.Damage.damage(Damage.java:207)
        at mindustry.entities.Damage.damage(Damage.java:176)
        at mindustry.entities.bullet.BulletType.hit(BulletType.java:131)
        at mindustry.entities.bullet.BulletType.hit(BulletType.java:109)
        at mindustry.entities.bullet.BulletType.hitTile(BulletType.java:105)
        at mindustry.entities.type.Bullet.lambda$update$0(Bullet.java:213)
        at mindustry.core.World.raycastEach(World.java:284)
        at mindustry.entities.type.Bullet.update(Bullet.java:202)
        at mindustry.entities.EntityGroup.update(EntityGroup.java:51)
        at mindustry.core.Logic.update(Logic.java:241)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:93)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)

**Comment by Anuken** [comment]
This is caused by a mod, not the base game. Report it in the correct repository.

**Comment by hribik100** [comment]
I had All mods disabled

**Comment by Anuken** [comment]
No, you didn't. The stack trace shows that you were using Hexed.
