### ISSUE TITLE
Game not starting after losing connection

### ISSUE THREAD

**Issue by Timamite** [Anuken/Mindustry#1749]
**Platform**: *Windows 10, latest*

**Build**: *104.5*

**Issue**: *After losing connection to a multiplayer game, i am not able to start the game. The error "java.lang.ExceptionInInitializerError
	at arc.backend.sdl.SdlGL20.glGetString(SdlGL20.java:88)
	at arc.backend.sdl.SdlGraphics.<init>(SdlGraphics.java:36)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:35)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
Caused by: arc.util.ArcRuntimeException: GLEW failed to initialize: Missing framebuffer_object extension.
	at arc.backend.sdl.jni.SDLGL.<clinit>(SDLGL.java:109)
	... 4 more
" occurs immedately after starting the game, crashing it.*

**Steps to reproduce**: *Lose connection to a multiplayer game, then try to start the game*

**Comment by Timamite** [comment]
[crash-report-03_24_2020_23_24_03.txt](https://github.com/Anuken/Mindustry/files/4377943/crash-report-03_24_2020_23_24_03.txt)

**Comment by DeltaNedas** [comment]
update your drivers, you are missing gl extensions
`apt install libgl1-mesa-glx` on debian

**Comment by Anuken** [comment]
Your graphics card/drivers don't support Mindustry. Update them.
