### ISSUE TITLE
[modding] type `GenericCrafter` BUG

### ISSUE THREAD

**Issue by 2938137849** [Anuken/Mindustry#1831]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10
**Build**: *The build number under the title in the main menu. Required.*
104.10
**Issue**: *Explain your issue in detail.*

while a `GenericCrafter` building only have field `outputLiquid`, the `consumes` must have field `liquid` ,or the game will cause an exception

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

i write a mod:
```json
{
  "type": "GenericCrafter",
  "size": 1,
  "outputLiquid": "water/1",
  "craftTime": 1,
  "consumes": {
    "items": {
      "items": ["copper/1"]
    }
  },
  "requirements": ["copper/50"],
  "category": "crafting",
}
```
when i build the building in a world, it will cause an exception like follow:
```
java.lang.NullPointerException
	at mindustry.world.blocks.production.GenericCrafter.shouldConsume(GenericCrafter.java:142)
	at mindustry.world.modules.ConsumeModule.update(ConsumeModule.java:26)
	at mindustry.entities.type.TileEntity.update(TileEntity.java:331)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:51)
	at mindustry.core.Logic.update(Logic.java:241)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:138)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
```
if i change the code like this:
```json
{
  "type": "GenericCrafter",
  "size": 1,
  "outputLiquid": "water/1",
  "craftTime": 1,
  "consumes": {
    "items": {
      "items": ["copper/1"]
    },
   "liquid": {
      "liquid": "water",
      "amount": 0
    }
  },
  "requirements": ["copper/50"],
  "category": "crafting",
}
```
(only add a `liquid` field)
then it works well.
and the panel in the game will show you need to input water, however you don not need to add water actually.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
you need hasLiquids, [NOTABUG]

**Comment by 2938137849** [comment]
ah, thanks, but this field is not in the wiki, so i thought it didn't exist
