### ISSUE TITLE
Bundle Error: zip file closed

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#1925]
**Platform**: *Android*

**Build**: *104.6*

**Issue**: *
Imported sk7725/Commandblocks from Github, translations are not showing up, and it says in the log:
```
Error loading bundle: sk7725-Commandblocks-1f6b845/bundles/bundle_ko.properties/bundle_ko: java.lang.IllegalStateException: zip file closed
    at java.util.zip.ZipFile.ensureOpen(ZipFile.java:706)
    at java.util.zip.ZipFile.getInputStream(ZipFile.java:377)
    at arc.files.ZipFi.read(ZipFi.java:129)
    at arc.files.Fi.reader(Fi.java:233)
    at arc.files.Fi.reader(Fi.java:225)
    at mindustry.mod.Mods.buildFiles(Mods.java:356)
    at mindustry.mod.Mods.load(Mods.java:270)
    at mindustry.mod.Mods.reloadContent(Mods.java:430)
    at mindustry.ui.dialogs.ModsDialog.lambda$null$2$ModsDialog(ModsDialog.java:48)
    at mindustry.ui.dialogs.-$$Lambda$ModsDialog$jkmLIxU_xA5eU1isqVlJXi5YloA.run(Unknown Source:2)
    at arc.backend.android.AndroidGraphics.lambda$onDrawFrame$0$AndroidGraphics(AndroidGraphics.java:426)
    at arc.backend.android.-$$Lambda$AndroidGraphics$E5Jhq3pDs174QxCFAWFeVbXthOc.run(Unknown Source:2)
    at arc.backend.android.AndroidGraphics.runProtected(AndroidGraphics.java:479)
    at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:424)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```
Using localizedName does not work too. May be similar to #1304 , but it does not mention about the log error.
*

**Steps to reproduce**: *Download sk77725/Commandblocks, from Github.*

**Link to mod(s) used, if applicable**: *https://github.com/sk7725/Commandblocks*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't have any issues with this.

**Comment by sk7725** [comment]
It is the Korean translation, does the translation show up correctly when you set the language to Korean?

**Comment by Anuken** [comment]
Without any modifications, it doesn't, but I don't get any errors. Since you explicitly specify `name:` in your blocks, that overwrites  any bundle values. Removing name and description values makes it show up correctly.

**Comment by sk7725** [comment]
The translation shows up, still the error shows up in the log, but does not have performance impact of any sort.

**Comment by Anuken** [comment]
Note that in 6.0, names no longer override specific localizations, so your original files will work. Since the error doesn't cause any issues, this can be closed.
