### ISSUE TITLE
NPE on destroying blocks in multiplayer

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#1990]
**Platform**: *Windows*

**Build**: *5.104.9*

**Issue**: *NPE with crash sometimes*

```
java.lang.NullPointerException
	at mindustry.content.Fx.lambda$load$89(Fx.java:530)
	at mindustry.entities.Effects.renderEffect(Effects.java:38)
	at mindustry.entities.type.EffectEntity.draw(EffectEntity.java:74)
	at mindustry.entities.EntityGroup.lambda$draw$3(EntityGroup.java:66)
	at mindustry.entities.EntityGroup.draw(EntityGroup.java:78)
	at mindustry.entities.EntityGroup.draw(EntityGroup.java:66)
	at mindustry.entities.EntityGroup.draw(EntityGroup.java:62)
	at mindustry.core.Renderer.draw(Renderer.java:324)
	at mindustry.core.Renderer.update(Renderer.java:170)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:138)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
```

**Steps to reproduce**: *When I'm trying to deconstruct block in multiplayer, sometimes it crashes, not sure if this is connected to some specific block - once reproduced for mining drill, another one for conveyor. Stacktraces were the same.*

**Link to mod(s) used, if applicable**: *no mods, server used was \<io\> attack*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported. - definitely tried, but searching by stacktrace is not a consistent thing :(**

**Comment by Anuken** [comment]
1. Update your game, 104.9 is not the latest version.
2. This is no longer relevant with 6.0.
