### ISSUE TITLE
Offscreen destruction of a Command Center causes a crash when placing another one

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#2161]
**Platform**: Windows

**Build**: Steam 104.10

**Issue**: When placing a command center after another one got destroyed offscreen, the game crashes with a NullPointerException
[crash-report-06_13_2020_20_10_29.txt](https://github.com/Anuken/Mindustry/files/4775684/crash-report-06_13_2020_20_10_29.txt)

**Steps to reproduce**: A command center is destroyed offscreen, and rebuilt by BuilderDrones. Placing another command center down crashes the game

**Link to mod(s) used, if applicable**: n/a

**Crash report, if applicable**: 
java.lang.NullPointerException
	at mindustry.world.blocks.units.CommandCenter.placed(CommandCenter.java:50)
	at mindustry.world.blocks.BuildBlock.constructed(BuildBlock.java:108)
	at mindustry.world.blocks.BuildBlock$BuildEntity.construct(BuildBlock.java:248)
	at mindustry.entities.traits.BuilderTrait.updateBuilding(BuilderTrait.java:107)
	at mindustry.entities.type.Player.updateMechanics(Player.java:461)
	at mindustry.entities.type.Player.update(Player.java:565)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:51)
	at mindustry.core.Logic.update(Logic.java:248)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:138)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not relevant in 6.0; it doesn't have command centers.
