### ISSUE TITLE
Crash error discord-rpc not found on Linux Arm.

### ISSUE THREAD

**Issue by lerker100** [Anuken/Mindustry#2167]
**Platform**: *Manjaro Arm*
**Build**: *104 but I can't get the game to launch so not sure exactly what point it is.*
**Issue**: *Mindustry through's a `discord-rpc` error and closes.*
 
I'm tring to install mindustry on my Pinebook Pro which is a linux arm laptop.
I install it through the AUR package and it does install just fine and openjdk8 is present.
Mindustry errors out saying that `discord-rpc` was unable to load.
Discord-rpc has been deprecated anyways [Discord-rpc Github](https://github.com/discord/discord-rpc)

**Crash report.*
```
[E] Failed to initialize discord.: java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (linux-aarch64/libdiscord-rpc.so) not found in resource path ([file:/usr/share/java/mindustry/Mindustry.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
        at com.sun.jna.Library$Handler.<init>(Library.java:179)
        at com.sun.jna.Native.loadLibrary(Native.java:569)
        at com.sun.jna.Native.loadLibrary(Native.java:544)
        at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
        at mindustry.desktop.DesktopLauncher.<init>(DesktopLauncher.java:68)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

arc.util.ArcRuntimeException: Couldn't load shared library 'libgdxarm64.so' for target: Linux, 64-bit
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
        at arc.util.ArcNativesLoader.load(ArcNativesLoader.java:15)
        at arc.backend.sdl.SdlApplication.init(SdlApplication.java:78)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:30)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
Caused by: arc.util.ArcRuntimeException: Unable to read file for extraction: libgdxarm64.so
        at arc.util.SharedLibraryLoader.readFile(SharedLibraryLoader.java:93)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:253)
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
        ... 4 more
[E] Failed to save local crash report.: java.lang.ExceptionInInitializerError
        at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:341)
        at mindustry.desktop.DesktopLauncher.lambda$null$9(DesktopLauncher.java:201)
        at mindustry.desktop.DesktopLauncher.lambda$handleCrash$10(DesktopLauncher.java:201)
        at mindustry.net.CrashSender.send(CrashSender.java:72)
        at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:198)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:56)
Caused by: arc.util.ArcRuntimeException: Couldn't load shared library 'libopenal.so' for target: Linux, 64-bit
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
        at arc.backend.sdl.jni.SDL.<clinit>(SDL.java:39)
        ... 6 more
Caused by: arc.util.ArcRuntimeException: java.lang.UnsatisfiedLinkError: /tmp/arc/5cc08052/libopenal.so: /tmp/arc/5cc08052/libopenal.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:288)
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
        ... 7 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/arc/5cc08052/libopenal.so: /tmp/arc/5cc08052/libopenal.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1088)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:294)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:260)
        ... 8 more

[I] Sending crash report.
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
        at arc.util.NetJavaImpl.lambda$http$0(NetJavaImpl.java:67)
        at arc.util.async.AsyncExecutor.lambda$submit$2(AsyncExecutor.java:33)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Discord RPC isn't the problem here; if the Discord libraries fail to load, it just prints the stack trace and ignores that system. Mindustry doesn't have *any* native libraries (SDL, OpenAL) compiled for ARM, which is what you see when looking further down the stack trace.

ARM is not supported.
