### ISSUE TITLE
Failed to read tile entity of block: conveyor while connecting to multiplayer

### ISSUE THREAD

**Issue by galyfray** [Anuken/Mindustry#2214]
**Platform**: *Windows*

**Build**: *104.1*

**Issue**: *Can't loggin to server hosted by a fried due to an error while loading the map*

**Steps to reproduce**: *Don't really know try to logging to the map fork with conveyor in ?*

**Crash report, if applicable**: *The contents of relevant crash report files.*
[E] java.io.IOException: Unknown version: 1
	at mindustry.game.Schematics.read(Schematics.java:402)
	at mindustry.game.Schematics.read(Schematics.java:385)
	at mindustry.game.Schematics.loadFile(Schematics.java:118)
	at mindustry.game.Schematics.load(Schematics.java:73)
	at mindustry.game.Schematics.loadSync(Schematics.java:65)
	at arc.assets.AssetManager$2.loadSync(AssetManager.java:358)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:109)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:124)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

[I] Total time to load: 1912
[I] Time to generate menu: 30.85097
[I] Fetched 21 global servers.
[I] Connecting to server: /
[I] Recieved world data: 33298 bytes.
[I] Time to cache: 77.474625
[E] java.lang.RuntimeException: java.io.IOException: Failed to read tile entity of block: conveyor
	at mindustry.net.NetworkIO.loadWorld(NetworkIO.java:58)
	at mindustry.core.NetClient.lambda$new$3(NetClient.java:125)
	at mindustry.net.Net.handleClientReceived(Net.java:247)
	at mindustry.net.Net.handleClientReceived(Net.java:240)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:60)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
Caused by: java.io.IOException: Failed to read tile entity of block: conveyor
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:197)
	at mindustry.net.NetworkIO.loadWorld(NetworkIO.java:56)
	... 8 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at mindustry.world.blocks.distribution.Conveyor$ConveyorEntity.read(Conveyor.java:370)
	at mindustry.io.SaveVersion.lambda$readMap$3(SaveVersion.java:194)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:72)
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:192)
	... 9 more

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
update

**Comment by Anuken** [comment]
Update your game.
