### ISSUE TITLE
Sudden Crash in Multiplayer

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#2222]
**Platform**: *Windows*

**Build**: *104.10*

**Issue**: *Suddenly crashed in multiplayer.*

**Steps to reproduce**: *I was the host on a steam local multi. And suddenly, as soon as I configured a node I crashed. Can you tell me why this occured and how to fix it? Commandblocks was active, and used for team changing, btw, but the node was a vanilla Power Infinite.*

**Link to mod(s) used, if applicable**: *https://github.com/sk7725/Commandblocks*

**Crash report, if applicable**: *mindustry.net.ValidateException: Player cannot configure a tile.
	at mindustry.input.InputHandler.onTileConfig(InputHandler.java:168)
	at mindustry.gen.Call.onTileConfig(Call.java:812)
	at mindustry.world.Tile.configure(Tile.java:95)
	at mindustry.world.blocks.power.PowerNode.onConfigureTileTapped(PowerNode.java:179)
	at mindustry.input.InputHandler.tileTapped(InputHandler.java:579)
	at mindustry.input.DesktopInput.pollInput(DesktopInput.java:377)
	at mindustry.input.DesktopInput.update(DesktopInput.java:170)
	at mindustry.core.Control.update(Control.java:434)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:138)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You configured a block that your team didn't have access to, so it failed validation and crashed. This was most likely caused by your mod - I've never seen this in the wild.

**Comment by sk7725** [comment]
Must be caused by team changing then. Also, can it just ignore multiplayer errors(or at least in 6.0)? Throwing the player out of the game is probably not the best way to handle it, at least in my boundaries of knowledge...(Also, I guess this happens because your team is changed while still configuring that block) ~~2 minutes? thats a new record~~
