### ISSUE TITLE
forbidden characters in autosave filename

### ISSUE THREAD

**Issue by Remint32** [Anuken/Mindustry#2243]
**Platform**: *Windows*

**Build**: *Bleeding Edge build 8991 (Server)*

**Issue/Steps to reproduce**: *Command `config autosave true`*, **The file name cannot contain forbidden characters that the Autosave tries to save with** (`:`).

**Stacktrace log**: 
```
config autosave true
[07-19-2020 12:24:52] [I] autosave set to true.
[07-19-2020 12:24:52] [I] Autosaving...
[07-19-2020 12:24:52] [E] Autosave failed.: java.lang.RuntimeException: arc.util.ArcRuntimeException: Error writing file: config\saves\auto_wasteland_07-19-2020_12:24:52.msav (local)
        at mindustry.io.SaveIO.save(SaveIO.java:46)
        at mindustry.server.ServerControl.lambda$new$8(ServerControl.java:187)
        at arc.Events.lambda$on$0(Events.java:17)
        at arc.Events.lambda$fire$1(Events.java:29)
        at arc.struct.Seq.each(Seq.java:200)
        at arc.Events.fire(Events.java:29)
        at arc.Events.fire(Events.java:25)
        at mindustry.core.Logic.update(Logic.java:325)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:93)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
Caused by: arc.util.ArcRuntimeException: Error writing file: config\saves\auto_wasteland_07-19-2020_12:24:52.msav (local)
        at arc.files.Fi.write(Fi.java:403)
        at arc.files.Fi.write(Fi.java:415)
        at mindustry.io.SaveIO.write(SaveIO.java:106)
        at mindustry.io.SaveIO.write(SaveIO.java:110)
        at mindustry.io.SaveIO.save(SaveIO.java:43)
        ... 9 more
Caused by: java.io.FileNotFoundException: config\saves\auto_wasteland_07-19-2020_12:24:52.msav (Синтаксическая ошибка в имени файла, имени папки или метке тома)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at arc.files.Fi.write(Fi.java:399)
        ... 13 more

```

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment]
don't play 6.0

**Comment by Remint32** [comment]
> 
> 
> don't play 6.0

I see you're very smart.

**Comment by DeltaNedas** [comment]
why are you using MSDOS for a server

**Comment by Remint32** [comment]
> why are you using MSDOS for a server

lol, what?

**Comment by DeltaNedas** [comment]
The feature of having lots of filename restrictions comes from dos

**Comment by ILiekMelons** [comment]
Windows has the same file naming restrictions

**Comment by BasedUser** [comment]
and so does unix. What are you guys thinking?
