### ISSUE TITLE
Server crash on connecting any energy node

### ISSUE THREAD

**Issue by Remint32** [Anuken/Mindustry#2246]
**Platform**: *Windows*

**Build**: *All builds starting from the fixed multiplayer menu (previously it was not possible to check due to a crash in menu) to the current (**BE 9003**)*

**Issue**: *The server crashes when trying to connect / auto-connect any power node to any suitable building or other node.*

**Steps to reproduce**: *put any energy node (including the source) and try to connect it to any suitable building or other node.*

**Stacktrace log**:
```
java.lang.NullPointerException
        at mindustry.net.Administration.lambda$new$3(Administration.java:81)
        at mindustry.net.Administration.allowAction(Administration.java:145)
        at mindustry.input.InputHandler.tileConfig(InputHandler.java:221)
        at mindustry.gen.Call.tileConfig(Call.java:1103)
        at mindustry.gen.Building.configureAny(Building.java:631)
        at mindustry.world.blocks.power.PowerNode$PowerNodeEntity.lambda$placed$3(PowerNode.java:291)
        at arc.struct.Seq.each(Seq.java:193)
        at mindustry.world.blocks.power.PowerNode$PowerNodeEntity.placed(PowerNode.java:289)
        at mindustry.world.blocks.BuildBlock.constructed(BuildBlock.java:100)
        at mindustry.world.blocks.BuildBlock$BuildEntity.construct(BuildBlock.java:217)
        at mindustry.gen.BuilderMinerTrailUnit.update(BuilderMinerTrailUnit.java:1200)
        at mindustry.entities.EntityGroup.each(EntityGroup.java:66)
        at mindustry.entities.EntityGroup.update(EntityGroup.java:57)
        at mindustry.gen.Groups.update(Groups.java:52)
        at mindustry.core.Logic.update(Logic.java:367)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:95)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
[07-20-2020 04:23:52] [I] Sending crash report.
java.net.SocketTimeoutException: connect timed out
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
        at arc.util.NetJavaImpl.lambda$http$0(NetJavaImpl.java:67)
        at arc.util.async.AsyncExecutor.lambda$submit$2(AsyncExecutor.java:31)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Remint32** [comment]
_For those who are particularly intelligent, I would like to note that I am not trying to play 6.0.
Refrain from making stupid comments._
