### ISSUE TITLE
Critical bug in bleeding edge

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry#2278]
**Platform:** Android

**Build:** BE 9085

**Issue:** Game crashes after loading an existing sector

**Steps to reproduce:** After leaving a sector and launching to it again, game instantly crashes. Also I've seen turn being always 0.
https://youtu.be/bFhMDz3arK4

**Link to mod(s) used, if applicable:** none

**Crash report, if applicable:** I could not find any crash reports in game folder. 

---

**- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Crash report, if applicable: I could not find any crash reports in game folder.

I cannot help you without a crash report. This does not happen to me.

**Comment by Dexapnow** [comment]
It happend to me when clicking on sector.
```
java.lang.NullPointerException
	at mindustry.type.Sector.calculateRecievedItems(Sector.java:202)
	at mindustry.type.Sector.calculateItems(Sector.java:191)
	at mindustry.ui.dialogs.PlanetDialog.lambda$null$10(PlanetDialog.java:344)
	at arc.scene.ui.layout.Table.table(Table.java:251)
	at mindustry.ui.dialogs.PlanetDialog.lambda$updateSelected$11(PlanetDialog.java:343)
	at arc.scene.ui.layout.Table.table(Table.java:251)
	at mindustry.ui.dialogs.PlanetDialog.updateSelected(PlanetDialog.java:340)
	at mindustry.ui.dialogs.PlanetDialog.access$400(PlanetDialog.java:31)
	at mindustry.ui.dialogs.PlanetDialog$1$1.tap(PlanetDialog.java:216)
	at arc.scene.event.ElementGestureListener$1.tap(ElementGestureListener.java:36)
	at arc.input.GestureDetector.touchUp(GestureDetector.java:197)
	at arc.scene.event.ElementGestureListener.handle(ElementGestureListener.java:104)
	at arc.scene.Scene.touchUp(Scene.java:338)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:111)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:152)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
```

**Comment by Anuken** [comment]
Fixed.
