### ISSUE TITLE
when the fuse trys to shoot, the game crashes and when i open the save it also crashes

### ISSUE THREAD

**Issue by WeiJian122-afk** [Anuken/Mindustry#2456]
Platform: Windows

Build: 9475

Issue: I went near the fuse(the turret that has short range and uses graphite as ammo) and then the game crashed and I think it has something to do with the new generated bullet

Steps to reproduce: Simple. Just get a fuse and graphite for ammunition make it an emeny and then let the fuse shoot at you, if it don't crash then I'll put the map download

No mods were used

Crash log:
java.lang.NullPointerException
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.updateShooting(Turret.java:351)
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.updateTile(Turret.java:263)
	at mindustry.gen.Building.update(Building.java:1033)
	at mindustry.entities.EntityGroup$$Lambda$1363/1706272858.get(Unknown Source)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:66)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:57)
	at mindustry.gen.Groups.update(Groups.java:52)
	at mindustry.core.Logic.update(Logic.java:377)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:151)
	at arc.backend.sdl.SdlApplication$$Lambda$216/1436664465.get(Unknown Source)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

-x-x-
BTW I was using the BE Mindustry v6 bleeding-edge build 9475

**Comment by Quezler** [comment]
didn't the ammo change to thorium? 🤔

**Comment by Anuken** [comment]
Doesn't happen to me, with or without the graphite "ammo".

> if it don't crash then I'll put the map download

If you have the save, why aren't you posting it here from the start? Waiting for me to check if it crashes is a waste of everyone's time.
