### ISSUE TITLE
Fail to start/build on 32-bit linux

### ISSUE THREAD

**Issue by SynedraAcus** [Anuken/Mindustry#248]
32-bit linux build is not available on itch.io, so I tried to get the game working otherwise. The bleeding edge jar complains about liblwgl being unavailable:

```
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at org.lwjgl.system.Library.loadSystem(Library.java:146)
	at org.lwjgl.system.Library.loadSystem(Library.java:66)
	at org.lwjgl.system.Library.<clinit>(Library.java:49)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:60)
	at org.lwjgl.system.MemoryStack.<init>(MemoryStack.java:60)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:79)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:70)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.lwjgl.system.MemoryStack.stackGet(MemoryStack.java:605)
	at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:614)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:38)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:78)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:88)
	at io.anuke.mindustry.desktop.DesktopLauncher.<init>(DesktopLauncher.java:24)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Disposed server.
java.lang.IllegalArgumentException: No setting with name "multithread" exists!
	at io.anuke.ucore.core.Settings.def(Settings.java:151)
	at io.anuke.ucore.core.Settings.getBool(Settings.java:101)
	at io.anuke.mindustry.desktop.CrashHandler.handle(CrashHandler.java:41)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:41)
```
I failed to understand how to  install LWGJL on 32-bit Mint, either (or if it is even possible, there apparently are some issues with 32bit support for this lib). If it matters, java version is:
```
$java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK Server VM (build 25.181-b13, mixed mode)
```
 Trying to build from source, I get this:

```
$./gradlew descktop:run
Downloading https://services.gradle.org/distributions/gradle-4.10.2-bin.zip
..........................................................................

Welcome to Gradle 4.10.2!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :android
No keystore info property found!

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

So the question is, is playing Mindustry on 32 bit linux possible? If yes, how do I build?

**Comment by TheChosenEvilOne** [comment]
LWJGL has dropped support for Linux x86

**Comment by Vistal3241** [comment]
> [As said above,](http://forum.lwjgl.org/index.php?topic=6086.0), LWJGL does not have 32-bit linux support. This means that Mindustry will not be able to run on 32-bit Linux devices at all.
> 
> As LWJGL is not my library, there's nothing I can do here.

Please, update and add support 32-bit linux. I cant download linux 64 bit or windows 32 bit((((
I hope play on chromebook. My chromebook Acer cb5-311p.

**Comment by Anuken** [comment]
@Vistal3241 I don't have any 32-bit linux devices, and setting up compilation for that platform is a long and involved process. I won't be supporting it.

**Comment by Vistal3241** [comment]
> @Vistal3241 I don't have any 32-bit linux devices, and setting up compilation for that platform is a long and involved process. I won't be supporting it.

Of course, thanks. Can you create chrome app? If not, i understand)
Think please...
It's hard, i know, but i hope play on my chromebook))
Sorry, im selfish...
