### ISSUE TITLE
Unsupported major minor version 52.0

### ISSUE THREAD

**Issue by pixaxeofpixie** [Anuken/Mindustry#2519]
**Platform**: *Mac*

**Build**: *9525*

**Issue**: *Im youse command 
which you gave me in last my issue.But after the command run the command Terminal give this error*

**Steps to reproduce**: *Open a mindustry BE version with .jar file run command in Terminal.*

**Link(s) to mod(s) used**: *None.*

**Save file**: *None*

**Crash report**: *Exception in thread "Thread-1" java.lang.UnsupportedClassVersionError: mindustry/desktop/DesktopLauncher : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Install Java 8 or above.

**Comment by pixaxeofpixie** [comment]
im install java 8

**Comment by pixaxeofpixie** [comment]
okay,in java control i see a path of java
but in folder i dont have anything with java
