### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Prosta4okua** [Anuken/Mindustry#2537]
1.
**Platform**: *Windows*

**Build**: *9635*

**Issue**: *Crash*

**Steps to reproduce**: *I just chose PvP or Sandbox and clicked play.*

**Save file**: *But now it works. https://cdn.discordapp.com/attachments/697832034072264785/753758254261207051/mapa.msav*

**Crash report**: *java.lang.NullPointerException
	at mindustry.world.blocks.defense.ForceProjector$ForceBuild.draw(ForceProjector.java:159)
	at mindustry.world.Block.drawBase(Block.java:226)
	at mindustry.graphics.BlockRenderer.drawBlocks(BlockRenderer.java:244)
	at mindustry.core.Renderer.draw(Renderer.java:254)
	at mindustry.core.Renderer.update(Renderer.java:85)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:151)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36).*

---
2. I launced the core on another sector. I forgot to report that.
**Old crash report**: *java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Unknown Source)
	at arc.graphics.g2d.SpriteCache.reserve(SpriteCache.java:272)
	at arc.graphics.g2d.MultiCacheBatch.reserve(MultiCacheBatch.java:68)
	at mindustry.graphics.FloorRenderer.cacheChunkLayer(FloorRenderer.java:220)
	at mindustry.graphics.FloorRenderer.cacheChunk(FloorRenderer.java:183)
	at mindustry.graphics.FloorRenderer.clearTiles(FloorRenderer.java:240)
	at mindustry.graphics.FloorRenderer.lambda$new$0(FloorRenderer.java:31)
	at arc.Events.lambda$fire$2(Events.java:30)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:30)
	at arc.Events.fire(Events.java:25)
	at mindustry.core.World.endMapLoad(World.java:202)
	at mindustry.core.World.loadGenerator(World.java:223)
	at mindustry.core.World.loadSector(World.java:230)
	at mindustry.core.Control.lambda$playSector$22(Control.java:320)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

---
3. I cannot change properly commands to blocks with a brush.
![image](https://user-images.githubusercontent.com/31485341/92824172-c4e34100-f3d6-11ea-8188-83c6b91eb518.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Prosta4okua** [comment]
4. Also removed the shield block, but the shield did not disappear
![image](https://user-images.githubusercontent.com/31485341/92824435-14297180-f3d7-11ea-8176-f4009f41cfc6.png)
