### ISSUE TITLE
Game crash when T5 ground support fires lazer at T5 air support and lazer hits a plast wall.

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#2651]
**Platform**: *Windows*

**Build**: *9857*

**Issue**: *Me, frost and Kit was playing sandbox pvp in v6, Frost tried to fire a T5 ground unit lazer to me. i was in T5 air support and his lazer hit both my projector and plast wall, then game instanly crashed, along side with the server.*

**Steps to reproduce**: *Shoot a T5 ground lazer to a T5 air support and hit both projector and a plast wall at the same time.*

**Link(s) to mod(s) used**: *No mod used.*

**Save file**: *On server, we didnt save.*

**Crash report**: *java.lang.NullPointerException
	at arc.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:55)
	at mindustry.ui.fragments.ChatFragment.draw(ChatFragment.java:143)
	at arc.scene.Group.drawChildren(Group.java:125)
	at arc.scene.Group.draw(Group.java:51)
	at arc.scene.Scene.draw(Scene.java:115)
	at mindustry.core.UI.update(UI.java:134)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:151)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36).*

-X-

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This crash log isn't relevant to the issue itself; post the *server* crash log.
