### ISSUE TITLE
Private server crash (steam)

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry#2676]
**Platform**: Windows

**Build**: *The build number under the title in the main menu. Required.* Steam 105

**Issue**: *Explain your issue in detail.* One's client crashes when trying to join friend's lobby

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I. My lobby
1) I started a PvP match, hosting the private server for 2 people.
2) Invited a friend to join the lobby.
3) Friend told me that his game crashed. Fortunately he gave me his crash report. (no. 1)

II. Friend's lobby
Then the friend tried to host a PvP match in an another map, but same issue had happened for me (my client crashed). See steps above. (crash no. 2)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* None

**Save file**: *The save file you were playing on when the bug happened, if applicable.* It's probably useless to send saves as PvP match is always paused when there's only 1 player.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
no. 1
```
java.lang.RuntimeException: Failed to to read remote method 'onInfoPopup'!
    at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:184)
    at mindustry.core.NetClient.lambda$new$4(NetClient.java:134)
    at mindustry.net.Net.handleClientReceived(Net.java:247)
    at mindustry.desktop.steam.SNet$1.update(SNet.java:83)
    at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
    at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
    at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
    at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
Caused by: java.nio.BufferUnderflowException
    at java.nio.Buffer.nextGetIndex(Buffer.java:506)
    at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:310)
    at mindustry.io.TypeIO.readString(TypeIO.java:310)
    at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:175)
    ... 7 more
```
no. 2
```
java.lang.RuntimeException: Failed to to read remote method 'onEffect'!
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:198)
	at mindustry.core.NetClient.lambda$new$4(NetClient.java:128)
	at mindustry.net.Net.handleClientReceived(Net.java:249)
	at mindustry.desktop.steam.SNet$1.update(SNet.java:82)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.us(Reads.java:54)
	at mindustry.io.TypeIO.readEffect(TypeIO.java:425)
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:191)
	... 7 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
	at arc.util.io.Reads.us(Reads.java:52)
	... 9 more
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your friend(s) are not running v105.

**Comment by TheSlaylord** [comment]
oh sh*t, they really were running 104.10
