### ISSUE TITLE
save with air/ground factory is broken

### ISSUE THREAD

**Issue by quanium** [Anuken/Mindustry#2678]
**Platform**: *Windows*

**Build**: *9890*

**Issue**: *update to latest version and load maps with factories are broken. sector not captured ALL building lost.*
[saves.zip](https://github.com/Anuken/Mindustry/files/5268026/saves.zip)

**Steps to reproduce**: *build on earlier version air/ground factory then update to latest*

**Link(s) to mod(s) used**: ---

**Save file**: *sector 124*

**Crash report**: 
[I] [GL] Version: OpenGL 4.3.0 / Intel / Intel(R) HD Graphics
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 1.8.0_121
[I] Total time to load: 6315
[I] Time to generate menu: 239.76746
[I] Fetched 3 global servers.
[E] mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveIO.load(SaveIO.java:163)
	at mindustry.io.SaveIO.load(SaveIO.java:140)
	at mindustry.io.SaveIO.load(SaveIO.java:134)
	at mindustry.game.Saves$SaveSlot.load(Saves.java:188)
	at mindustry.core.Control.lambda$playSector$22(Control.java:286)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:68)
	at mindustry.io.SaveVersion.read(SaveVersion.java:59)
	at mindustry.io.SaveIO.load(SaveIO.java:160)
	... 10 more
Caused by: java.io.IOException: Failed to read tile entity of block: air-factory
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:267)
	at mindustry.io.SaveVersion.lambda$read$0(SaveVersion.java:59)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:116)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:109)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:66)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Unknown revision '2' for entity type 'mono'
	at mindustry.gen.MinerUnit.read(MinerUnit.java:369)
	at mindustry.world.blocks.payloads.Payload.read(Payload.java:61)
	at mindustry.world.blocks.production.PayloadAcceptor$PayloadAcceptorBuild.read(PayloadAcceptor.java:160)
	at mindustry.world.blocks.units.UnitFactory$UnitFactoryBuild.read(UnitFactory.java:255)
	at mindustry.gen.Building.readAll(Building.java:529)
	at mindustry.io.SaveVersion.lambda$readMap$3(SaveVersion.java:264)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:116)
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:262)
	... 16 more

[E] mindustry.io.SaveIO$SaveException: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
	at mindustry.game.Saves$SaveSlot.load(Saves.java:194)
	at mindustry.core.Control.lambda$playSector$22(Control.java:286)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveIO.load(SaveIO.java:163)
	at mindustry.io.SaveIO.load(SaveIO.java:145)
	at mindustry.io.SaveIO.load(SaveIO.java:134)
	at mindustry.game.Saves$SaveSlot.load(Saves.java:188)
	... 7 more
Caused by: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:68)
	at mindustry.io.SaveVersion.read(SaveVersion.java:59)
	at mindustry.io.SaveIO.load(SaveIO.java:160)
	... 10 more
Caused by: java.io.IOException: Failed to read tile entity of block: air-factory
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:267)
	at mindustry.io.SaveVersion.lambda$read$0(SaveVersion.java:59)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:116)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:109)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:66)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Unknown revision '2' for entity type 'mono'
	at mindustry.gen.MinerUnit.read(MinerUnit.java:369)
	at mindustry.world.blocks.payloads.Payload.read(Payload.java:61)
	at mindustry.world.blocks.production.PayloadAcceptor$PayloadAcceptorBuild.read(PayloadAcceptor.java:160)
	at mindustry.world.blocks.units.UnitFactory$UnitFactoryBuild.read(UnitFactory.java:255)
	at mindustry.gen.Building.readAll(Building.java:529)
	at mindustry.io.SaveVersion.lambda$readMap$3(SaveVersion.java:264)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:116)
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:262)
	... 16 more

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your saves from that version are lost, but this won't happen again.
