### ISSUE TITLE
Game crash while joining server

### ISSUE THREAD

**Issue by bartox1** [Anuken/Mindustry#2680]
**Platform**: Windows

**Build**: Steam Build 105

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: It happend while joining my firend's private server.

**Link(s) to mod(s)**:Map "BoxFort"https://steamcommunity.com/sharedfiles/filedetails/?id=1876602615&searchtext=box

**Crash report**:
 java.lang.RuntimeException: Failed to to read remote method 'onEffect'!
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:198)
	at mindustry.core.NetClient.lambda$new$4(NetClient.java:128)
	at mindustry.net.Net.handleClientReceived(Net.java:249)
	at mindustry.desktop.steam.SNet$1.update(SNet.java:82)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.us(Reads.java:54)
	at mindustry.io.TypeIO.readEffect(TypeIO.java:425)
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:191)
	... 7 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
	at arc.util.io.Reads.us(Reads.java:52)
	... 9 more

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
Lol wut

**Comment by Esnardo** [comment]
are you sure you both have the same version?
