### ISSUE TITLE
Builds 9881 and up can't properly load saves from up to 9880 if they contain tier 2 units

### ISSUE THREAD

**Issue by blackouish** [Anuken/Mindustry#2710]
**Platform**: Linux (OpenJDK11)

**Build**: 9881 and up

**Issue**: Saves that contain tier 2 units and were made in builds up to 9880 can't be properly loaded in builds 9881 and up.

**How I happened across the issue**: I was playing the game without an Internet connection, then, when I had connection, I updated the game and, when attempting to load a save that contained tier 2 units, it said that the save file was corrupted.

**Steps to reproduce**: In a build up to 9880, make a unit factory, then connect it to an additive reconstructor (this will make tier 2 units). Then, save the game and try to load it in builds 9881 and up.

**Link(s) to mod(s) used**: [pre-V6 Example mod](https://github.com/Anuken/ExampleMod)

**Logs**: 
```
[E] mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "entities".
	at mindustry.io.SaveIO.load(SaveIO.java:163)
	at mindustry.io.SaveIO.load(SaveIO.java:140)
	at mindustry.io.SaveIO.load(SaveIO.java:134)
	at mindustry.game.Saves$SaveSlot.load(Saves.java:188)
	at mindustry.core.Control.lambda$playSector$22(Control.java:286)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.io.IOException: Error reading region "entities".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:68)
	at mindustry.io.SaveVersion.read(SaveVersion.java:60)
	at mindustry.io.SaveIO.load(SaveIO.java:160)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Unknown revision '2' for entity type 'mono'
	at mindustry.gen.MinerUnit.read(MinerUnit.java:686)
	at mindustry.io.SaveVersion.lambda$readEntities$5(SaveVersion.java:340)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:116)
	at mindustry.io.SaveVersion.readEntities(SaveVersion.java:332)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:116)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:109)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:66)
	... 12 more

[E] mindustry.io.SaveIO$SaveException: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "entities".
	at mindustry.game.Saves$SaveSlot.load(Saves.java:194)
	at mindustry.core.Control.lambda$playSector$22(Control.java:286)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "entities".
	at mindustry.io.SaveIO.load(SaveIO.java:163)
	at mindustry.io.SaveIO.load(SaveIO.java:145)
	at mindustry.io.SaveIO.load(SaveIO.java:134)
	at mindustry.game.Saves$SaveSlot.load(Saves.java:188)
	... 7 more
Caused by: java.io.IOException: Error reading region "entities".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:68)
	at mindustry.io.SaveVersion.read(SaveVersion.java:60)
	at mindustry.io.SaveIO.load(SaveIO.java:160)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Unknown revision '2' for entity type 'poly'
	at mindustry.gen.BuilderMinerUnit.read(BuilderMinerUnit.java:771)
	at mindustry.io.SaveVersion.lambda$readEntities$5(SaveVersion.java:340)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:116)
	at mindustry.io.SaveVersion.readEntities(SaveVersion.java:332)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:116)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:109)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:66)
	... 12 more
```
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate. No build will be able to load save from 9880, they are lost.
