### ISSUE TITLE
IllegalArgument Crash when launching into a new sector in campaign

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#2759]
> **Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.
- This issue will most likely be closed almost immediately because of the above note...

**Platform**: Windows

**Build**: Steam Build 106

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: Launching to an unexplored sector caused this crash.

**Link(s) to mod(s) used**: No mods enabled

**Save file**: [savefile.zip](https://github.com/Anuken/Mindustry/files/5295152/savefile.zip)

**Crash report**: [crash-report-09_28_2020_17_22_25.txt](https://github.com/Anuken/Mindustry/files/5295142/crash-report-09_28_2020_17_22_25.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
duplicate

**Comment by z0mbiesrock** [comment]
Bruh:
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at arc.graphics.g2d.SpriteCache.reserve(SpriteCache.java:272)
	at arc.graphics.g2d.MultiCacheBatch.reserve(MultiCacheBatch.java:68)
	at mindustry.graphics.FloorRenderer.cacheChunkLayer(FloorRenderer.java:220)
	at mindustry.graphics.FloorRenderer.cacheChunk(FloorRenderer.java:183)
	at mindustry.graphics.FloorRenderer.clearTiles(FloorRenderer.java:240)
	at mindustry.graphics.FloorRenderer.lambda$new$0(FloorRenderer.java:31)
	at arc.Events.lambda$fire$2(Events.java:30)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:30)
	at arc.Events.fire(Events.java:25)
	at mindustry.core.World.endMapLoad(World.java:207)
	at mindustry.core.World.loadGenerator(World.java:228)
	at mindustry.core.World.loadSector(World.java:235)
	at mindustry.core.Control.lambda$playSector$22(Control.java:325)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by Anuken** [comment]
***duplicate***
