### ISSUE TITLE
Mindustry crash ( steam build )

### ISSUE THREAD

**Issue by TimurMindustry** [Anuken/Mindustry#2801]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The save file you were playing on when the bug happened. REQUIRED for any issue that happens in-game.*

**Crash report**: *arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sounds/????.ogg
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:670)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:126)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sounds/????.ogg
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:105)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	... 6 more
Caused by: arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: File not found: sounds\????.ogg (internal)
	at arc.util.async.AsyncResult.get(AsyncResult.java:34)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:103)
	... 9 more
Caused by: arc.util.ArcRuntimeException: File not found: sounds\????.ogg (internal)
	at arc.files.Fi.read(Fi.java:200)
	at arc.backend.sdl.audio.Ogg$Sound.<init>(Ogg.java:52)
	at arc.backend.sdl.audio.ALAudio.newSound(ALAudio.java:88)
	at arc.backend.sdl.audio.ALAudio.newSound(ALAudio.java:15)
	at arc.assets.loaders.SoundLoader.loadAsync(SoundLoader.java:35)
	at arc.assets.loaders.SoundLoader.loadAsync(SoundLoader.java:15)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. Fill in the template.
2. Uninstall/unsubscribe to your mods.
