### ISSUE TITLE
backRegion is null for some reason

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2814]
**Platform**: Android 9

**Build**: 10177

**Issue**:
Routorio's combat router and reverout's bullets dont seem to be loaded? load() has this.super$load() and there aren't script errors.
There is an error which means that the backRegion is null which shouldn't ever happen

**Steps to reproduce**:
1. enable routorio
2. restart
3. look on screen

**Link(s) to mod(s) used**: deltanedas/routorio

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
Error for reverout:
```
[E] Error for routorio-reverout / /storage/emulated/0/Android/data/io.anuke.mindustry.be/files/mods/routorio/content/units/reverout.json:
arc.util.serialization.SerializationException: Serialization trace:
{}.weapons
weapons (adapter20)
	at mindustry.mod.ContentParser.readFields(ContentParser.java:588)
	at mindustry.mod.ContentParser.readFields(ContentParser.java:560)
	at mindustry.mod.ContentParser.lambda$new$6$ContentParser(ContentParser.java:294)
	at mindustry.mod.-$$Lambda$ContentParser$Q5Algh3tL1G3vUQfhWU0kPYepWM.run(Unknown Source:6)
	at mindustry.mod.ContentParser.lambda$read$10$ContentParser(ContentParser.java:369)
	at mindustry.mod.-$$Lambda$ContentParser$iSLOADv5Pgl942NWACW4kDGfqVQ.run(Unknown Source:8)
	at mindustry.mod.ContentParser.attempt(ContentParser.java:390)
	at mindustry.mod.ContentParser.lambda$c-LAFDNy0ZSkyRXJ-MIl9V87Jz8(Unknown Source:0)
	at mindustry.mod.-$$Lambda$ContentParser$c-LAFDNy0ZSkyRXJ-MIl9V87Jz8.get(Unknown Source:4)
	at arc.struct.Seq.each(Seq.java:200)
	at mindustry.mod.ContentParser.finishParsing(ContentParser.java:398)
	at mindustry.mod.Mods.loadContent(Mods.java:530)
	at mindustry.core.ContentLoader.createModContent(ContentLoader.java:72)
	at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:92)
	at mindustry.-$$Lambda$ClientLauncher$OEspX1Jk-8hCSNx_-ZAEe2Q0xRo.run(Unknown Source:0)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:334)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:109)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:135)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:424)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
Caused by: java.lang.RuntimeException: arc.util.serialization.SerializationException: Serialization trace:
{}.weapons[0].bullet
bullet (mindustry.type.Weapon)
	at mindustry.mod.ContentParser$2.internalRead(ContentParser.java:124)
	at mindustry.mod.ContentParser$2.readValue(ContentParser.java:113)
	at arc.util.serialization.Json.readValue(Json.java:987)
	at arc.util.serialization.Json.readValue(Json.java:1109)
	at mindustry.mod.ContentParser$2.internalRead(ContentParser.java:162)
	at mindustry.mod.ContentParser$2.readValue(ContentParser.java:113)
	at mindustry.mod.ContentParser.readFields(ContentParser.java:581)
	... 24 more
Caused by: arc.util.serialization.SerializationException: Serialization trace:
{}.weapons[0].bullet
bullet (mindustry.type.Weapon)
	at mindustry.mod.ContentParser.readFields(ContentParser.java:588)
	at mindustry.mod.ContentParser$1.lambda$new$8$ContentParser$1(ContentParser.java:97)
	at mindustry.mod.-$$Lambda$ContentParser$1$Z4DFl9hH7NjPKIlnSV5c3v7hs1M.parse(Unknown Source:2)
	at mindustry.mod.ContentParser$2.internalRead(ContentParser.java:122)
	... 30 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: 'backRegion' in BasicBulletType is missing!
	at mindustry.mod.ContentParser.lambda$checkNullFields$12(ContentParser.java:553)
	at mindustry.mod.-$$Lambda$ContentParser$Qz3jcbQ4OWJP42MZfUeQT1G0OYU.get(Unknown Source:4)
	at arc.struct.Seq.each(Seq.java:200)
	at mindustry.mod.ContentParser.checkNullFields(ContentParser.java:545)
	at mindustry.mod.ContentParser$2.readValue(ContentParser.java:114)
	at mindustry.mod.ContentParser.readFields(ContentParser.java:581)
	... 33 more
Caused by: java.lang.RuntimeException: 'backRegion' in BasicBulletType is missing!
	at mindustry.mod.ContentParser.lambda$checkNullFields$12(ContentParser.java:550)
	... 38 more
```

**Comment by DeltaNedas** [comment]
fixed
