### ISSUE TITLE
Rhino doesn't like variables and functions with the same name

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#2867]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *10286*

**Issue**: *When a variable and function has the same name, it is impossible to access the function from JS. Example: the `byte dump` and `boolean dump()` in https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/entities/comp/BuildingComp.java*

**Steps to reproduce**: *Code:
```
//...
extend(Building, {
    _proxItems: [],
    updateTile(){
      if(this._proxItems.length > 0){
        for(var i=0; i<this._proxItems.length; i++){
          this.items.set(this._proxItems[i], 1);
          this.dump(this._proxItems[i]);
        }
        this.items.clear();
      }
    },
//...
```
*

**Link(s) to mod(s) used**: *[https://github.com/sk7725/Testers](https://github.com/sk7725/Testers)(note that there is a workaround here, but this is still an issue)*

**Save file**: *This issue happens at the code level, thus I am **sure** that it is unrelated.*

**Crash report**: *
Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 10286
OS: Windows 10 x64
Java Version: 14.0.2
Java Architecture: 64
1 Mods: testers:0.1

rhino.EcmaError: TypeError: Cannot call property dump in object Building#84. It is not a function, it is "number". (smartsource#22)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3955)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3935)
	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3964)
	at rhino.ScriptRuntime.typeError3(ScriptRuntime.java:3986)
	at rhino.ScriptRuntime.notFunctionError(ScriptRuntime.java:4046)
	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2350)
	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2333)
	at rhino.gen.smartsource_5._c_anonymous_3(smartsource:22)
	at rhino.gen.smartsource_5.call(smartsource)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
	at rhino.gen.smartsource_5.call(smartsource)
	at rhino.Context.lambda$call$0(Context.java:515)
	at rhino.Context.call(Context.java:524)
	at rhino.Context.call(Context.java:515)
	at rhino.JavaAdapter.callMethod(JavaAdapter.java:549)
	at adapter5.updateTile(<adapter>)
	at mindustry.gen.Building.update(Building.java:952)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:67)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:57)
	at mindustry.gen.Groups.update(Groups.java:63)
	at mindustry.core.Logic.update(Logic.java:322)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:151)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
Proposed solution(naturally): change one of the names.

**Comment by Anuken** [comment]
This is known. Rhino doesn't have a way to differentiate between field and functions access.

**Comment by LeonorLunatech** [comment]
@Anuken Is this limitation still the case? "This is known. Rhino doesn't have a way to differentiate between field and functions access."

**Comment by Anuken** [comment]
Yes.
