### ISSUE TITLE
space shader crash

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#2880]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: `mac`

**Build**: `10313`

**Issue**: `crash when trying to compile from source of when trying to launch from bleeding edge.`

**Steps to reproduce**: `see above`

**Link(s) to mod(s) used**: `null`

**Save file**: `null`

**Crash report**: 

```
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: bleeding-edge build 10313
OS: Mac OS X x64
Java Version: 14.0.1
Java Architecture: 64
0 Mods

java.lang.IllegalArgumentException: Failed to compile shader: Fragment shader:
ERROR: 0:28: '*' does not operate on 'float' and 'int'

	at arc.graphics.gl.Shader.<init>(Shader.java:129)
	at mindustry.graphics.Shaders$LoadShader.<init>(Shaders.java:257)
	at mindustry.graphics.Shaders$SurfaceShader.<init>(Shaders.java:231)
	at mindustry.graphics.Shaders$SpaceShader.<init>(Shaders.java:205)
	at mindustry.graphics.Shaders.init(Shaders.java:47)
	at mindustry.core.Renderer.<init>(Renderer.java:44)
	at mindustry.ClientLauncher.setup(ClientLauncher.java:97)
	at mindustry.ClientLauncher.init(ClientLauncher.java:171)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:126)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

> (possibly) related issue yet with a different exception: #2878

**Comment by Quezler** [comment]
on second glance it looks like #2878 is exactly the same error, just with a totally different exception message 🤔

**Comment by zethnest** [comment]
Possible the same with #2874 ?

**Comment by Quezler** [comment]
yes, thanks for spotting, i'll hook that issue number to the pr as well so anuke can close it all with just one button press 👀

**Comment by Anuken** [comment]
fixed
