### ISSUE TITLE
getItem() in consumes.java is WAY too picky

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#2928]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *10302 & 10375*

**Issue**: *getItem() of https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/consumers/Consumers.java crashes if the block has ConsumeItemDynamic, ConsumeItemFilter, or none - when it should return the respective versions or `null`.*

**Steps to reproduce**: *call getItem() on a UnitFactory or some power generators.*

**Link(s) to mod(s) used**: *https://github.com/sk7725/Testers : [smartsource.js](https://github.com/sk7725/Testers/blob/master/scripts/smartsource.js)

**Save file**: *Happens codewise & instant crash, so I am 99.9% sure.*

**Crash report**: *Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 10302
OS: Windows 10 x64
Java Version: 14.0.2
Java Architecture: 64
1 Mods: testers:0.16

rhino.WrappedException: Wrapped java.lang.ClassCastException: class mindustry.world.blocks.defense.turrets.ItemTurret$1 cannot be cast to class mindustry.world.consumers.ConsumeItems (mindustry.world.blocks.defense.turrets.ItemTurret$1 and mindustry.world.consumers.ConsumeItems are in unnamed module of loader 'app') (smartsource#46)
	at rhino.Context.throwAsScriptRuntimeEx(Context.java:1668)
	at rhino.MemberBox.invoke(MemberBox.java:127)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
	at rhino.optimizer.OptRuntime.callProp0(OptRuntime.java:71)
	at rhino.gen.smartsource_5._c_anonymous_4(smartsource:46)
	at rhino.gen.smartsource_5.call(smartsource)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
	at rhino.gen.smartsource_5.call(smartsource)
	at rhino.Context.lambda$call$0(Context.java:515)
	at rhino.Context.call(Context.java:524)
	at rhino.Context.call(Context.java:515)
	at rhino.JavaAdapter.callMethod(JavaAdapter.java:549)
	at adapter10.onProximityUpdate(<adapter>)
	at mindustry.gen.Building.updateProximity(Building.java:703)
	at mindustry.world.Tile.changed(Tile.java:527)
	at mindustry.world.Tile.setBlock(Tile.java:231)
	at mindustry.world.Tile.setBlock(Tile.java:177)
	at mindustry.world.blocks.ConstructBlock.constructFinish(ConstructBlock.java:67)
	at mindustry.gen.Call.constructFinish(Call.java:244)
	at mindustry.world.blocks.ConstructBlock.constructed(ConstructBlock.java:114)
	at mindustry.world.blocks.ConstructBlock$ConstructBuild.construct(ConstructBlock.java:236)
	at mindustry.gen.BuilderMinerUnit.update(BuilderMinerUnit.java:1372)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:67)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:57)
	at mindustry.gen.Groups.update(Groups.java:63)
	at mindustry.core.Logic.update(Logic.java:322)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:151)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.lang.ClassCastException: class mindustry.world.blocks.defense.turrets.ItemTurret$1 cannot be cast to class mindustry.world.consumers.ConsumeItems (mindustry.world.blocks.defense.turrets.ItemTurret$1 and mindustry.world.consumers.ConsumeItems are in unnamed module of loader 'app')
	at mindustry.world.consumers.Consumers.getItem(Consumers.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at rhino.MemberBox.invoke(MemberBox.java:105)
	... 31 more
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
Please make it at least return null or not crash...

**Comment by AgentAvis** [comment]
Sounds like a non-issue to me.

**Comment by Anuken** [comment]
> return null

This is bad design. When you call this method, you probably need a result. Returning null just causes a vague `NullPointer` with no obvious cause. 

> if the block has ConsumeItemDynamic, ConsumeItemFilter,

These are fundamentally different, and can't be used in the same context. *You don't know* what the exact items consumed are in these cases.

> not crash

How? You either return something, or you crash. Returning `null` is not an option here.
