### ISSUE TITLE
Server creation crash

### ISSUE THREAD

**Issue by BuzzsawWWN** [Anuken/Mindustry#2937]
Alright, so I tried to make a server so me and my brother could play locally and it kept crashing

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: beta build 108
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.desktop.DesktopLauncher.updateLobby(DesktopLauncher.java:230)
	at mindustry.ui.dialogs.HostDialog.lambda$runHost$15(HostDialog.java:83)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by BuzzsawWWN** [comment]
Editing this to fit the template
