### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by gej302** [Anuken/Mindustry#2968]
**Issue**: The game crashes immediately when attempting to host multiplayer game.

**Steps to reproduce**: Started campaign with after deleting all game data from build 107.  Pressed "Host multiplayer game".  Immediate crash.  Attempted to host custom game with immediate crash.

**Save file**: Attached 0.msav zipped as
[0.zip](https://github.com/Anuken/Mindustry/files/5388500/0.zip)

**Crash report**: 
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: beta build 108
OS: Windows 10 x32
Java Version: 1.8.0_261
Java Architecture: 32
0 Mods

java.lang.NullPointerException
	at mindustry.desktop.DesktopLauncher.updateLobby(DesktopLauncher.java:230)
	at mindustry.ui.dialogs.HostDialog.lambda$runHost$15(HostDialog.java:83)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by gej302** [comment]
Apparently, it's not just a campaign issue, but it's been fixed supposedly.
