### ISSUE TITLE
Starting Ground Zero after Clear Game Data crashes

### ISSUE THREAD

**Issue by Nathmon565** [Anuken/Mindustry#3017]
**Platform**: Windows

**Build**: bleeding-edge 10613

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: Clear game data, then start Ground Zero on the campaign map

**Link(s) to mod(s) used**: N/A

**Save file**: N/A (Fresh save data)

**Crash report**:
Version: bleeding-edge build 10613
OS: Windows 10 x64
Java Version: 14.0.2
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.ui.dialogs.PlanetDialog.lambda$updateSelected$22(PlanetDialog.java:460)
	at arc.scene.Element$9.changed(Element.java:967)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:165)
	at arc.scene.Element.fire(Element.java:136)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:34)
	at arc.scene.Scene.touchUp(Scene.java:342)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:104)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:152)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
