### ISSUE TITLE
Mindustry beta 108 has crashed after trying to host a game

### ISSUE THREAD

**Issue by Uhrbaan** [Anuken/Mindustry#3026]
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: beta build 108
OS: Windows 10 x64
Java Version: 14.0.1
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.desktop.DesktopLauncher.updateLobby(DesktopLauncher.java:230)
	at mindustry.ui.dialogs.HostDialog.lambda$runHost$15(HostDialog.java:83)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by Quezler** [comment]
update to 109 and close this.
