### ISSUE TITLE
Poly crashes the game

### ISSUE THREAD

**Issue by T1murik** [Anuken/Mindustry#3052]
**Platform**: *Windows*

**Build**: *beta build 109*

**Issue**: *just a crash*

**Steps to reproduce**: 
1) enter v6.mindustry.ru
2) see the building drone(poly)
3) ~~???~~
4) crash!

**Link(s) to mod(s) used**: *no mods*

**Save file**: *how to get the server save?*

**Crash report**: 
```
Version: beta build 109
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at arc.math.geom.Position.within(Position.java:41)
	at mindustry.gen.BuilderLegsUnit.draw(BuilderLegsUnit.java:1749)
	at mindustry.entities.EntityGroup.lambda$draw$0(EntityGroup.java:83)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:67)
	at mindustry.entities.EntityGroup.draw(EntityGroup.java:80)
	at mindustry.core.Renderer.draw(Renderer.java:260)
	at mindustry.core.Renderer.update(Renderer.java:91)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:151)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by T1murik** [comment]
UPD: processor controlled toxopid tries to build
