### ISSUE TITLE
Game crashes on launch, fails to create the crash log.

### ISSUE THREAD

**Issue by blackouish** [Anuken/Mindustry#3285]
**Platform**: Linux

**Build**: 11107

**Issue**: When I attempt to launch the game, it fails before it can do anything with graphics.

**Steps to reproduce**: 1) `java -jar client-be-11107.jar`
2) It crashes, and fails to create a crash log. 

**Link(s) to mod(s) used**: None

**Game Output**:
```
[I] Initialized Discord rich presence.
arc.util.ArcRuntimeException: Couldn't load shared library 'libarc64.so' for target: Linux, 64-bit
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
        at arc.util.ArcNativesLoader.load(ArcNativesLoader.java:15)
        at arc.backend.sdl.SdlApplication.init(SdlApplication.java:77)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:29)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: java.lang.UnsatisfiedLinkError: /tmp/arc/4f109bb7/libarc64.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/arc/4f109bb7/libarc64.so)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:288)
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
        ... 4 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/arc/4f109bb7/libarc64.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/arc/4f109bb7/libarc64.so)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:294)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:260)
        ... 5 more
[E] Failed to save local crash report.: java.lang.NullPointerException
        at mindustry.net.CrashSender.createReport(CrashSender.java:29)
        at mindustry.net.CrashSender.send(CrashSender.java:87)
        at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:185)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:45)

[I] Sending crash report.
java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
        at arc.util.NetJavaImpl.lambda$http$0(NetJavaImpl.java:67)
        at arc.util.async.AsyncExecutor.lambda$submit$2(AsyncExecutor.java:31)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
``` 
 **Note**: Yes, It does look like missing libs on my part, but trust me, I updated everything on my pc and still got the same error.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
youre not on amd64
trick gradle to compile $(uname -m) natives or you cant play mindustry natively

**Comment by blackouish** [comment]
Actually, my arch IS amd64

**Comment by UltraBlackLinux** [comment]
Do you have access to the tmp dir?

**Comment by blackouish** [comment]
Yes.

**Comment by Anuken** [comment]
fixed
