### ISSUE TITLE
Java error when launching the server on beta 112.1

### ISSUE THREAD

**Issue by N07070** [Anuken/Mindustry#3294]
**Platform**: Debian Linux 10
**Build**: Server version Beta 112.1, downloaded from the github release page

**Issue**: 

```
$ mindustry-server » java -jar server-beta112.1.jar                                  1 ↵
java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569)
        at mindustry.net.Administration.loadLegacy(Administration.java:490)
        at mindustry.net.Administration.load(Administration.java:453)
        at mindustry.net.Administration.<init>(Administration.java:32)
        at mindustry.core.NetServer.<init>(NetServer.java:46)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:81)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:68)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:56)
[11-08-2020 14:54:20] [I] Server loaded. Type 'help' for help.
```

**Steps to reproduce**: See above, I just ran the server jar file with `java -jar server.jar`

**Java version** : 
```
mindustry-server » java -version                                              1 ↵
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-post-Debian-1deb10u1, mixed mode, sharing)
```

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

**Crash report**: N/A
---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

----

Comment : I'm just reporting this bug, but the server seems to run ok otherwise.

**Comment by Anuken** [comment]
That error isn't of any significance; it just failed to load legacy server data.

**Comment by DeltaNedas** [comment]
um, it's Debian **GNU/**Linux.

**Comment by summetdev** [comment]
@DeltaNedas ![Screenshot_20201102-224655_Discord-01.jpeg](https://user-images.githubusercontent.com/55251897/98485869-af4d9480-222a-11eb-8209-3faa98dfc36e.jpeg)
