### ISSUE TITLE
Save file issue on build 11140

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#3302]
**Platform**: Debian Linux (Kernel 5.9.0-1-amd64)

**Build**: 11140
**Issue**: Save file error when loading a sector in campaign. It spits out an error (also in terminal output) and resets the sector's progress. Screenshots:

https://cdn.discordapp.com/attachments/391072390999834626/775165949695230002/unknown.png
https://cdn.discordapp.com/attachments/391072390999834626/775165781277016098/unknown.png
https://cdn.discordapp.com/attachments/391072390999834626/775165594517110824/unknown.png

**Steps to reproduce**: Load a sector.

**Link(s) to mod(s) used**: None.

**Save file**: *attached as [errsave.zip](https://github.com/Anuken/Mindustry/files/5507550/errsave.zip)*

**Crash report**: CONSOLE OUTPUT:
```
[I] Initialized Discord rich presence.
[I] [GL] Version: OpenGL 4.6.0 / Intel / Mesa Intel(R) HD Graphics 520 (SKL GT2)
[I] [GL] Max texture size: 16384
[I] [GL] Max vert/frag shader FP precision: 23 / 23
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 11.0.9.1
[I] Loaded mod 'classicified' in 109.929504ms
[I] Total time to load: 4858
[I] Time to generate menu: 135.52191
[I] Fetched 6 global servers.
[E] mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveIO.load(SaveIO.java:163)
        at mindustry.io.SaveIO.load(SaveIO.java:140)
        at mindustry.io.SaveIO.load(SaveIO.java:134)
        at mindustry.game.Saves$SaveSlot.load(Saves.java:187)
        at mindustry.core.Control.lambda$playSector$23(Control.java:270)
        at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
        at arc.util.Timer$1.run(Timer.java:88)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:156)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:51)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:73)
        at mindustry.io.SaveVersion.read(SaveVersion.java:58)
        at mindustry.io.SaveIO.load(SaveIO.java:160)
        ... 10 more
Caused by: java.io.IOException: Failed to read tile entity of block: air-factory
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:260)
        at mindustry.io.SaveVersion.lambda$read$0(SaveVersion.java:58)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:121)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:114)
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:71)
        ... 12 more
Caused by: java.lang.NullPointerException
        at mindustry.world.blocks.payloads.Payload.read(Payload.java:60)
        at mindustry.world.blocks.production.PayloadAcceptor$PayloadAcceptorBuild.read(PayloadAcceptor.java:164)
        at mindustry.world.blocks.units.UnitFactory$UnitFactoryBuild.read(UnitFactory.java:274)
        at mindustry.gen.Building.readAll(Building.java:547)
        at mindustry.io.SaveVersion.lambda$readMap$3(SaveVersion.java:257)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:121)
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:255)
        ... 16 more

[E] mindustry.io.SaveIO$SaveException: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
        at mindustry.game.Saves$SaveSlot.load(Saves.java:193)
        at mindustry.core.Control.lambda$playSector$23(Control.java:270)
        at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
        at arc.util.Timer$1.run(Timer.java:88)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:156)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:51)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveIO.load(SaveIO.java:163)
        at mindustry.io.SaveIO.load(SaveIO.java:145)
        at mindustry.io.SaveIO.load(SaveIO.java:134)
        at mindustry.game.Saves$SaveSlot.load(Saves.java:187)
        ... 7 more
Caused by: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:73)
        at mindustry.io.SaveVersion.read(SaveVersion.java:58)
        at mindustry.io.SaveIO.load(SaveIO.java:160)
        ... 10 more
Caused by: java.io.IOException: Failed to read tile entity of block: air-factory
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:260)
        at mindustry.io.SaveVersion.lambda$read$0(SaveVersion.java:58)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:121)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:114)
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:71)
        ... 12 more
Caused by: java.lang.NullPointerException
        at mindustry.world.blocks.payloads.Payload.read(Payload.java:60)
        at mindustry.world.blocks.production.PayloadAcceptor$PayloadAcceptorBuild.read(PayloadAcceptor.java:164)
        at mindustry.world.blocks.units.UnitFactory$UnitFactoryBuild.read(UnitFactory.java:274)
        at mindustry.gen.Building.readAll(Building.java:547)
        at mindustry.io.SaveVersion.lambda$readMap$3(SaveVersion.java:257)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:121)
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:255)
        ... 16 more

[E] mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveIO.load(SaveIO.java:163)
        at mindustry.io.SaveIO.load(SaveIO.java:140)
        at mindustry.io.SaveIO.load(SaveIO.java:134)
        at mindustry.game.Saves$SaveSlot.load(Saves.java:187)
        at mindustry.core.Control.lambda$playSector$23(Control.java:270)
        at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
        at arc.util.Timer$1.run(Timer.java:88)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:156)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:51)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:73)
        at mindustry.io.SaveVersion.read(SaveVersion.java:58)
        at mindustry.io.SaveIO.load(SaveIO.java:160)
        ... 10 more
Caused by: java.io.IOException: Failed to read tile entity of block: air-factory
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:260)
        at mindustry.io.SaveVersion.lambda$read$0(SaveVersion.java:58)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:121)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:114)
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:71)
        ... 12 more
Caused by: java.lang.NullPointerException
        at mindustry.world.blocks.payloads.Payload.read(Payload.java:60)
        at mindustry.world.blocks.production.PayloadAcceptor$PayloadAcceptorBuild.read(PayloadAcceptor.java:164)
        at mindustry.world.blocks.units.UnitFactory$UnitFactoryBuild.read(UnitFactory.java:274)
        at mindustry.gen.Building.readAll(Building.java:547)
        at mindustry.io.SaveVersion.lambda$readMap$3(SaveVersion.java:257)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:121)
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:255)
        ... 16 more

[E] mindustry.io.SaveIO$SaveException: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
        at mindustry.game.Saves$SaveSlot.load(Saves.java:193)
        at mindustry.core.Control.lambda$playSector$23(Control.java:270)
        at mindustry.core.UI.lambda$loadAnd$10(UI.java:244)
        at arc.util.Timer$1.run(Timer.java:88)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:156)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:51)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveIO.load(SaveIO.java:163)
        at mindustry.io.SaveIO.load(SaveIO.java:145)
        at mindustry.io.SaveIO.load(SaveIO.java:134)
        at mindustry.game.Saves$SaveSlot.load(Saves.java:187)
        ... 7 more
Caused by: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:73)
        at mindustry.io.SaveVersion.read(SaveVersion.java:58)
        at mindustry.io.SaveIO.load(SaveIO.java:160)
        ... 10 more
Caused by: java.io.IOException: Failed to read tile entity of block: air-factory
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:260)
        at mindustry.io.SaveVersion.lambda$read$0(SaveVersion.java:58)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:121)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:114)
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:71)
        ... 12 more
Caused by: java.lang.NullPointerException
        at mindustry.world.blocks.payloads.Payload.read(Payload.java:60)
        at mindustry.world.blocks.production.PayloadAcceptor$PayloadAcceptorBuild.read(PayloadAcceptor.java:164)
        at mindustry.world.blocks.units.UnitFactory$UnitFactoryBuild.read(UnitFactory.java:274)
        at mindustry.gen.Building.readAll(Building.java:547)
        at mindustry.io.SaveVersion.lambda$readMap$3(SaveVersion.java:257)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:121)
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:255)
        ... 16 more
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Luxray5474** [comment]
Relevant screenshot 
![image](https://user-images.githubusercontent.com/30189017/98490726-6da7f400-2200-11eb-8574-6ede77fa18d4.png)

**Comment by Anuken** [comment]
Already fixed.

**Comment by DeltaNedas** [comment]
its GNU/Linux

**Comment by Anuken** [comment]
thanks for reminding us
