### ISSUE TITLE
java.lang.RuntimeException: arc.util.ArcRuntimeException: Asset not loaded

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#3414]
**Platform**: Windows 10

**Build**: Steam Build 113.2

**Issue**: 
According to the attached log, custom sound files are restricted to only one asset at a time (be it a block, unit, etc), and after loading once, the game is unable to load the sound file for future assets, breaking the entire mod and rendering the game unplyable.
```
[E] Error for diamond-ore-sporeclusterd / saves/mods/Diamond Ore/content/blocks/effect/sporeclusterd.hjson:
arc.util.serialization.SerializationException: Serialization trace:
{}.breakSound
breakSound (adapter20)
	at mindustry.mod.ContentParser.readFields(ContentParser.java:626)
	at mindustry.mod.ContentParser.readFields(ContentParser.java:596)
	at mindustry.mod.ContentParser.lambda$new$0(ContentParser.java:247)
	at mindustry.mod.ContentParser.lambda$read$8(ContentParser.java:403)
	at mindustry.mod.ContentParser.attempt(ContentParser.java:424)
	at arc.struct.Seq.each(Seq.java:200)
	at mindustry.mod.ContentParser.finishParsing(ContentParser.java:432)
	at mindustry.mod.Mods.loadContent(Mods.java:529)
	at mindustry.core.ContentLoader.createModContent(ContentLoader.java:72)
	at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:93)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:334)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:109)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:136)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:51)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.lang.RuntimeException: arc.util.ArcRuntimeException: Asset not loaded: sounds/sporesplat.ogg
	at mindustry.mod.ContentParser$2.internalRead(ContentParser.java:140)
	at mindustry.mod.ContentParser$2.readValue(ContentParser.java:129)
	at mindustry.mod.ContentParser.readFields(ContentParser.java:619)
	... 20 more
Caused by: arc.util.ArcRuntimeException: Asset not loaded: sounds/sporesplat.ogg
	at arc.assets.AssetManager.get(AssetManager.java:102)
	at mindustry.mod.ContentParser$1.lambda$new$7(ContentParser.java:97)
	at mindustry.mod.ContentParser$2.internalRead(ContentParser.java:138)
	... 22 more
```
@DeltaNedas thinks this error is impossible to avoid without scripting.

**Steps to reproduce**: 
[last_log.txt](https://github.com/Anuken/Mindustry/files/5543118/last_log.txt)

**Link(s) to mod(s) used**: https://github.com/z0mbiesrock/Diamond-Ore/tree/6.0

**Save file**: not applicable

**Crash report**: not applicable

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by z0mbiesrock** [comment]
updated log:
[last_log.txt](https://github.com/Anuken/Mindustry/files/5543211/last_log.txt)
