### ISSUE TITLE
poly formation build crash

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3449]
**Platform**: `ubuntu`

**Build**: `11362`

**Issue**: `server has crashed 3 times in a row with this same error:`

**Steps to reproduce**: `opened up the nydus bleeding edge server`

**Link(s) to mod(s) used**: `mods folder empty`

**Save file**: [autosavebe.msav.zip](https://github.com/Anuken/Mindustry/files/5561863/autosavebe.msav.zip)

**Crash report**: 

```
	at mindustry.gen.UnitEntityLegacyPoly.addBuild(UnitEntityLegacyPoly.java:1455)
	at mindustry.gen.UnitEntityLegacyPoly.addBuild(UnitEntityLegacyPoly.java:1439)
	at mindustry.ai.types.FormationAI.updateUnit(FormationAI.java:82)
	at mindustry.gen.UnitEntityLegacyPoly.update(UnitEntityLegacyPoly.java:1118)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:67)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:57)
	at mindustry.gen.Groups.update(Groups.java:67)
	at mindustry.core.Logic.update(Logic.java:350)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:89)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have nuzzled the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
just encountered a different trace, but probably fixed by the same commit:

```
	at mindustry.gen.PayloadUnit.addBuild(PayloadUnit.java:1542)
	at mindustry.gen.PayloadUnit.addBuild(PayloadUnit.java:395)
	at mindustry.ai.types.FormationAI.updateUnit(FormationAI.java:82)
	at mindustry.gen.UnitEntityLegacyPoly.update(UnitEntityLegacyPoly.java:1118)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:67)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:57)
	at mindustry.gen.Groups.update(Groups.java:67)
	at mindustry.core.Logic.update(Logic.java:350)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:89)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)

**Comment by Planebagels** [comment]
pog
