### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CergC4888** [Anuken/Mindustry#3452]
**Platform**: *Windows*

**Build**: *114.1.*

**Issue**: *l build salvo.*

**Steps to reproduce**: *I do not know.*

**Link(s) to mod(s) used**: *No.*

**Save file**: *.*

**Crash report**: *Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: beta build 114.1
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.NullPointerException
    at mindustry.world.Block.lambda$setBars$5(Block.java:358)
    at mindustry.ui.Bar.lambda$new$0(Bar.java:34)
    at arc.scene.Element.act(Element.java:79)
    at arc.scene.Group.act(Group.java:41)
    at arc.scene.Group.act(Group.java:41)
    at arc.scene.Group.act(Group.java:41)
    at arc.scene.Group.act(Group.java:41)
    at arc.scene.Group.act(Group.java:41)
    at arc.scene.Group.act(Group.java:41)
    at arc.scene.Group.act(Group.java:41)
    at arc.scene.Scene.act(Scene.java:170)
    at arc.scene.Scene.act(Scene.java:121)
    at mindustry.core.UI.update(UI.java:133)
    at arc.ApplicationCore.update(ApplicationCore.java:36)
    at mindustry.ClientLauncher.update(ClientLauncher.java:153)
    at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
    at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
    at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
    at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
[crash-report-11_18_2020_19_18_47.txt](https://github.com/Anuken/Mindustry/files/5562454/crash-report-11_18_2020_19_18_47.txt)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
