### ISSUE TITLE
V5 mod scripts completely broken in V6

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#3455]
**Platform**: Windows 10

**Build**: Steam 114.2

**Issue**: I have been trying to translate the V5 scripting to V6, but it seems that it's impossible to fix...

rhino.EcmaError: TypeError: Cannot call method "get" of undefined (multimelter#31)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3955)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3935)
	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3964)
	at rhino.ScriptRuntime.typeError2(ScriptRuntime.java:3980)
	at rhino.ScriptRuntime.undefCallError(ScriptRuntime.java:3994)
	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2339)
	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2333)
	at rhino.gen.multimelter_11._c_anonymous_1(multimelter:31)
	at rhino.gen.multimelter_11.call(multimelter)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
	at rhino.gen.multimelter_11.call(multimelter)
	at rhino.JavaAdapter.doCall(JavaAdapter.java:572)
	at rhino.JavaAdapter.callMethod(JavaAdapter.java:554)
	at adapter14.drawBase(<adapter>)
	at mindustry.graphics.BlockRenderer.drawBlocks(BlockRenderer.java:263)
	at mindustry.core.Renderer.draw(Renderer.java:256)
	at mindustry.core.Renderer.update(Renderer.java:92)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: https://github.com/z0mbiesrock/Diamond-Ore/tree/6.0

**Save file**: not applicable

**Crash report**:
[crash-report-11_18_2020_18_17_19.txt](https://github.com/Anuken/Mindustry/files/5563304/crash-report-11_18_2020_18_17_19.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
thats because v6 is completely different from v5

**Comment by z0mbiesrock** [comment]
> thats because v6 is completely different from v5

no shit sherlock. And fixing _one_ thing breaks **five** more things

**Comment by DeltaNedas** [comment]
this is clearly an issue with your mod, fix it

**Comment by Anuken** [comment]
The issue tracker is for bugs, not scripting help. Only report something if a **specific** modding feature is broken on Mindustry's end.
