### ISSUE TITLE
remote method unitClear without a core warning

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3461]
**Platform**: `linux`

**Build**: `11373`

**Issue**: `when you press v (respawn) while your team has no core you get this spammed in the console:`

**Steps to reproduce**: `be on a team with no core, then control a block or non-core unit`

**Link(s) to mod(s) used**: `simple team switch plugin`

**Save file**: `no :)`

**Crash report**: 

```
java.lang.RuntimeException: Failed to to read remote method 'unitClear'!
	at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:166)
	at mindustry.core.NetServer.lambda$new$7(NetServer.java:252)
	at mindustry.net.Net.handleServerReceived(Net.java:278)
	at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:117)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
Caused by: java.lang.NullPointerException
	at mindustry.input.InputHandler.unitClear(InputHandler.java:361)
	at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:163)
	... 6 more
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reposted.**

**Comment by Anuken** [comment]
Is your client modified? That stack trace doesn't make any sense. [There's nothing to be null at that line.](https://github.com/Anuken/Mindustry/blob/72d5a8a768384490d70c48022c223552e988fe33/core/src/mindustry/input/InputHandler.java#L361)

`player` is checked for being null beforehand, and `unit()` can't be null.

**Comment by Anuken** [comment]
Further testing: Spawning a random unit, having the player control it and doing:

> js Groups.player.find(u => true).team(Team.derelict)

in the server console leads to a player controlling a unit with no core, as you mention in the issue.

Pressing V in this scenario does nothing interesting - no errors, no logs on either end. Other teams (e.g. purple) have the same effect.

I'll assume this is something to do with a modified client or very specific to your plugin until more information is given.

**Comment by Quezler** [comment]
hmm, strange then 🤔
