### ISSUE TITLE
SectorPreset on modded planets goes h

### ISSUE THREAD

**Issue by GlennFolker** [Anuken/Mindustry#3589]
**Platform**: *Windows 10 64-bit*

**Build**: `v117`

**Issue**:
Title says all. When you try to launch into a `SectorPreset` in a modded `Planet`, the game crashes.

**Steps to reproduce**:
1. Make a mod with this script:
    ```js
    //main.js

    const planet = new JavaAdapter(Planet, {}, "planet", Planets.sun, 3, 1);
    planet.meshLoader = () => new HexMesh(planet, 6);
    planet.generator = new SerpuloPlanetGenerator();
    planet.atmosphereColor = Color.valueOf("f69420");
    planet.startSector = 30;

    const sector = new SectorPreset("sector", planet, 30);
    sector.alwaysUnlocked = true;
    sector.captureWave = 15;
    ```
2. Run `Mindustry.jar`.
3. Go to **Campaign**.
4. Go to the newly created `planet`, and launch to the only unlocked sector there.
5. ~~Experience pain.~~

**Link(s) to mod(s) used**: *Every mod, nevertheless*

**Save file**: ...

**Crash report**:
```css
Mindustry has crashed. How unfortunate.
Version: beta build 117
OS: Windows 10 x64
Java Version: 15.0.1
Java Architecture: 64
1 Mods: mod:6.9

arc.util.serialization.SerializationException: Serialization trace:
{}.sector
sector (mindustry.game.Rules)
	at arc.util.serialization.Json.readFields(Json.java:911)
	at arc.util.serialization.Json.readValue(Json.java:1086)
	at arc.util.serialization.Json.readValue(Json.java:987)
	at arc.util.serialization.Json.fromJson(Json.java:828)
	at mindustry.io.JsonIO.read(JsonIO.java:60)
	at mindustry.io.SaveVersion.getMeta(SaveVersion.java:42)
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.getMeta(SaveIO.java:82)
	at mindustry.game.Saves$SaveSlot.save(Saves.java:202)
	at mindustry.game.Saves.saveSector(Saves.java:131)
	at mindustry.core.Control.lambda$playSector$27(Control.java:375)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:240)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.lang.NullPointerException: Cannot read field "sectors" because the return value of "mindustry.core.ContentLoader.getByName(mindustry.ctype.ContentType, String)" is null
	at mindustry.io.JsonIO$2.read(JsonIO.java:87)
	at mindustry.io.JsonIO$2.read(JsonIO.java:78)
	at arc.util.serialization.Json.readValue(Json.java:1093)
	at arc.util.serialization.Json.readFields(Json.java:904)
	... 16 more

```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There is no support for custom planet mods. Figure it out yourself until this is officially supported.

**Comment by DeltaNedas** [comment]
is it some map tag or something we need to add

**Comment by GlennFolker** [comment]
Fixed this
