### ISSUE TITLE
Client Crashing when placing conveyor at edge of map

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry#3645]
**Platform**: Linux

**Build**: 118

**Issue**: Title

**Steps to reproduce**: Title

**Crash report**:
```
[E] java.lang.NullPointerException
	at mindustry.world.modules.ItemModule.read(ItemModule.java:341)
	at mindustry.gen.Building.readBase(Building.java:938)
	at mindustry.gen.Building.readAll(Building.java:581)
	at mindustry.core.NetClient.blockSnapshot(NetClient.java:462)
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:42)
	at mindustry.core.NetClient.lambda$new$4(NetClient.java:130)
	at mindustry.net.Net.handleClientReceived(Net.java:258)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:62)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

[W] Missing entity at sand:air:air[201,28] entity=null:derelict. Skipping block snapshot.
[E] java.lang.NullPointerException
	at mindustry.world.modules.ItemModule.read(ItemModule.java:341)
	at mindustry.gen.Building.readBase(Building.java:938)
	at mindustry.gen.Building.readAll(Building.java:581)
	at mindustry.core.NetClient.blockSnapshot(NetClient.java:462)
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:42)
	at mindustry.core.NetClient.lambda$new$4(NetClient.java:130)
	at mindustry.net.Net.handleClientReceived(Net.java:258)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:62)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That's not a crash report.

**Comment by UltraBlackLinux** [comment]
@Anuken I added the 4 missing lines in the log. Makes a huge difference.
BTW: It is not bc of the custom client, all vanilla players have that.

**Comment by Anuken** [comment]
That's still not a crash report. You posted completely unrelated warning logs.

**Comment by UltraBlackLinux** [comment]
@Anuken if you still don't consider these errors a crash report, then crash your client yourself, it isn't that hard.

**Comment by Anuken** [comment]
> if you still don't consider these errors a crash report

Why would anyone consider **errors** crashes? I don't understand what you're trying to do here. Did you just add the standard crash report header to some errors you got in the console? *Why?*

> then crash the client yourself, it isn't that hard.

It is, actually. You haven't provided a save or screenshot, despite the former being listed as **ABSOLUTELY REQUIRED IN ALL CAPS.**

**Comment by UltraBlackLinux** [comment]
@Anuken it was on a server, and it happened to other people, too. I didn't even discover it, but decided to make a crash report here...

**Comment by Anuken** [comment]
> how am I supposed to make a screenshot of the client crashing?

A screenshot of the *map*, not your client crashing.

I don't understand. *Did your client crash, or did it not?* If not, why did you make up a crash report with random console errors? Why didn't you post the save? Why didn't you send the actual crash in your crash report/game folder?

**Comment by UltraBlackLinux** [comment]
The client crashed.

**Comment by Anuken** [comment]
Obviously, but that doesn't answer any of my questions.

**Comment by UltraBlackLinux** [comment]
The Log I sent is all I got, before the client crashed.

**Comment by Anuken** [comment]
Don't look at the log for crash reports, there's a folder for that.

**Comment by UltraBlackLinux** [comment]
That's where I looked...

**Comment by UltraBlackLinux** [comment]
Recreated the crash:
![Screenshot_20201129_164538](https://user-images.githubusercontent.com/62404294/100546558-5047d200-3262-11eb-8268-c6110cff8c8e.png)
```
java.lang.NullPointerException
	at mindustry.world.blocks.distribution.Conveyor.thisPlaceableOn(Conveyor.java:149)
	at mindustry.world.blocks.distribution.Conveyor.getReplacement(Conveyor.java:115)
	at mindustry.input.InputHandler.lambda$updateLine$32(InputHandler.java:900)
	at arc.struct.Seq.each(Seq.java:200)
	at mindustry.input.InputHandler.updateLine(InputHandler.java:899)
	at mindustry.input.InputHandler.updateLine(InputHandler.java:913)
	at mindustry.input.DesktopInput.pollInput(DesktopInput.java:593)
	at mindustry.input.DesktopInput.update(DesktopInput.java:395)
	at mindustry.core.Control.update(Control.java:510)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:162)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

**Comment by UltraBlackLinux** [comment]
@Anuken This is the version that I know is broken (it's not Foo's client, vanilla players had it too): https://github.com/blahblahbloopster/mindustry-client-v6/releases/tag/4

**Comment by Anuken** [comment]
1. If you got a message like that, *why didn't you just send it?* It tells you where the log is saved, you don't need to make anything up!
2. No, it most definitely is that client. That stack trace is unusable and points to a crash in `thisPlaceableOn`, which is a method that **doesn't even exist** in my source code. The line numbers all point to places that are unrelated. If it happens on a vanilla client, then *send me a crash from that client*, not this.

**Comment by UltraBlackLinux** [comment]
@Anuken As I said, some vanilla player showed me this, and I didn't make anything up.
Thanks, and I am very sorry. (lol)
