### ISSUE TITLE
Crash while loading

### ISSUE THREAD

**Issue by Horizon333** [Anuken/Mindustry#3695]
**Platform**: Windows 32bit

**Build**: release build 120

**Issue**: Every time i try to start the game i get a "out of memory" crash message

**Steps to reproduce**: i just start the game, i don't have a lot of ram, 2.9gb available in total used mostly by the windows malware program that i can't turn off, it might have to do with it, but when i tried the alpha version 1 time i got it working and when it loaded at first it just worked fine

**Link(s) to mod(s) used**: none

**Crash report**: Version: release build 120
OS: Windows 10 x32
Java Version: 1.8.0_201-1-ojdkbuild
Java Architecture: 32
0 Mods

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:670)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:137)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:105)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	... 6 more
Caused by: arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load file: sprites/sprites.png
	at arc.util.async.AsyncResult.get(AsyncResult.java:34)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:103)
	... 9 more
Caused by: arc.util.ArcRuntimeException: Couldn't load file: sprites/sprites.png
	at arc.graphics.Pixmap.<init>(Pixmap.java:93)
	at arc.graphics.TextureData$Factory.loadFromFile(TextureData.java:96)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:38)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:17)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error loading pixmap: Out of memory
	at arc.graphics.Pixmap$NativePixmap.<init>(Pixmap.java:596)
	at arc.graphics.Pixmap.<init>(Pixmap.java:91)
	... 9 more
[crash-report-12_01_2020_16_33_07.txt](https://github.com/Anuken/Mindustry/files/5623769/crash-report-12_01_2020_16_33_07.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
Might not be related but you definitely should get rid of that malware

**Comment by Anuken** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

No, you haven't.

**Comment by Horizon333** [comment]
> > I have searched the closed and open issues to make sure that this problem has not already been reported.
> 
> No, you haven't.

Sorry but is my error Error loading pixmap?, if yes how do i resolve it, clear the mindustry temp?

**Comment by Anuken** [comment]
There is no known solution.
