### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Prosta4okua** [Anuken/Mindustry#3702]
**Platform**: *Win 10 x64*

**Build**: *120.*

**Issue**: *I wanted to trace a player*

**Steps to reproduce**: **

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *
Mindustry has crashed. How unfortunate.
Version: steam build 120
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
18 Mods: dev-mode:2.3.1, rtfm:2.10.4, українізатор-всесвіту:1, boss-constructors:0.1, cheat-block:1, cobalt-mod:1.0, example-mod:1, hacker-tools:2.0.0, multi-lib:1.4.7, opore-mod:63, shadow-mod:1.09.4, stalloblast:3.1, steam-power:1.6, xelos-pixel-texturepack:0.2.2, xzimur.noisetech:4.b-104.10, diamond-ore:[#9cb6f4]2.0.2[], goldmod:2.0 alpha b4, routorio:2.34.5

java.lang.NullPointerException
	at mindustry.core.NetServer.adminRequest(NetServer.java:709)
	at mindustry.gen.Call.adminRequest(Call.java:34)
	at mindustry.ui.fragments.PlayerListFragment.lambda$rebuild$20(PlayerListFragment.java:144)
	at arc.scene.Element.lambda$clicked$2(Element.java:902)
	at arc.scene.Element$4.clicked(Element.java:911)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:34)
	at arc.scene.Scene.touchUp(Scene.java:342)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:143)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Were you hosting a local server?

**Comment by Prosta4okua** [comment]
> Were you hosting a local server?

I'm hosting. No one has connected from the local network. Only via Steam and port-forwarding.
