### ISSUE TITLE
Mindustry crashes while starting up

### ISSUE THREAD

**Issue by Kamikazafly** [Anuken/Mindustry#3723]
**Platform**: *Windows 10 32 bit/

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Version: steam build 120.2

**Issue**: *Explain your issue in detail.*
Cant start up game. game closes when its loading V6. previous version i had no problems at all.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Starting up game. it loads till i get error message. V6. btw
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
[crash-report-12_02_2020_17_55_07.txt](https://github.com/Anuken/Mindustry/files/5630840/crash-report-12_02_2020_17_55_07.txt)

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 120.2
OS: Windows 10 x32
Java Version: 1.8.0_201-1-ojdkbuild
Java Architecture: 32
0 Mods

arc.util.ArcRuntimeException: Couldn't load file: sprites/sprites.png
	at arc.graphics.Pixmap.<init>(Pixmap.java:93)
	at arc.graphics.gl.FileTextureData.prepare(FileTextureData.java:44)
	at arc.graphics.TextureData.getPixmap(TextureData.java:46)
	at arc.graphics.g2d.TextureAtlas.lambda$getPixmap$1(TextureAtlas.java:161)
	at arc.struct.ObjectMap.get(ObjectMap.java:316)
	at arc.graphics.g2d.TextureAtlas.getPixmap(TextureAtlas.java:161)
	at arc.graphics.g2d.TextureAtlas.getPixmap(TextureAtlas.java:156)
	at mindustry.game.Schematics.lambda$new$2(Schematics.java:75)
	at arc.Events.lambda$fire$2(Events.java:30)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:30)
	at arc.Events.fire(Events.java:25)
	at mindustry.ClientLauncher.update(ClientLauncher.java:146)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.io.IOException: Error loading pixmap: Corrupt JPEG
	at arc.graphics.Pixmap$NativePixmap.<init>(Pixmap.java:596)
	at arc.graphics.Pixmap.<init>(Pixmap.java:91)
	... 16 more

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

No, you haven't. This has been reported many times.
