### ISSUE TITLE
Failed to to read remote method 'entitySnapshot'

### ISSUE THREAD

**Issue by matkoniecz** [Anuken/Mindustry#3727]
**Platform**: Linux

**Build**: 120.2

**Issue**: I played, suddennly I got message about unexpected error (sorry, failed to capture it). Logs had:

```
[I] Connecting to server: /91.134.217.10:6006
[I] Received world data: 1936182 bytes.
[I] Disconnecting.
[I] Connecting to server: /168.119.120.239:16567
[I] Received world data: 3119 bytes.
[I] Disconnecting.
[I] Connecting to server: /168.119.120.239:16006
[I] Received world data: 17175 bytes.
[W] Missing entity at darksand:air:air[137,164] entity=null:derelict. Skipping block snapshot.
[W] Missing entity at dacite:air:air[80,144] entity=null:derelict. Skipping block snapshot.
[W] Missing entity at dacite:air:air[170,128] entity=null:derelict. Skipping block snapshot.
[E] java.lang.NullPointerException

[I] Disconnecting.
[E] java.lang.RuntimeException: Failed to to read remote method 'entitySnapshot'!
        at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:147)
        at mindustry.core.NetClient.lambda$new$4(NetClient.java:127)
        at mindustry.net.Net.handleClientReceived(Net.java:258)
        at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:62)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.lang.RuntimeException: java.io.EOFException
        at arc.util.io.Reads.b(Reads.java:76)
        at arc.util.io.Reads.b(Reads.java:67)
        at mindustry.io.TypeIO.readBytes(TypeIO.java:547)
        at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:144)
        ... 7 more
Caused by: java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
        at arc.util.io.Reads.b(Reads.java:73)
        ... 10 more
```

**Steps to reproduce**: No idea.

**Link(s) to mod(s) used**: Not applicable

**Save file**: I got kicked from server, so I am unable to save game.

**Crash report**: Where I can find them?

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** I also checked https://github.com/Anuken/Mindustry/compare/v120.2...master
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+is%3Aopen+Failed+to+to+read+remote+method+%27entitySnapshot%27

**Comment by Anuken** [comment]
This doesn't happen to me on any device, and won't be fixed.

**Comment by LeoSko** [comment]
Looks like report from my server.

I've had reports of such error on my server as well as facing it myself once or twice in the past week. The strange thing is that it doesn't crash all clients, but only some specific one and started to happen only in v6. I have some custom manipulations of events from inside of the server which potentially could trigger the weirdness. 

@Anuken, is it possible at tileDamaged and tileDestroyed when being called one after another to produce any kind of race condition on client side with such side effect?
