### ISSUE TITLE
Exception when building

### ISSUE THREAD

**Issue by SilverLuke** [Anuken/Mindustry#374]
This exception occurs when the player is inside a "blueprint" and he start to build that "blueprint".
This is the stack trace:
`java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
        at com.badlogic.gdx.utils.Queue.removeIndex(Queue.java:220)
        at com.badlogic.gdx.utils.Queue.removeValue(Queue.java:213)
        at io.anuke.mindustry.entities.traits.BuilderTrait.updateBuilding(BuilderTrait.java:184)
        at io.anuke.mindustry.entities.Player.update(Player.java:553)
        at io.anuke.ucore.entities.Entities.update(Entities.java:63)
        at io.anuke.mindustry.core.Logic.update(Logic.java:209)
        at io.anuke.ucore.modules.ModuleCore.render(ModuleCore.java:60)
        at io.anuke.mindustry.Mindustry.render(Mindustry.java:43)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at io.anuke.mindustry.desktop.DesktopLauncher.<init>(DesktopLauncher.java:15)
        at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:30)
`
Ps: Amazing game.

**Comment by Anuken** [comment]
Looks like an issue in libGDX, might need to wait until they fix it: https://github.com/libgdx/libgdx/issues/5471.
