### ISSUE TITLE
Floating window's crash

### ISSUE THREAD

**Issue by ArthurDavletov** [Anuken/Mindustry#3744]
**Platform**: *Android 10.0. MIUI 12.0.5.0*

**Build**: *release build 120.3*

**Issue**: *The game crashes when I put it in a floating window*

**Steps to reproduce**: *I opened the game. Then I went to the apps menu. Then I tried to display it as a floating window, but the game ended. But with split screen everything is fine*

**Link(s) to mod(s) used**: *Original from Google Play*

**Save file**: *The game also crashes when I try to output a file with an crash logs. If this item is about the map in the game, then this problem is in any part of the game*

**Crash report**: *The game also crashes. But I can to send Xiaomi crashtext.*

Floating window:
```
java.lang.IllegalStateException: Frame buffer couldn't be constructed: missing attachment
	at arc.graphics.gl.GLFrameBuffer.build(GLFrameBuffer.java:288)
	at arc.graphics.gl.GLFrameBuffer.invalidateAllFrameBuffers(GLFrameBuffer.java:97)
	at arc.backend.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:264)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1549)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1280)
```
When I try to output crashlog:

```
arc.util.ArcRuntimeException: Error writing file: /document/raw:/storage/emulated/0/Download/Мусор/MindustryCrashAnotherTest (absolute)
	at arc.files.Fi.writeString(Fi.java:509)
	at arc.files.Fi.writeString(Fi.java:493)
	at arc.files.Fi.writeString(Fi.java:483)
	at mindustry.ui.dialogs.SettingsMenuDialog.lambda$new$18$SettingsMenuDialog(SettingsMenuDialog.java:218)
	at mindustry.ui.dialogs.-$$Lambda$SettingsMenuDialog$Gw15vJpr91Jzft_koLIAZbEaHKs.get(Unknown Source:4)
	at mindustry.android.AndroidLauncher$1.lambda$showFileChooser$1$AndroidLauncher$1(AndroidLauncher.java:98)
	at mindustry.android.-$$Lambda$AndroidLauncher$1$T2t6Y7IKnmu8jovOUC46AWtJxeI.run(Unknown Source:6)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:414)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1581)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1280)
Caused by: arc.util.ArcRuntimeException: Error writing file: /document/raw:/storage/emulated/0/Download/Мусор/MindustryCrashAnotherTest (absolute)
	at arc.files.Fi.writer(Fi.java:469)
	at arc.files.Fi.writeString(Fi.java:506)
	... 9 more
Caused by: java.io.FileNotFoundException: /document/raw:/storage/emulated/0/Download/Мусор/MindustryCrashAnotherTest: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at arc.files.Fi.writer(Fi.java:461)
	... 10 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7448)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 12 more
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The game does not support floating windows or splitscreen. I explicitly disable it in the manifest.
