### ISSUE TITLE
asdf

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [Anuken/Mindustry#3868]
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: beta build 111
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.async.PhysicsProcess.begin(PhysicsProcess.java:60)
	at mindustry.async.AsyncCore.begin(AsyncCore.java:47)
	at mindustry.ClientLauncher.update(ClientLauncher.java:149)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by ThisIsACoolBoy** [comment]
everytime i get into mindustry this happens

**Comment by kiVts** [comment]
I think you better use a template

**Comment by Erisfiregamer1** [comment]
T e m p l a t e ?

**Comment by kiVts** [comment]
What is a template?

**Comment by ItsJonyBoi** [comment]
Have you tried reinstalling the game?

**Comment by DeltaNedas** [comment]
why did you choose to delete the template

**Comment by Anuken** [comment]
> beta build 111

yikes

**Comment by ThisIsACoolBoy** [comment]
hold up how tf does the crash show 111 instead of 121 or etc
lmfao

**Comment by ThisIsACoolBoy** [comment]
> 
> 
> why did you choose to delete the template

i pretty much fucked up

**Comment by ThisIsACoolBoy** [comment]
> 
> 
> @ThisIsACoolBoy Have you tried reinstalling the game?

yes
