### ISSUE TITLE
Crash when select launchpad dest same map w/o click on any sectors

### ISSUE THREAD

**Issue by findoff** [Anuken/Mindustry#3896]
**Platform**: Windows 7 x64

**Build**: 121.2 (steam)

**Issue**: Game crashes

**Steps to reproduce**: When accidentally click select instantly after click launchpad dist selection. I.e Click dist select over launchpad => click select w/o click to other sectors onto world map.

**Save file**: [mindustry-campaign-saves.zip](https://github.com/Anuken/Mindustry/files/5668378/mindustry-campaign-saves.zip) (tested at extraction outpost)

**(Crash) logs**:
```
Version: steam build 121.2
OS: Windows 7 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.ui.dialogs.PlanetDialog.playSelected(PlanetDialog.java:800)
	at mindustry.ui.dialogs.PlanetDialog.lambda$updateSelected$32(PlanetDialog.java:770)
	at arc.scene.Element.lambda$clicked$2(Element.java:893)
	at arc.scene.Element$4.clicked(Element.java:902)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:34)
	at arc.scene.Scene.touchUp(Scene.java:357)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:143)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```
---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.
