### ISSUE TITLE
Unable to launch mod sector

### ISSUE THREAD

**Issue by summetdev** [Anuken/Mindustry#3940]
**Platform**: Windows

**Build**: v120 (not works on 121.2 too)

**Issue**:
When trying to launch on a modified planet, the game crashes.

**Steps to reproduce**:
1. Create a mod planet.
2. Try to launch to any planet sector.

**Links to mods used**:
[SolarSystem-1.0-Desktop.zip](https://github.com/Anuken/Mindustry/files/5683297/SolarSystem-1.0-Desktop.zip)

**Crash logs**:
[crash-report.txt](https://github.com/Anuken/Mindustry/files/5683276/crash-report-12_12_2020_17_44_25.txt)
```
arc.util.serialization.SerializationException: Serialization trace:
{}.sector
sector (mindustry.game.Rules)
	at arc.util.serialization.Json.readFields(Json.java:911)
	at arc.util.serialization.Json.readValue(Json.java:1086)
	at arc.util.serialization.Json.readValue(Json.java:987)
	at arc.util.serialization.Json.fromJson(Json.java:828)
	at mindustry.io.JsonIO.read(JsonIO.java:60)
	at mindustry.io.SaveVersion.getMeta(SaveVersion.java:42)
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.getMeta(SaveIO.java:82)
	at mindustry.game.Saves$SaveSlot.save(Saves.java:202)
	at mindustry.game.Saves.saveSector(Saves.java:131)
	at mindustry.core.Control.lambda$playSector$27(Control.java:394)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:240)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.lang.NullPointerException
	at mindustry.io.JsonIO$2.read(JsonIO.java:87)
	at mindustry.io.JsonIO$2.read(JsonIO.java:78)
	at arc.util.serialization.Json.readValue(Json.java:1093)
	at arc.util.serialization.Json.readFields(Json.java:904)
	... 16 more
```

---

- [X] I have updated to the latest release to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> modified planet

This is not supported.

**Comment by DeltaNedas** [comment]
anuke how do you make it not have stroke

**Comment by summetdev** [comment]
> This is not supported.

will it be?

**Comment by z0mbiesrock** [comment]
> > This is not supported.
> 
> will it be?

Nope; you'll have to wait for when planets officially get added to allow for modding of them
