### ISSUE TITLE
Mindustry has crashed. How unfortunate.

### ISSUE THREAD

**Issue by EmenAitch** [Anuken/Mindustry#4166]
**Platform**: *Windows 10 x32*

**Build**: *release build 122.*
Java Version: 1.8.0_201-1-ojdkbuild
Java Architecture: 32
0 Mods

**Issue**: *Force Close at menu.*

**Steps to reproduce**: *no clue*

**Link(s) to mod(s) used**: *not use mod.*

**Save file**: *.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:670)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:137)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:105)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	... 6 more
Caused by: arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load file: sprites/sprites.png
	at arc.util.async.AsyncResult.get(AsyncResult.java:34)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:103)
	... 9 more
Caused by: arc.util.ArcRuntimeException: Couldn't load file: sprites/sprites.png
	at arc.graphics.Pixmap.<init>(Pixmap.java:93)
	at arc.graphics.TextureData$Factory.loadFromFile(TextureData.java:96)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:38)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:17)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error loading pixmap: Out of memory
	at arc.graphics.Pixmap$NativePixmap.<init>(Pixmap.java:596)
	at arc.graphics.Pixmap.<init>(Pixmap.java:91)
	... 9 more
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
read the error, you need more memory
close things like web browsers

**Comment by Anuken** [comment]
Duplicate.
