### ISSUE TITLE
Crash-Report, can someone help?

### ISSUE THREAD

**Issue by Zadras** [Anuken/Mindustry#4176]
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 121.4
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

mindustry.net.ValidateException: Player cannot configure a tile.
	at mindustry.input.InputHandler.tileConfig(InputHandler.java:307)
	at mindustry.gen.Call.tileConfig(Call.java:1315)
	at mindustry.gen.Building.configure(Building.java:1456)
	at mindustry.core.Control.lambda$playSector$27(Control.java:354)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:246)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by Anuken** [comment]
Update your game.

**Comment by DeltaNedas** [comment]
`&template=bug_report.md`
