### ISSUE TITLE
extra/new planet crashes when I launch to a generated sector

### ISSUE THREAD

**Issue by gamma-02** [Anuken/Mindustry#4320]
**Platform**: *Mac*

**Build**: *221.1*

**Issue**: *it crashes whenever I try to launch to a modded planet.*

**Steps to reproduce**: *just launch to any map on the new planet that's not Last Stand*

**Link(s) to mod(s) used**: *https://github.com/BlueWolf3682/Exotic-Mod*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Mindustry has crashed. How unfortunate.
Version: release build 122.1
OS: Mac OS X x64
Java Version: 1.8.0_222
Java Architecture: 64
4 Mods: braindustry:1.4.2, exotic-mod:614 alpha, mindustry-production:3.1, rtfm:2.14.6

java.lang.NullPointerException
	at mindustry.world.blocks.environment.Floor.drawBase(Floor.java:176)
	at mindustry.graphics.FloorRenderer.cacheChunkLayer(FloorRenderer.java:212)
	at mindustry.graphics.FloorRenderer.cacheChunk(FloorRenderer.java:183)
	at mindustry.graphics.FloorRenderer.clearTiles(FloorRenderer.java:238)
	at mindustry.graphics.FloorRenderer.lambda$new$0(FloorRenderer.java:30)
	at arc.Events.lambda$fire$2(Events.java:30)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:30)å
	at arc.Events.fire(Events.java:25)
	at mindustry.core.World.endMapLoad(World.java:218)
	at mindustry.core.World.loadGenerator(World.java:239)
	at mindustry.core.World.loadSector(World.java:246)
	at mindustry.core.Control.lambda$playSector$27(Control.java:389)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:246)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> extra/new planet

Not supported.

**Comment by gamma-02** [comment]
ok

**Comment by gamma-02** [comment]
so what has to happen for it to not crash?

**Comment by joshuaptfan** [comment]
> so what has to happen for it to not crash?

Don't play on modded planets since they're not supported (yet).

**Comment by gamma-02** [comment]
but I want to

**Comment by joshuaptfan** [comment]
And I want a million dollars, but...

**Comment by Anuken** [comment]
> it shoud be pretty simple...

Feel free to make the simple changes required and submit a pull request.

**Comment by gamma-02** [comment]
idk how to do it with Mindustry itself but with mods its simple... no ores or floor tiles on new stages.

**Comment by joshuaptfan** [comment]
This is not a live chat. Please do not spam unimportant comments here, it creates notification spam for all involved users.

**Comment by BlueWolf3682** [comment]
(the planet works now but please fix modded blocks causing the generator to die inside just to make my life easier by a lot)
