### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Domaman202** [Anuken/Mindustry#4323]
**Platform**: Windows

**Build**: steam build 122.1

**Issue**: Crash

**Log**:
Mindustry has crashed. How unfortunate.
Version: steam build 122.1
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
17 Mods: aeromindustry:1, braindustry:1.4.2, collos:[#EC5EFF]1.2.1[], gravillaso: 0.9.7r, heavy-armaments:2.3, hori:2.3, opore-mod:67, pixelcraft:0.9.6, powered-by-nature:2.0, revision:6.5, scrapless-slag:2.00, time-control:0.2, titanium-drill-1.1:1.1, vf's-frontiers:1.2, eax能源:1.6.8.73, hypertech:2.82, intensify:[white]2.201

java.lang.ClassCastException: arc.struct.Seq cannot be cast to mindustry.game.Objectives$Objective
	at arc.struct.Seq.find(Seq.java:346)
	at arc.struct.Seq.contains(Seq.java:276)
	at mindustry.core.Control.lambda$new$12(Control.java:139)
	at arc.Events.lambda$fire$2(Events.java:30)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:30)
	at arc.Events.fire(Events.java:25)
	at mindustry.ctype.UnlockableContent.unlock(UnlockableContent.java:125)
	at mindustry.core.Control.checkAutoUnlocks(Control.java:239)
	at mindustry.core.Control.lambda$new$13(Control.java:147)
	at arc.Events.lambda$fire$2(Events.java:30)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:30)
	at arc.Events.fire(Events.java:25)
	at mindustry.game.Universe.runTurn(Universe.java:187)
	at mindustry.game.Universe.update(Universe.java:70)
	at mindustry.core.Logic.update(Logic.java:386)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by BlueWolf3682** [comment]
Have you made sure this crash occurs without mods?

**Comment by Domaman202** [comment]
oops no ...

**Comment by DeltaNedas** [comment]
do not the opore

**Comment by BlueWolf3682** [comment]
they can whatever mods they want to
