### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by LOVECN81** [Anuken/Mindustry#4471]
Version: release build 123.1
OS: Windows 7 x32
Java Version: 1.8.0_201-1-ojdkbuild
Java Architecture: 32
0 Mods

java.lang. Out Of Memory Error: unable to create new native thread

	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at arc.util.async.Threads.daemon(Threads.java:49)
	at mindustry.net.ArcNetProvider.pingHost(ArcNetProvider.java:182)
	at mindustry.net.Net.pingHost(Net.java:290)
	at mindustry.ui.dialogs.JoinDialog.refreshGlobal(JoinDialog.java:365)
	at mindustry.ui.dialogs.JoinDialog.refreshAll(JoinDialog.java:110)
	at mindustry.ui.dialogs.JoinDialog.lambda$new$7(JoinDialog.java:92)
	at arc.scene.ui.Dialog$5.shown(Dialog.java:377)
	at arc.scene.event.VisibilityListener.handle(VisibilityListener.java:11)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Dialog.show(Dialog.java:417)
	at arc.scene.ui.Dialog.show(Dialog.java:457)
	at arc.scene.ui.Dialog.show(Dialog.java:452)
	at mindustry.ui.fragments.MenuFragment.checkPlay(MenuFragment.java:199)
	at mindustry.ui.fragments.MenuFragment.lambda$buildDesktop$22(MenuFragment.java:170)
	at mindustry.ui.fragments.MenuFragment.lambda$buttons$30(MenuFragment.java:240)
	at arc.scene.Element.lambda$clicked$2(Element.java:893)
	at arc.scene.Element$4.clicked(Element.java:902)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:34)
	at arc.scene.Scene.touchUp(Scene.java:360)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:143)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)**Platform**: *Android/iOS/Mac/Windows/Linux*

**Comment by WilloIzCitron** [comment]
please close #4470

**Comment by Anuken** [comment]
Unable to reproduce.

**Comment by DeltaNedas** [comment]
when you disable thread support in nt and recompile

**Comment by LOVECN81** [comment]
can somebody help me?
