### ISSUE TITLE
Launching with custom core in campaign crashes the game.

### ISSUE THREAD

**Issue by souvikpodder** [Anuken/Mindustry#4475]
**Platform**: *Windows*

**Build**:  123.1

**Issue**: When I am launching from any sector to a new sector with custom CORE the game crashes with below error.
What I can understand looking at the code, the code is scanning for the schema with that custom core but didn't find anything so it crashes. (Maybe I am wrong .: P)

java.lang.IllegalStateException: Array is empty.
	at arc.struct.Seq.first(Seq.java:709)
	at mindustry.game.Universe.getLoadout(Universe.java:137)
	at mindustry.ui.dialogs.LaunchLoadoutDialog.show(LaunchLoadoutDialog.java:107)
	at mindustry.ui.dialogs.PlanetDialog.playSelected(PlanetDialog.java:833)
	at arc.scene.Element.lambda$clicked$2(Element.java:893)
	at arc.scene.Element$4.clicked(Element.java:902)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:34)
	at arc.scene.Scene.touchUp(Scene.java:360)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:143)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

PS: I have other mods also. I tried disabling all and enabling one by one and found the Larger-core mods causes the issue.

**Steps to reproduce**: Launching from one sector to another with custom core.

**Link(s) to mod(s) used**:  https://github.com/z0mbiesrock/Larger-Cores 

**Save file**:  
[saves.zip](https://github.com/Anuken/Mindustry/files/5897810/saves.zip)

**(Crash) logs**: 
[crash-report-01_30_2021_16_25_24.txt](https://github.com/Anuken/Mindustry/files/5897812/crash-report-01_30_2021_16_25_24.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by antonilol** [comment]
maybe this issues has to be reported at the issue tracker of the mod z0mbiesrock/Larger-Cores

**Comment by souvikpodder** [comment]
@antonilol The issue is how the current code handles the sector loading.
Whenever it loads a sector it tries to find a schematic with the core name of the sector from which the player is trying to launch. But for custom core, this schematic doesn't exist at all.
So the game crashes.
I don't know what can the mod do to rectify this.

**Comment by TheRealIvyX** [comment]
then its z0mbiesrock's fault for not making built in core schems for the 2 cores in his mods and not an issue with the way sectors are generated
