### ISSUE TITLE
Errors when lanching v124 in China

### ISSUE THREAD

**Issue by driver1748** [Anuken/Mindustry#4621]
**Platform**: *Windows*

**Build**: *release build v124*

**Issue**: *I was using CN commuity servers mod,when I saw v124 updates.However,the game crashed when the loading is nearly compeleted.Then I went back to v123.1 and disabled the mod.Now I can enter the game,but there is a error report every time I enter the game.Maybe Anuke should a button to completly disable loading community servers when starting.By the way,using github in China is OK,but so slow.*

**Steps to reproduce**: *Just launch v124(Crashes when there is Chinalist mod enabled)*

**Link(s) to mod(s) used**: *https://github.com/driver1748/Chinalist*

**(Crash) logs**(WHEN THERE IS THE MOD AND THE GAME CRASHES): *Mindustry has crashed. How unfortunate.
Version: release build 124
OS: Windows 7 x64
Java Version: 1.8.0_271
Java Architecture: 64
7 Mods: chinalist:1.2, cliff:1.0.1, pictologic:1.5.7, rtfm:2.14.0, ui-lib:2.16.4, new-horizon:1.15, thc-industry:0.4.7.200611_classic

rhino.EvaluatorException: Access to Java class "arc.Net" is prohibited. (main.js#2)
	at rhino.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:68)
	at rhino.Context.reportRuntimeError(Context.java:830)
	at rhino.Context.reportRuntimeError(Context.java:876)
	at rhino.Context.reportRuntimeError1(Context.java:844)
	at rhino.JavaMembers.<init>(JavaMembers.java:24)
	at rhino.JavaMembers.lookupClass(JavaMembers.java:771)
	at rhino.NativeJavaObject.initMembers(NativeJavaObject.java:43)
	at rhino.NativeJavaObject.<init>(NativeJavaObject.java:33)
	at rhino.NativeJavaObject.<init>(NativeJavaObject.java:24)
	at rhino.WrapFactory.wrapAsJavaObject(WrapFactory.java:107)
	at rhino.WrapFactory.wrap(WrapFactory.java:66)
	at rhino.JavaMembers.get(JavaMembers.java:84)
	at rhino.NativeJavaClass.get(NativeJavaClass.java:69)
	at rhino.ScriptableObject.getProperty(ScriptableObject.java:2182)
	at rhino.ScriptRuntime.getObjectProp(ScriptRuntime.java:1458)
	at rhino.ScriptRuntime.getObjectProp(ScriptRuntime.java:1452)
	at rhino.gen.main_js_3._c_anonymous_2(main.js:2)
	at rhino.gen.main_js_3.call(main.js)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
	at rhino.gen.main_js_3.call(main.js)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:524)
	at rhino.ContextFactory.call(ContextFactory.java:446)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.jdk18.VMBridge_jdk18.lambda$newInterfaceProxy$0(VMBridge_jdk18.java:100)
	at com.sun.proxy.$Proxy2.get(Unknown Source)
	at arc.Events.lambda$fire$2(Events.java:30)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:30)
	at arc.Events.fire(Events.java:25)
	at mindustry.ClientLauncher.update(ClientLauncher.java:146)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)*

**(Crash) logs**(WHEN THERE IS **NOT** THE MOD AND THE GAME IS SUCCESSFULLY LAUNCHED):*[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / GeForce GTX 960/PCIe/SSE2
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 1.8.0_72
[I] Loaded mod 'pictologic' in 17.785065ms
[I] Loaded mod 'rtfm' in 2.643901ms
[I] Loaded mod 'cliff' in 0.794845ms
[I] Loaded mod 'ui-lib' in 0.863264ms
[I] Loaded mod 'new-horizon' in 15.72447ms
[I] Loaded mod 'THC Industry' in 0.954024ms
[I] Loaded mod 'ChinaList' in 0.758542ms
[I] Time to initialize modded scripts: 891.7289
[I] Total time to load: 6571
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
[E] java.net.UnknownHostException: raw.githubusercontent.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at arc.util.NetJavaImpl.lambda$http$0(NetJavaImpl.java:86)
	at arc.util.async.AsyncExecutor.lambda$submit$2(AsyncExecutor.java:31)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[I] Time to generate menu: 124.77262
*
Crashes:
![image](https://user-images.githubusercontent.com/62016462/107170663-eb47ef80-69fb-11eb-8cda-790b5bfd2d08.png)
Enters:
![image](https://user-images.githubusercontent.com/62016462/107170821-3e21a700-69fc-11eb-9da8-463cd03d3768.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by driver1748** [comment]
![image](https://user-images.githubusercontent.com/62016462/107171053-cd2ebf00-69fc-11eb-979f-2efc0222e32c.png)
opening the blue link with chrome

**Comment by driver1748** [comment]
I asked the mod maker and
![image](https://user-images.githubusercontent.com/62016462/107171811-a96c7880-69fe-11eb-82e1-30bef61d7585.png)
Anuke doesn't allow mods to connect with the Internet now
![image](https://user-images.githubusercontent.com/62016462/107171902-e0db2500-69fe-11eb-9e97-b64f381e9fad.png)
arc.Net is a Internet-connecting repo,banned by him

**Comment by way-zer** [comment]
It is in commit https://github.com/Anuken/Mindustry/commit/9142da2b70ae6a4769e53c16a62ef0ac695c014b

**Comment by driver1748** [comment]
> It is in commit [9142da2](https://github.com/Anuken/Mindustry/commit/9142da2b70ae6a4769e53c16a62ef0ac695c014b)
> And other net packages have been banned before

Bruh,thinking about the safety?

**Comment by driver1748** [comment]
Then just fix the error about fails to load the list

**Comment by driver1748** [comment]
> It is in commit [9142da2](https://github.com/Anuken/Mindustry/commit/9142da2b70ae6a4769e53c16a62ef0ac695c014b)
> And other net packages have been banned before

OK im now trying to _edit it by myself_

**Comment by abomb4** [comment]
v124 开 幕 雷 击
All versions before v124 have this situation too, but the error log is displayed in F8 only; this time a dialog displayed
![image](https://user-images.githubusercontent.com/6198193/107172448-5a274780-6a00-11eb-93e8-7d2b7cc34fcb.png)

**Comment by shugen002** [comment]
how about switch use jsdeliver to deliver global server list ?

**Comment by shugen002** [comment]
looks like there is two issue in one issue.
1、China Player can't connect to raw.githubusercontent.com to get mod list . And the Exception dialog is annoying .
2、Arc.Net has been banned without inform mod maker .

**Comment by Anuken** [comment]
The dialog was caused by mods being queried at application start instead of only when the mod browser is opened. This has been fixed.

arc.Net was never supposed to be available to mods. It not being blacklisted was an oversight.

**Comment by Anuken** [comment]
*after a brief discussion on Discord, I decided to revert the arc.Net blacklist.*

**Comment by driver1748** [comment]
> after a brief discussion on Discord, I decided to revert the arc.Net blacklist.

_Cute cat._
_Lovely._
