### ISSUE TITLE
Too much core on map will cause client fail to join server.

### ISSUE THREAD

**Issue by shugen002** [Anuken/Mindustry#4658]
**Platform**: Windows

**Build**: 124.1

**Issue**: I fail to join server hosting this map and got error.

**Steps to reproduce**: Create a game with beload map and let other people join.

**Link(s) to mod(s) used**: none.

**Save file**: 
[放鞭炮.zip](https://github.com/Anuken/Mindustry/files/5969389/default.zip)

<details>
<summary>
Caused by: java.lang.NegativeArraySizeException: -25575
</summary>

```
[E] java.lang.RuntimeException: Failed to read remote method 'stateSnapshot'!
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:460)
	at mindustry.core.NetClient.lambda$new$4(NetClient.java:127)
	at mindustry.net.Net.handleClientReceived(Net.java:258)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:62)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.lang.NegativeArraySizeException: -25575
	at net.jpountz.lz4.LZ4FastDecompressor.decompress(LZ4FastDecompressor.java:99)
	at net.jpountz.lz4.LZ4FastDecompressor.decompress(LZ4FastDecompressor.java:113)
	at mindustry.net.Net.decompressSnapshot(Net.java:179)
	at mindustry.core.NetClient.stateSnapshot(NetClient.java:480)
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:458)
	... 7 more

```
</details>

PS: I know this map is for fun , but this still is a bug.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
looks like the max amount of cores is currently 127, shared between all teams 🤔 (I'm guessing anuke will either change it from byte to short, or tell you to not have so many cores)
