### ISSUE TITLE
game crashes when placing power nodes

### ISSUE THREAD

**Issue by grannybullet** [Anuken/Mindustry#4693]
Version: bleeding-edge build 20738 - 20740
OS: Windows 10 x64
Java Version: 1.8.0_281
Java Architecture: 64
0 Mods

the game crashes when i try to place a power node that connects to some combustion generators

this started happening while paying campaign, i set down some combustion generators and tried to connect them by placing small power node, and i have tested it and it is just the placing of power nodes that causes the crash

**Save file**: *The (zipped) save file you were playing on when the bug happened.

[saves.zip](https://github.com/Anuken/Mindustry/files/5985935/saves.zip)

java.lang.IllegalStateException: Array is empty.
	at arc.struct.Seq.peek(Seq.java:703)
	at mindustry.input.Placement.calculateNodes(Placement.java:103)
	at mindustry.world.blocks.power.PowerNode.changePlacementPath(PowerNode.java:159)
	at mindustry.input.InputHandler.iterateLine(InputHandler.java:1181)
	at mindustry.input.InputHandler.updateLine(InputHandler.java:856)
	at mindustry.input.InputHandler.updateLine(InputHandler.java:874)
	at mindustry.input.DesktopInput.pollInput(DesktopInput.java:485)
	at mindustry.input.DesktopInput.update(DesktopInput.java:263)
	at mindustry.core.Control.update(Control.java:518)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
issue seems to exist since 2-3 days, though i haven't spotted any commit that could have been to blame here or in arc 🤔

**Comment by Anuken** [comment]
Fixed.
