### ISSUE TITLE
Server doesn't detect all client mods

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#4720]
**Platform**: Windows 10

**Build**: build 125

**Issue**: See all crash logs

**Steps to reproduce**: Unknown. just play my server and get random errors.
I tried logging to plugin source code that affects the actual server, but there was a random error, not a specific code.

**Link(s) to mod(s) used**: No mods using client

**Save file**: Not need

**(Crash) logs**: Here
```
java.lang.NullPointerException
	at mindustry.gen.UnitEntity.apply(UnitEntity.java:823)
	at mindustry.gen.UnitEntity.update(UnitEntity.java:1361)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:68)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:58)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:411)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```
```
java.lang.NullPointerException
	at mindustry.gen.PayloadUnit.update(PayloadUnit.java:1893)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:68)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:58)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:411)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```
```
java.lang.NullPointerException: Cannot read field "id" because "unit.type" is null
	at mindustry.game.Teams.updateTeamStats(Teams.java:192)
	at mindustry.core.Logic.update(Logic.java:375)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```
```
java.lang.NullPointerException
	at mindustry.game.Teams.updateTeamStats(Teams.java:192)
	at mindustry.core.Logic.update(Logic.java:375)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```
```
java.lang.NullPointerException
	at mindustry.world.blocks.payloads.UnitPayload.draw(UnitPayload.java:85)
	at mindustry.type.UnitType.drawPayload(UnitType.java:503)
	at mindustry.type.UnitType.draw(UnitType.java:464)
	at mindustry.gen.PayloadUnit.draw(PayloadUnit.java:733)
	at mindustry.entities.EntityGroup.lambda$draw$0(EntityGroup.java:84)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:68)
	at mindustry.entities.EntityGroup.draw(EntityGroup.java:81)
	at mindustry.core.Renderer.draw(Renderer.java:252)
	at mindustry.core.Renderer.update(Renderer.java:100)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```
```
java.lang.NullPointerException
	at mindustry.gen.UnitEntityLegacyBeta.update(UnitEntityLegacyBeta.java:1311)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:68)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:58)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:411)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

PhysicsProcess errors occur the most.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
~~tell sharlotte to stop making ohno spiders~~

**Comment by Kieaer** [comment]
It's estimated that an error occurs when a particular user uses some mods.
Most errors are logic, perhaps there's a mod that controls the time of the server.
Although there're already many users who are equipped with many mods and play the server, the server allowed access even though ``strict on``.

**Comment by sk7725** [comment]
the type of your units is null, I suspect that sharlotte's ohno spiders (it abuses UnitType to make amalgamates) did something wrong and left a mark on the server save file.
No mods would or should make a serverside unit type null.

**Comment by Anuken** [comment]
Many mods have `hidden: true`, which means they don't count when servers are joined. This is intentional.

> Steps to reproduce: Unknown. just play my server and get random errors.

That doesn't help me find a solution. Something on your server is creating invalid units. I don't see any code that would allow clients to do this, and if it were really caused by clientside mods I would expect to see it on other servers as well.

**Comment by DeltaNedas** [comment]
if a mod breaks server compat it shouldnt be hidden and by extension you shouldnt use it

**Comment by Kieaer** [comment]
![image](https://user-images.githubusercontent.com/44261958/108626055-9b543880-7491-11eb-8cd9-c37da9dc33ec.png)
Presumed to use mod but not detected in server

**Comment by Anuken** [comment]
> Many mods have hidden: true, which means they don't count when servers are joined. This is intentional.
