### ISSUE TITLE
A crash has occured

### ISSUE THREAD

**Issue by ParraRespuestas** [Anuken/Mindustry#4739]
**Platform**: Windows

**Build**: 125.1

**Issue**: When you start Mindustry, you see the loading screen and it closes instantly and sends an error message stating the following: "A crash has occurred. It has been saved to: (directory)
IO: Error loading pixel map: insufficient memory. "

> **(Crash) logs**:
[crash-report-02_20_2021_00_41_29.txt](https://github.com/Anuken/Mindustry/files/6014104/crash-report-02_20_2021_00_41_29.txt)

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 125.1
OS: Windows 10 x32
Java Version: 1.8.0_201-1-ojdkbuild
Java Architecture: 32
0 Mods

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:670)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:138)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:105)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	... 6 more
Caused by: arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load file: sprites/sprites.png
	at arc.util.async.AsyncResult.get(AsyncResult.java:34)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:103)
	... 9 more
Caused by: arc.util.ArcRuntimeException: Couldn't load file: sprites/sprites.png
	at arc.graphics.Pixmap.<init>(Pixmap.java:93)
	at arc.graphics.TextureData$TextureDataFactory.loadFromFile(TextureData.java:96)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:39)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:18)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error loading pixmap: Out of memory
	at arc.graphics.Pixmap$NativePixmap.<init>(Pixmap.java:596)
	at arc.graphics.Pixmap.<init>(Pixmap.java:91)
	... 9 more

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
Perhaps you are low on memory. How much RAM does your computer have? Have you tried closing some programs and starting Mindustry again?

**Comment by DeltaNedas** [comment]
the error says out of memory, you need more memory

**Comment by Anuken** [comment]
Duplicate.
