### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Skilifer** [Anuken/Mindustry#4817]
Version: release build 122
OS: Windows 10 x32
Java Version: 1.8.0_201-1-ojdkbuild
Java Architecture: 32
0 Mods

java.lang.IllegalStateException: Frame buffer couldn't be constructed: missing attachment
	at arc.graphics.gl.GLFrameBuffer.build(GLFrameBuffer.java:288)
	at arc.graphics.gl.FrameBuffer.create(FrameBuffer.java:83)
	at arc.graphics.gl.FrameBuffer.<init>(FrameBuffer.java:71)
	at arc.graphics.gl.FrameBuffer.<init>(FrameBuffer.java:43)
	at arc.graphics.gl.FrameBuffer.<init>(FrameBuffer.java:38)
	at mindustry.graphics.BlockRenderer.<init>(BlockRenderer.java:37)
	at mindustry.core.Renderer.<init>(Renderer.java:23)
	at mindustry.ClientLauncher.setup(ClientLauncher.java:98)
	at mindustry.ClientLauncher.init(ClientLauncher.java:173)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:117)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by Anuken** [comment]
Cannot reproduce, does not follow template.
