### ISSUE TITLE
Crash while in chat

### ISSUE THREAD

**Issue by Smeagstheman** [Anuken/Mindustry#4869]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126`

**Issue**: Cannot chat in multiplayer game. I can enter chat but after typing, when I press the Enter key the game crashes

**Steps to reproduce**: Only happens when trying to chat with other players. I can type the message out, but unable to send it

**Link(s) to mod(s) used**: `none`

**Save file**: *
[sector-serpulo-21.zip](https://github.com/Anuken/Mindustry/files/6094565/sector-serpulo-21.zip)

not sure if my save file is in. it is an absolute nightmare trying to zip the folder since my computer wants to change the file type when I try to upload

**Crash report**: 
java.lang.NullPointerException
	at mindustry.core.NetClient.sendChatMessage(NetClient.java:193)
	at mindustry.gen.Call.sendChatMessage(Call.java:807)
	at mindustry.ui.fragments.ChatFragment.sendMessage(ChatFragment.java:184)
	at mindustry.ui.fragments.ChatFragment.lambda$toggle$3(ChatFragment.java:212)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by bvcbvc** [comment]
you forgot the checkmarks bro

**Comment by Volas171** [comment]
**this might be crashing because of this**
![C6AEC78A-FB37-43C2-AE68-E51AD826C8DB](https://user-images.githubusercontent.com/60143910/110192926-02151280-7dff-11eb-95fa-a039c85e3ddc.png)
