### ISSUE TITLE
Null unit casting error.

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Anuken/Mindustry#4929]
**Platform**: *Linux (Server)*

**Build**: *126*

**Issue**: *An error with casting variables, due to unit being null.*

**Steps to reproduce**: *This happens rather rarely, and assumably is assosciated with some form of server lag.*

**Link(s) to mod(s) used**: *None.*

**Error Log**: 
```
java.lang.RuntimeException: Failed to read remote method 'requestBuildPayload'!
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:126)
        at mindustry.core.NetServer.lambda$new$7(NetServer.java:261)
        at mindustry.net.Net.handleServerReceived(Net.java:277)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:117)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
Caused by: java.lang.ClassCastException: class mindustry.gen.NullUnit cannot be cast to class mindustry.gen.Payloadc (mindustry.gen.NullUnit and 
mindustry.gen.Payloadc are in unnamed module of loader 'app')
        at mindustry.input.InputHandler.requestBuildPayload(InputHandler.java:208)
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:124)
        ... 6 more
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This isn't a crash, and isn't of any consequence. Ignore it.
