### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Skilifer** [Anuken/Mindustry#4949]
Mindustry has crashed. How unfortunate.
Version: release build 126.1
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
1 Mods: example-mod:3.0

java.lang.NullPointerException
	at mindustry.world.blocks.distribution.StackConveyor$StackConveyorBuild.poofIn(StackConveyor.java:269)
	at mindustry.world.blocks.distribution.StackConveyor$StackConveyorBuild.handleItem(StackConveyor.java:286)
	at mindustry.world.blocks.experimental.BlockLoader$BlockLoaderBuild.updateTile(BlockLoader.java:116)
	at mindustry.gen.Building.update(Building.java:1185)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:68)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:58)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:411)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:164)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by joshuaptfan** [comment]
You need to upload a save file. The template you deleted told you this.

**Comment by Skilifer** [comment]
Its multiplayer

**Comment by Anuken** [comment]
No save, no reproduction steps.

> mindustry.world.blocks.experimental.BlockLoader

The block loader is an experimental block and is not supported.
