### ISSUE TITLE
Cannot host multiplayer

### ISSUE THREAD

**Issue by Kompaktive** [Anuken/Mindustry#4959]
**Platform**: *Windows*

**Build**: *steam build 126.1*

**Issue**: *I can't host multiplayer game, I can't see any additional game settings like "Player Limit" or "Public Game Visibility". I can't join game from friend invitation, but I can join public server flawlessly.*

**Steps to reproduce**:
*1. Create a new campaign / custom game. Then press **Esc** and click **Host Multiplayer Game**. After that, a pop up text "Opening Server..." appears. Then what happens next is the button doesn't change to "Invite Friends", instead it goes to unclickable state button (Grey color Host Multiplayer Game button), but at the same time the game is no longer paused when I pressed Esc.*

*2. When I pressed join from friend invitation on Steam, the game does nothing. It just stays in main menu.*

**Link(s) to mod(s) used**: *no mod*

**Save file**: [save1.zip](https://github.com/Anuken/Mindustry/files/6167915/save1.zip)

**(Crash) logs**: *The game won't let me export crash log since there is no crash. However, I got error from last_log.txt.*
```
[I] [GL] Version: OpenGL 4.5.0 / Intel / Intel(R) HD Graphics 630
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 1.8.0_72
[W] Shader shaders/mesh.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/default.vert | shaders/blockbuild.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/shield.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/buildbeam.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/default.vert | shaders/unitbuild.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/default.vert | shaders/darkness.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/light.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/water.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/space.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/planet.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/planetgrid.vert | shaders/planetgrid.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/atmosphere.vert | shaders/atmosphere.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/unlit.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/screenspace.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[E] java.lang.RuntimeException: java.util.zip.ZipException: incorrect header check
	at mindustry.io.SaveIO.getMeta(SaveIO.java:95)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:239)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: incorrect header check
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at mindustry.io.SaveIO.readHeader(SaveIO.java:176)
	at mindustry.io.SaveIO.getMeta(SaveIO.java:89)
	... 11 more

[I] Total time to load: 6418
[W] Shader bloomshaders/screenspace.vert | bloomshaders/bloom.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader bloomshaders/screenspace.vert | bloomshaders/threshold.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader bloomshaders/blurspace.vert | bloomshaders/gaussian.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/cubemap.vert | shaders/cubemap.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_bloom.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_threshold.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader bloomshaders/blurspace.vert | bloomshaders/alpha_gaussian.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
[I] Time to generate menu: 114.311295
[I] Fetched 25 community servers.
[I] Saved on exit.
[save1.zip](https://github.com/Anuken/Mindustry/files/6167890/save1.zip)

```
---
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You're either not running the Steam version at all, or you're in some sort of state where Steam can't initialize, such as offline mode. Either way, I can't reproduce or fix this.

**Comment by Kompaktive** [comment]
I'm running on steam, I legitimately bought Mindustry on Steam to support you and to play without portforward. My friend can see me playing Mindustry. Is there something to do with Java? I don't have Java installed.

**Comment by Anuken** [comment]
It's possible there may be more information in a `steam-error-log-xxx` file in the Steam local files, but either way I doubt I can help you. The Steam features work on every single computer I've tested, and I've only ever heard of this happening for 1-2 other people.

**Comment by Kompaktive** [comment]
Where can I find that file in specific folder? I actually suspect this is because my laptop is still brand new, my friend recently buy Mindustry just to play with me and she's not having any trouble in multiplayer. I don't have anything installed other than steam and steam games. I don't have Java Runtime, I don't have VC_Redist. There must be something missing on my end resulting your game not acknowledging my Steam. Please note that I **can** join public server, but I can't host multiplayer or join my friend.

**Comment by Anuken** [comment]
> Where can I find that file in specific folder? 

It should be in the same folder as the game executable.

>  I don't have anything installed other than steam and steam games. I don't have Java Runtime, I don't have VC_Redist.

You should not need these. Mindustry comes with Java.

> Please note that I can join public server, but I can't host multiplayer or join my friend.

This isn't related to Steam, it uses a different system.

**Comment by Kompaktive** [comment]
Guess I'm out of luck. I will try to update this issue in case I fixed it. Thanks for your time.

**Comment by Kompaktive** [comment]
Hi Anuken. Just wanted to let you know that I managed to fix the problem by installing Developer Mode Mod. Everything is working as intended now.

**Comment by Anuken** [comment]
...what? That mod shouldn't affect how Steam is initialized. Did you run a specific command?

**Comment by Kompaktive** [comment]
I absolutely have no idea, but that's what happened. I didn't run any command. I just installed Developer Mode Mod, restarted Mindustry, and then suddenly I can see the workshop button appearing in main menu, and I can host multiplayer and invite my friends, set player limit and public visibility.
