### ISSUE TITLE
Client NullPointerException when player on server host build something

### ISSUE THREAD

**Issue by DraconYale** [Anuken/Mindustry#500]
When the player who host the server build something, the client crash.
I'll post the error below:
```
--- CONTENT INFO ---
[item]: loaded 16
[block]: loaded 276
[mech]: loaded 8
[bullet]: loaded 50
[liquid]: loaded 4
[status]: loaded 11
[unit]: loaded 14
[weather]: loaded 0
[effect]: loaded 0
[zone]: loaded 10
[loadout]: loaded 4
Total content loaded: 393
-------------------
Time to load [total]: 2151.9204
Connecting to server: ****
Recieved world data: 12384 bytes.
Time to cache: 175.44531
java.lang.NullPointerException
        at io.anuke.mindustry.world.Build.validPlace(Build.java:72)
        at io.anuke.mindustry.entities.traits.BuilderTrait.updateBuilding(BuilderTrait.java:89)
        at io.anuke.mindustry.entities.type.Player.update(Player.java:554)
        at io.anuke.mindustry.entities.Entities.update(Entities.java:56)
        at io.anuke.mindustry.core.Logic.update(Logic.java:173)
        at io.anuke.arc.ApplicationCore.update(ApplicationCore.java:36)
        at io.anuke.mindustry.Mindustry.update(Mindustry.java:51)
        at io.anuke.arc.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:371)
        at io.anuke.arc.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:224)
        at io.anuke.arc.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:54)
        at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:24)
```

**Comment by Anuken** [comment]
What are the client and server build versions?
