### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Parkjeyhyun** [Anuken/Mindustry#5058]
Version: steam build 126.3
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.game.Teams.updateTeamStats(Teams.java:187)
	at mindustry.core.Logic.update(Logic.java:375)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:164)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by BlueWolf3682** [comment]
Template.

**Comment by Parkjeyhyun** [comment]
Can you delete this issue?
@Anuken
