### ISSUE TITLE
Cannot export data: crash (no activity found)

### ISSUE THREAD

**Issue by Martinocom** [Anuken/Mindustry#5117]
**Platform**: `Android 29`

**Build**: `release build 126.2`

**Issue**: I cannot export my data from game. It crashes when trying to press "export". Log says that he can't find the right Activity to launch. I have two applications to manage files (FX and a generic File Manager). Yes, storage permission is granted.

**Steps to reproduce**: Just go into settings, game data, export and it will crash.

**Link(s) to mod(s) used**: `none`

**Save file**: Cannot save, since I cannot export. This is the bug! Sorry :(

**Crash report**: 

```
time: 1618649712585
msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/zip }
stacktrace: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/zip }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at android.app.Activity.startActivityForResult(Activity.java:5168)
	at mindustry.android.AndroidLauncher$1.lambda$showFileChooser$0$AndroidLauncher$1(AndroidLauncher.java:91)
	at mindustry.android.-$$Lambda$AndroidLauncher$1$Z2g4jQDWo4imsdBXrRSd441Vizg.get(Unknown Source:4)
	at arc.backend.android.AndroidApplication.addResultListener(AndroidApplication.java:384)
	at mindustry.android.AndroidLauncher$1.showFileChooser(AndroidLauncher.java:91)
	at mindustry.android.AndroidLauncher$1.showFileChooser(AndroidLauncher.java:80)
	at mindustry.core.Platform$-CC.$default$showFileChooser(Platform.java:132)
	at mindustry.ClientLauncher.showFileChooser(Unknown Source:0)
	at mindustry.ui.dialogs.SettingsMenuDialog.lambda$new$12$SettingsMenuDialog(SettingsMenuDialog.java:170)
	at mindustry.ui.dialogs.-$$Lambda$SettingsMenuDialog$3xucDiawQayN4OTlQVyIvxaHzbg.run(Unknown Source:2)
	at arc.scene.Element.lambda$clicked$2(Element.java:893)
	at arc.scene.-$$Lambda$Element$Z5rFlDuLK9b0NIGwxILHnJVs0B8.get(Unknown Source:4)
	at arc.scene.Element$4.clicked(Element.java:902)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:360)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.backend.android.AndroidInput.processEvents(AndroidInput.java:287)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:410)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** _Ps: there are no updates on the play store. I checked and I have the latest version._
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Something about your Android device is uniquely messed up, as it doesn't seem to be able to create zip files through a file browser. I've never heard of anyone else having this problem, it doesn't occur on any devices/emulators I have and there's no good way for me to fix it.

**Comment by Martinocom** [comment]
I can confirm that no action that involves a file explorer will work. GMail and other apps recognises perfectly my file openers tho.

Anyway, is there so any way to export my data and import it without the use of "Export" function? Like titanium backup, will preserve the data?

**Comment by Anuken** [comment]
Browse to the data directory yourself, look in `Android/data/data/io.anuke.mindustry`.
