### ISSUE TITLE
IndexOutOfBounds crash

### ISSUE THREAD

**Issue by miiichael** [Anuken/Mindustry#524]
Hello, new player here.

```
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: index can't be >= size: 15 >= 15
	at io.anuke.mindustry.core.Control.update(Control.java:307)
	at io.anuke.ucore.modules.ModuleCore.render(ModuleCore.java:58)
	at io.anuke.mindustry.Mindustry.render(Mindustry.java:38)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:27)
Caused by: java.lang.IndexOutOfBoundsException: index can't be >= size: 15 >= 15
	at com.badlogic.gdx.utils.IntArray.get(IntArray.java:131)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALAudio.obtainSource(OpenALAudio.java:170)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALSound.play(OpenALSound.java:58)
	at io.anuke.ucore.core.Sounds.play(Sounds.java:51)
	at io.anuke.ucore.core.Sounds.playDistance(Sounds.java:39)
	at io.anuke.ucore.core.Effects.sound(Effects.java:72)
	at io.anuke.ucore.core.Effects.sound(Effects.java:67)
	at io.anuke.mindustry.world.blocks.types.defense.Turret.update(Turret.java:154)
	at io.anuke.mindustry.entities.TileEntity.update(TileEntity.java:117)
	at io.anuke.ucore.entities.Entities.update(Entities.java:184)
	at io.anuke.mindustry.core.Logic.update(Logic.java:152)
	at io.anuke.mindustry.core.ThreadHandler.runLogic(ThreadHandler.java:108)
	at java.lang.Thread.run(Thread.java:748)
```

3.5r40 on Debian. There was quite a lot of pew-pew-pew happening at the time.

**Comment by Anuken** [comment]
This crash is from build 40 and doesn't apply to the newer builds. Most of the classes mentioned don't exist anymore.
