### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by CleroStyle** [Anuken/Mindustry#5342]
Version: release build 126.2
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.gen.UnitEntityLegacyAlpha.destroy(UnitEntityLegacyAlpha.java:668)
	at mindustry.gen.UnitEntityLegacyAlpha.update(UnitEntityLegacyAlpha.java:1626)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:59)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:411)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:164)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by MrDuck557** [comment]
where save file
where template

**Comment by Anuken** [comment]
Unusable.
