### ISSUE TITLE
Play button crashes the game on Sandbox saves

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#54]
Whenever I load a sandbox save and try to start a new wave it crashes the game. 
```Block classes: 6
Controllers: added manager for application, 1 managers active
Total blocks loaded: 95
java.lang.NullPointerException
        at io.anuke.mindustry.core.Control.runWave(Control.java:338)
        at io.anuke.mindustry.ui.fragments.HudFragment.lambda$playButton$0(HudFragment.java:199)
        at io.anuke.ucore.scene.Element$2.clicked(Element.java:108)
        at io.anuke.ucore.scene.event.ClickListener.touchUp(ClickListener.java:94)
        at io.anuke.ucore.scene.event.InputListener.handle(InputListener.java:60)
        at io.anuke.ucore.scene.Scene.touchUp(Scene.java:372)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
        at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:178)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:383)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:99)
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 26: crash-report-Jan 3, 2018 8:57:58 AM.txt
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:112)
```

**Comment by Anuken** [comment]
See if 41a813ece3c0c3d54cb83763816f49b6939c1a95 fixes it.

**Comment by Anuken** [comment]
Confirmed fixed. Was caused by a discord RPC call with an invalid map.
