### ISSUE TITLE
Crash when trying to copy incompletely deconstructed boulder with F button

### ISSUE THREAD

**Issue by bugreporterboris445** [Anuken/Mindustry#5485]
**Platform**: *Windows*

**Build**: *126.2*

**Issue**: *Game will crash every time, when you try to copy with "F" button icompletely deconstructed boulder.
I've not tested that on alpha versions, only last release build 126.2*

**Steps to reproduce**: *I command unit to destroy boulder with right click, I cancel destroing with left click, then i press "F" button and select the incompletely undestroyed boulder to copy, game crash immediately
I've not tested that on alpha versions, only last release build 126.2*

**Link(s) to mod(s) used**: *no mods, clean version.*

**Save file**: *ok, Ive get it, dont hurt me. Last save file where i've got crush attached, it's campaign.  But I've tred it several times -- same way crush on any map.
[saves.zip](https://github.com/Anuken/Mindustry/files/6720463/saves.zip)
.*

**(Crash) logs**: 
Version: release build 126.2
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.game.Schematics.create(Schematics.java:354)
	at mindustry.input.DesktopInput.pollInput(DesktopInput.java:433)
	at mindustry.input.DesktopInput.update(DesktopInput.java:274)
	at mindustry.core.Control.update(Control.java:525)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:164)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate, already fixed.
