### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by shugen002** [Anuken/Mindustry#5521]
**Platform**: Windows  ,server

**Build**: 126.2 server

**Issue**: Crash Randomly

**Steps to reproduce**: Open a server with any default map (may need slow io server)

**Link(s) to mod(s) used**:  [MDTSteamLobbyPlugin](https://github.com/shugen002/MDTSteamLobbyPlugin)(latest action artifact version) 

I don't think this crash related to my plugin.

**Save file**: 

Seems more than one default map:  Ancient_Caldera / Shattered / Tendrils

**(Crash) logs**: 
```
[07-01-2021 18:37:12] [I] Selected next map to be Ancient Caldera.
[07-01-2021 18:37:25] [I] call updateLobby 1860000063fb42e true
[07-01-2021 18:37:25] [I] call updateLobby 1
[07-01-2021 18:37:25] [E] java.lang.NullPointerException: Cannot assign field "cooldown" because "entry" is null
        at mindustry.core.Logic.updateWeather(Logic.java:267)
        at mindustry.core.Logic.update(Logic.java:397)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:89)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by shugen002** [comment]
In case someone ask me why I use a slow server , my friend has buy this server but failed to ask for refund , then i take it as my stable test server.

**Comment by Anuken** [comment]
I can't reproduce this, and the log doesn't make any sense in a single-threaded context. You are likely modifying the rules or loading a map from another thread.
