### ISSUE TITLE
Executable from Itch fails

### ISSUE THREAD

**Issue by BlueManedHawk** [Anuken/Mindustry#5528]
**Platform**: *Linux*

**Build**: *127.2*

**Issue**: *Running the executable from Itch failed and outputted the message in this report's "(Crash) logs" section.*

**Steps to reproduce**: *I downloaded the files for Linux from Itch.  I unzipped them all into the same directory.  I attempted to run it.*

**Link(s) to mod(s) used**: *No mods used.*

**Save file**: *This didn't occur in-game.*

**(Crash) logs**: *
```
[91m[1m[E][0m arc.util.ArcRuntimeException: File not found: version.properties (internal)
	at arc.files.Fi.read(Fi.java:199)
	at arc.files.Fi.reader(Fi.java:232)
	at arc.files.Fi.reader(Fi.java:224)
	at mindustry.core.Version.init(Version.java:30)
	at mindustry.desktop.DesktopLauncher.<init>(DesktopLauncher.java:55)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)

java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Unknown Source)
	at java.base/java.io.InputStreamReader.<init>(Unknown Source)
	at mindustry.net.CrashSender.send(CrashSender.java:72)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:228)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:50)
[91m[1m[E][0m Failed to parse version.
[91m[1m[E][0m Failed to save local crash report.: java.lang.ExceptionInInitializerError
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:358)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$9(DesktopLauncher.java:231)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$10(DesktopLauncher.java:231)
	at mindustry.net.CrashSender.send(CrashSender.java:94)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:228)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:50)
Caused by: arc.util.ArcRuntimeException: Couldn't load shared library 'libsdl-arc64.so' for target: Linux, 64-bit
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
	at arc.backend.sdl.jni.SDL.<clinit>(SDL.java:118)
	... 6 more
Caused by: arc.util.ArcRuntimeException: Unable to read file for extraction: libsdl-arc64.so
	at arc.util.SharedLibraryLoader.readFile(SharedLibraryLoader.java:93)
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:253)
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
	... 7 more
```
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You either have a corrupted version or did not unzip the application correctly. Cannot reproduce.

**Comment by BlueManedHawk** [comment]
I unzipped the application with `unzip`.  Is that not the correct way to do it?

**Comment by Anuken** [comment]
It works fine when unzipped for me; your version is missing assets, for whatever reason.

**Comment by BlueManedHawk** [comment]
Huh.  Is there any way to obtain these missing assets?  Why would this only be occurring for me?

**Comment by Anuken** [comment]
Those assets are packaged in the zip, so there's no need to obtain them from anywhere else. All releases are zipped in exactly the same way for each platform, and considering you're the only one who is having issues, it's likely something wrong with your system or the way you're unzipping it.

**Comment by BlueManedHawk** [comment]
Huh.  I am very confused.
