### ISSUE TITLE
Kotlin plugins are incompatible with latest version.

### ISSUE THREAD

**Issue by jakubDoka** [Anuken/Mindustry#5666]
**Platform**: Windows

**Build**: 129.1

**Issue**: Kotlin seems to not be compatible with latest version of mindustry. Server is unable to load plugin, responding with:
```
[07-29-2021 13:10:25] [E] Failed to load mod file config/mods/the-worst-mindustry-plugin.jar. Skipping.
[07-29-2021 13:10:25] [E] java.lang.ClassCastException: class the_worst_one.Main cannot be cast to class mindustry.mod.Mod (the_worst_one.Main is in unnamed module of loader mindustry.co
re.Platform$1 @753ddbd8; mindustry.mod.Mod is in unnamed module of loader 'app')
        at mindustry.mod.Mods.loadMod(Mods.java:789)
        at mindustry.mod.Mods.loadMod(Mods.java:702)
        at mindustry.mod.Mods.load(Mods.java:356)
        at mindustry.Vars.init(Vars.java:305)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:47)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:65)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)
```
Plugin was working on v6.

**What I tried:**
- updating kotlin
- updating java jdk
- inspecting plugin loader source code and git diff (nothing sus found)
- updating gradlew

**Steps to reproduce**: Clone the repository and build it. Plug it into server and launch it. Mentioned error should appear.

**Link(s) to mod(s) used**: https://github.com/jakubDoka/the-worst-midustry-plugin

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You have the Mindustry classes in your plugin JAR file. This isn't allowed - since the class loader is child-first, your jar ends up loading the duplicate classes, which are not compatible with the ones that are already loaded.

![image](https://user-images.githubusercontent.com/10100000/127497022-b86e5888-2470-4ffe-a5b0-2201debe3785.png)

**Comment by Anuken** [comment]
This is because [you're using](https://github.com/jakubDoka/the-worst-midustry-plugin/blob/master/build.gradle.kts#L50) `compileClasspath` for the jar task, not `runtimeClasspath`. `compileClasspath` is for all dependencies needed *during compilation*; these shouldn't be in the JAR.

**Comment by jakubDoka** [comment]
**Than you so very much**, I did not notice it. :)
