### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by HolyHades** [Anuken/Mindustry#5697]
**Platform**: *Linux (Ubuntu)

**Build**: 129

**Issue**: I tried to start the game, but it crashes before it starts. I have Java installed, everything else works fine with Java.

**Steps to reproduce**: Start the game on Ubuntu (command used: java -jar Mindustry.jar)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: [E] java.lang.ExceptionInInitializerError
	at arc.backend.sdl.SdlApplication.lambda$init$0(SdlApplication.java:74)
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:186)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:74)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:31)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: arc.util.ArcRuntimeException: Couldn't load shared library 'libsdl-arc64.so' for target: Linux, 64-bit
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
	at arc.backend.sdl.jni.SDL.<clinit>(SDL.java:118)
	... 5 more
Caused by: arc.util.ArcRuntimeException: java.lang.UnsatisfiedLinkError: /tmp/arc/6aa18953/libsdl-arc64.so: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:288)
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
	... 6 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/arc/6aa18953/libsdl-arc64.so: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:294)
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:260)
	... 7 more

[E] Failed to save local crash report.: java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:358)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$9(DesktopLauncher.java:231)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$10(DesktopLauncher.java:231)
	at mindustry.net.CrashSender.send(CrashSender.java:92)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:228)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:50)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Nevermind, was forced to revert the change. I don't know of a way to fix this on my end right now, so the best solution is for you to install `sdl2` (`libsdl2-2.0-0` on Ubuntu).

**Comment by HolyHades** [comment]
I tried that, but unfortunately it still throws the same error.

**Comment by HolyHades** [comment]
With the newest build it works now, thanks :)
