### ISSUE TITLE
Compatibility issue with StatusEffect v6 -> v7

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#5706]
**Platform**: *Windows*

**Build**: *129.1*

**Issue**: *StatusEffects with transitions & affinities crash in v7 (when made with v6 code), probably due to changed codes.*

**Steps to reproduce**: *`sk7725/BetaMindy`'s `icy` is one example. Apply it and then apply either its opposites or affinities to make it crash in v7. This does not crash in v6.*

**Link(s) to mod(s) used**: *sk7725/BetaMindy, MeepofFaith/testing-utilities (for applying them)*

**Save file**: *crash*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
```
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 129.1
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
4 Mods: betamindy:1.0
[#b59e72]Demo of Chaos Itself[], new-horizon:1.9.1 Beta, test-utils:0.14, testers:0.25

java.lang.AbstractMethodError: Receiver class betamindy.content.MindyStatusEffects$8$$Lambda$1618/0x00000001005a4440 does not define or inherit an implementation of the resolved method 'abstract void handle(mindustry.gen.Unit, mindustry.entities.units.StatusEntry, float)' of interface mindustry.type.StatusEffect$TransitionHandler.
	at mindustry.type.StatusEffect.applyTransition(StatusEffect.java:176)
	at mindustry.gen.UnitEntity.apply(UnitEntity.java:944)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at rhino.MemberBox.invoke(MemberBox.java:104)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
	at rhino.optimizer.OptRuntime.call2(OptRuntime.java:32)
	at rhino.gen.statusMenu_14._c_applyLocal_1(statusMenu:13)
	at rhino.gen.statusMenu_14.call(statusMenu)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.statusMenu_14._c_apply_3(statusMenu:35)
	at rhino.gen.statusMenu_14.call(statusMenu)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.statusMenu_14.call(statusMenu)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy2/jdk.proxy2.$Proxy2.run(Unknown Source)
	at arc.scene.Element.lambda$clicked$2(Element.java:893)
	at arc.scene.Element$4.clicked(Element.java:902)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The effect transition API changed; v7 users will have to deal with effects crashing until the mod is correctly updated to v7.

**Comment by sk7725** [comment]
> The effect transition API changed; v7 users will have to deal with effects crashing until the mod is correctly updated to v7.

but would there be a way to keep the compatibility? After all, the aim for v7 is to keep mod compatibility when possible

**Comment by Anuken** [comment]
No.

**Comment by Anuken** [comment]
Checking for v7 when registering status effect transition lambdas and bailing out is a potential option, but that's only something that can be implemented in the mod itself.
