### ISSUE TITLE
The game crashes when I launch from one place to another

### ISSUE THREAD

**Issue by LTHPKBTE** [Anuken/Mindustry#5738]
**Platform**: Windows

**Build**:Pre-Alpha Build 129.2

**Issue**: The game crashes when I launch from one place to another

**Steps to reproduce**: 
![图片](https://user-images.githubusercontent.com/53574505/128973427-71db2680-a9ab-409c-b170-b900811ab792.png)

**Save file**: 
[saves.zip](https://github.com/Anuken/Mindustry/files/6966028/saves.zip)

<details>
        <summary>(Crash) logs</summary>
Version: pre-alpha build 129.2
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
0 Mods

java.lang.IllegalStateException: Frame buffer couldn't be constructed: incomplete attachment
	at arc.graphics.gl.GLFrameBuffer.build(GLFrameBuffer.java:241)
	at arc.graphics.gl.FrameBuffer.resize(FrameBuffer.java:115)
	at mindustry.graphics.Pixelator.drawPixelate(Pixelator.java:36)
	at mindustry.core.Renderer.update(Renderer.java:166)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:174)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
</details>

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Probide a crash log.

**Comment by LTHPKBTE** [comment]
[crash-report-08_11_2021_13_35_53.txt](https://github.com/Anuken/Mindustry/files/6966282/crash-report-08_11_2021_13_35_53.txt)

**Comment by LTHPKBTE** [comment]
After restarting the game several times, the problem seemed to disappear.

**Comment by Anuken** [comment]
Cannot reproduce the issue across multiple launches and various zoom levels. Implemented a potential fix, but there's no way to be sure if it works.
