### ISSUE TITLE
Crash: NPE when building power node

### ISSUE THREAD

**Issue by simply-peachy** [Anuken/Mindustry#576]
Windows 7 64-bit, Mindustry beta 84 64-bit. Placed a large power node and got an electric shock. I can't re-create it, but I think the node would have touched a small power node and its placement would link two separate power networks.
```

java.lang.NullPointerException
	at io.anuke.mindustry.world.blocks.power.PowerNode.playerPlaced(PowerNode.java:104)
	at io.anuke.mindustry.world.blocks.BuildBlock.lambda$onConstructFinish$1(BuildBlock.java:75)
	at io.anuke.mindustry.world.blocks.BuildBlock$$Lambda$1/37794916.run(Unknown Source)
	at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:140)
	at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at io.anuke.mindustry.desktopsdl.DesktopLauncher.main(DesktopLauncher.java:17)
```

**Comment by Anuken** [comment]
This has already been fixed.
