### ISSUE TITLE
Crash on startup: Couldn't load shared library 'libsdl-arc64.so' for target: Linux, 64-bit

### ISSUE THREAD

**Issue by yangfl** [Anuken/Mindustry#5783]
**Platform**: Linux (Debian 12 testing)

**Build**: 129.2

**Issue**: Crash on startup

**Steps to reproduce**: `/usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar Mindustry.jar`

**Link(s) to mod(s) used**: none

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
```
[W] Failed to initialize Discord RPC - you are likely using a JVM <16.
[E] java.lang.ExceptionInInitializerError
	at arc.backend.sdl.SdlApplication.lambda$init$0(SdlApplication.java:74)
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:187)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:74)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:31)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: arc.util.ArcRuntimeException: Couldn't load shared library 'libsdl-arc64.so' for target: Linux, 64-bit
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
	at arc.backend.sdl.jni.SDL.<clinit>(SDL.java:118)
	... 5 more
Caused by: arc.util.ArcRuntimeException: java.lang.UnsatisfiedLinkError: /tmp/arc/d36ec2de/libsdl-arc64.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/arc/d36ec2de/libsdl-arc64.so)
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:288)
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
	... 6 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/arc/d36ec2de/libsdl-arc64.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/arc/d36ec2de/libsdl-arc64.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:294)
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:260)
	... 7 more

[E] Failed to save local crash report.: java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:355)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$9(DesktopLauncher.java:228)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$10(DesktopLauncher.java:228)
	at mindustry.net.CrashSender.send(CrashSender.java:87)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:225)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:50)
```

Additionally, after failing to launch, mindustry leaves a file named `libsdl-arc64.so`, and a directory `.temp` in the current directory.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Download the itch.io version, the current latest github release depends on the newest glibc.
