### ISSUE TITLE
Items.copper is null

### ISSUE THREAD

**Issue by Hid-K** [Anuken/Mindustry#6023]
**Platform**: *Mac*

**Build**: *126.2*

**Issue**: *When my mod being loaded - Items.copper (and maybe others) is null*

**Steps to reproduce**: *Create mod, using [ MindustryJavaModTemplate](https://github.com/Anuken/MindustryJavaModTemplate)

**(Crash) logs**: *Mindustry has crashed. How unfortunate.
Version: release build 126.2
OS: Mac OS X x64
Java Version: 1.8.0_222
Java Architecture: 64
2 Mods: mindustry-network:0.1, time-control:0.2

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: contentinit
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:670)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:143)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: contentinit
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:105)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	... 6 more
Caused by: arc.util.ArcRuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at arc.util.async.AsyncResult.get(AsyncResult.java:34)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:103)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at mindustry.core.ContentLoader.initialize(ContentLoader.java:123)
	at mindustry.core.ContentLoader.init(ContentLoader.java:100)
	at mindustry.ClientLauncher.lambda$setup$5(ClientLauncher.java:112)
	at arc.assets.AssetManager$1.loadAsync(AssetManager.java:329)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at mindustry.world.Block.init(Block.java:748)
	at mindustry.core.ContentLoader.initialize(ContentLoader.java:117)
	... 9 more
*

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Hid-K** [comment]
When mod just loaded, but game was not reloaded - Items are loaded normaly:
```Java
[I] Медь
[I] [ItemStack{item=Медь, amount=20}, ItemStack{item=Кремний, amount=30}]
[I] Loaded mod 'Mindustry network' in 22.7744ms
```
