### ISSUE TITLE
Helllo my game wont start up

### ISSUE THREAD

**Issue by sodaZados** [Anuken/Mindustry#6052]
Version: steam build 126.3
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.IllegalArgumentException: Failed to compile shader: Vertex shader
Vertex shader failed to compile with the following errors:
ERROR: 0:16: error(#174) Not enough data provided for construction constructor
ERROR: error(#273) 1 compilation errors.  No code generated

	at arc.graphics.gl.Shader.<init>(Shader.java:125)
	at arc.graphics.gl.Shader.<init>(Shader.java:130)
	at mindustry.graphics.CubemapMesh.<init>(CubemapMesh.java:66)
	at mindustry.graphics.g3d.PlanetRenderer.<init>(PlanetRenderer.java:55)
	at mindustry.core.Renderer.init(Renderer.java:56)
	at mindustry.ClientLauncher.update(ClientLauncher.java:148)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by Anuken** [comment]
Your graphics drivers are broken; they are rejecting valid shader code.

**Comment by sodaZados** [comment]
> Your graphics drivers are broken; they are rejecting valid shader code.

and how to fix it i am not good with computer?

**Comment by Anuken** [comment]
It's unlikely that you can fix it without using a different computer.

**Comment by sodaZados** [comment]
ok thankyou
