### ISSUE TITLE
Crash the game after a while

### ISSUE THREAD

**Issue by Miros77** [Anuken/Mindustry#6103]
Android: 4.1.2 Model:LG-E445 

v.6.126.2

Crash the game after a while

Crash log

[I] [GL] Version: GLES 2.0.0 / Imagination Technologies / PowerVR SGX 531
[I] [GL] Max texture size: 2048
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[W] Shader shaders/mesh.vert | shaders/planet.frag:
Vertex shader
Success.

[W] Shader shaders/screenspace.vert | shaders/shield.frag:
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/buildbeam.frag:
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/unitbuild.frag:
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/darkness.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/light.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/space.frag:
Fragment shader:
Success.

[W] Shader shaders/planet.vert | shaders/planet.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/planetgrid.vert | shaders/planetgrid.frag:
Vertex shader
Success.

[W] Shader shaders/atmosphere.vert | shaders/atmosphere.frag:
Fragment shader:
Success.

[W] Shader shaders/unlit.vert | shaders/planet.frag:
Vertex shader
Success.

[W] Shader shaders/screenspace.vert | shaders/screenspace.frag:
Fragment shader:
Success.

[I] Total time to load: 46394ms
[W] Shader bloomshaders/screenspace.vert | bloomshaders/bloom.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/cubemap.vert | shaders/cubemap.frag:
Vertex shader
Success.
Fragment shader:
Success.

[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
[E] javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x62e5a978: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x4e9a4309:0x00000000)
	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:412)
	at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:442)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
	at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
	at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:165)
	at arc.util.NetJavaImpl.lambda$http$0(NetJavaImpl.java:86)
	at arc.util.-$$Lambda$NetJavaImpl$a3UqDVxOhRAnLr1IDs046SvF3O4.run(lambda)
	at arc.util.async.AsyncExecutor.lambda$submit$2(AsyncExecutor.java:32)
	at arc.util.async.-$$Lambda$AsyncExecutor$KE9SyyTGG4hNpihnP_17AgwyEnY.call(lambda)
	at arc.util.async.-$$Lambda$rdUmJAVAO4dv3DFAJBzHpUHffrw.call(lambda)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x62e5a978: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x4e9a4309:0x00000000)
	at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
	... 17 more

The error is probably due to the fact that the system browser is old (use another site such as Google drive)

**Comment by Miros77** [comment]
![2021-10-05-10-50-28](https://user-images.githubusercontent.com/59547044/135982495-0e0de42f-720a-4e70-af1b-8ee086a954f5.jpg)
![2021-10-05-10-50-41](https://user-images.githubusercontent.com/59547044/135982528-c5c02e9f-27d7-4533-a71b-de86c9772636.jpg)

**Comment by Miros77** [comment]
Browser Optima
![2021-10-05-10-52-52](https://user-images.githubusercontent.com/59547044/135983216-ed3b3319-c0c0-4a0b-ab64-7cab029e6f61.jpg)

the link opens

**Comment by oinkymoo** [comment]
if you didn't delete the template, you'd know that "latest" is not a version. it could refer to 3 or 4 different versions

**Comment by Darkness6030** [comment]
Latest - is it 126.2? Or steam 126.3? Or maybe latest v7 pre alpha - 131?

**Comment by oinkymoo** [comment]
Don’t forget about BE, which by now might no longer be the latest

**Comment by Miros77** [comment]
Version

> Latest - is it 126.2? Or steam 126.3? Or maybe latest v7 pre alpha - 131?

126.2

**Comment by Anuken** [comment]
You did not post a crash log. Your log contains a HTTP error, but (1) that's expected on older devices, and (2) such an error does not cause a *crash*.
