### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by UrkY2041** [Anuken/Mindustry#6306]
release build 126.2
OS: Windows 7 x32
Java Version: 1.8.0_201-1-ojdkbuild
Java Architecture: 32
0 Mods

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:670)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:143)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:105)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	... 6 more
Caused by: arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load file: sprites/sprites.png
	at arc.util.async.AsyncResult.get(AsyncResult.java:34)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:103)
	... 9 more
Caused by: arc.util.ArcRuntimeException: Couldn't load file: sprites/sprites.png
	at arc.graphics.Pixmap.<init>(Pixmap.java:93)
	at arc.graphics.TextureData.load(TextureData.java:79)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:39)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:18)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error loading pixmap: Out of memory
	at arc.graphics.Pixmap$NativePixmap.<init>(Pixmap.java:596)
	at arc.graphics.Pixmap.<init>(Pixmap.java:91)
	... 9 more

**Comment by Ccode-lang** [comment]
Are you loading a mod???

**Comment by Ccode-lang** [comment]
Or loading a modified jar?

**Comment by Ccode-lang** [comment]
It's a sprite loading error

**Comment by Anuken** [comment]
You don't have enough memory to load the sprites.

**Comment by KaaBEL** [comment]
## itch.io downloaded mindustry won't load fully on 32-bit windows

Sorry for bad english.

**Issue**:  
(Attempting to open for the first time) PC version downloaded from itch.io either crashes with crash report (almost identical to this bug report and other ones: [#3695](https://github.com/Anuken/Mindustry/issues/3695), [#4166](https://github.com/Anuken/Mindustry/issues/4166), [#4739](https://github.com/Anuken/Mindustry/issues/4739) all found by searching internet). Or loads, but rendering context of the window eventually freezes before fully loading although after being loaded the music plays, and cursor changes by hover over menu buttons, which can be clicked and does sound effects, except I couldn't see what I was actually doing. The freeze time isn't dependant on the loading phase, but rather on the load of PC (high %s of CPU, HDD and RAM changing in task manager).

__*Right to the point*__, it doesn't seem to be caused by lack of RAM memory. The most reliable method (a crazy workaround) with which I opened and played the game was having 3 instances of Mindustry app opening at the same time (like the apps were distracted from getting frozen, by them slowing down the PC themselves xD ).
This is more like a crazy story, than *issue*, hopefully it will help someone.

**Steps to reproduce**:  
I have no Idea how to reproduce it, but I may give the detailed story how it developed by the time and __*I don't feel this being worth of bug/crash report*__, but idk (probbably even illegal to comment on such old crash).

First time I used Android emulator LDPlayer4 and `Mindustry_7-official-143.1_Apkpure.apk` app, which resulted in freezing rendering context of window (the cursor and rest of buttons of window worked) before fully loading too. I got to hear the main menu music or other times I noticed in task manager that the activity of LDPlayer4 fell down to around 0. Then yesterday, I realized there may be a PC version as well so I downloaded one at [anuke.itch.io/mindustry/downl...](https://anuke.itch.io/mindustry/download/eyJpZCI6MTQwMTY5LCJleHBpcmVzIjoxNjgzODM1OTM5fQ%3d%3d.oVTnxIUo8pEfrgF8q0a%2fOO%2fFIMk%3d) and extracted the contents of `mindustry-windows-32-bit.zip` into created `C:\Users\<user_name>\AppData\Roaming\Mindustry` directory. First run gave crash error, second froze while loaded, so I was trying extracting into other directories, opening, deleting all files/folders from `...\Roaming\Mindustry` and if I remember well, there was the first time It opened properly, if I remember well. So I thought it's because I deleted it's data after it initialized in its first round, so I tried extracting into other directories, but later couldn't even get it to crash (by out of memory). I knew it was possible as did got to play once, so I tried just opening them if I get lucky and it will load without freezing without any success, the time until the rendering freezes is random so loading animation progress differs, and here progress was even lowering (screen size, or mouse movement doesn't matter). As it was stated as lack of memory I tried to get as much available as possible, by close all other applications (including task manager) and later tried to fill RAM with something else for Windows background processes to leave more for mindustry and near after the bigger changes of opened apps the progress got more far then previously when PC was calm. So I got an idea to slow down PC by opening Mindustry in more windows at once. Tried to open 3, than 5 at one when I almost crashed the PC and I had to do hard turn off. After restart I opened 3 at once again (each after a blank window of previous one appears), and used task manager to close them when it was slowing down too much. This time it worked, I recorded this one and while it was working I opened other one that loaded fully too. But today I attempted to open it again. I hoped for it fixing itself so I don't have to open 3 at once, almost freeze the PC and ran out of RAM. Today instead of freezing I get only the same crash (attached crash report) over and over. Right now I keep one Mindustry window from 3 at once method, I recorded it today after alone one crashed. They are loaded all 3 without crashing or freezing (except slowing down the PC), already exceeding 90% of RAM (which I guess Windows saves by 'compressing' some of it, there is virtually more in use).

**Save file**: I was attempting to just get to the main menu, for the first time on PC, to test Midustry logic scripts, with whatever world to test in. After I get in the menu, there weren't any other problems yet during playing.

**Build** and **Platform** are best described in crash log I guess.

**(Crash) logs**:  
`crash-report-05_12_2023_10_49_50.txt`
```
Version: release build 144
OS: Windows 10 x32 (x86)
Java Version: 1.8.0_151-1-ojdkbuild
Runtime Available Memory: 622mb
Cores: 4
Mods: none (vanilla)

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:206)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:104)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: arc.util.ArcRuntimeException: Error loading pixmap from image data: Out of memory (sprites/sprites.png)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:102)
	... 9 more
Caused by: arc.util.ArcRuntimeException: Error loading pixmap from image data: Out of memory (sprites/sprites.png)
	at arc.graphics.Pixmap.load(Pixmap.java:734)
	at arc.graphics.Pixmap.<init>(Pixmap.java:74)
	at arc.graphics.TextureData.load(TextureData.java:75)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:35)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:16)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:52)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
  ```

**Comment by Anuken** [comment]
I can't reproduce any issues with the win32 version myself, and the real error seems to be in the image loading library (that I didn't write), so I can't fix it.
