### ISSUE TITLE
No resources after launching somewhere

### ISSUE THREAD

**Issue by fkarg** [Anuken/Mindustry#6337]
**Platform**: Linux

**Build**: steam build 126.3

**Issue**: When launching to a new location, I have _no_ resources available, instead of 2k copper, ...

**Steps to reproduce**: Launch to any new location.

**Save file**: [gdrive link](https://drive.google.com/file/d/1InwaB34BPOwlyNOBAMBrLOw8BuQJwXKv/view?usp=sharing)

Additional data: This is what stderr showed when running steam:
```
[I] Fetched content (LoadedMod): 0
[I] Fetched content (Schematic): 0
[I] Fetched content (Map): 0
Failed to load cookie file from cookie: Permission denied
[I] [Audio] Initialized SoLoud 202002 using MiniAudio at 44100hz / 128 samples / 2 channels
Installing breakpad exception handler for appid(gameoverlayui)/version(20211111224923)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[I] [GL] Version: OpenGL 4.6.0 / Intel / Mesa Intel(R) HD Graphics 620 (KBL GT2)
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[I] [JAVA] Version: 1.8.0_275
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[E] java.lang.RuntimeException: java.util.zip.ZipException: incorrect header check
	at mindustry.io.SaveIO.getMeta(SaveIO.java:95)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: incorrect header check
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at mindustry.io.SaveIO.readHeader(SaveIO.java:176)
	at mindustry.io.SaveIO.getMeta(SaveIO.java:89)
	... 11 more

[I] Total time to load: 5598ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
[I] Received steam stats.
[I] Fetched 31 community servers.
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [N/A?] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
  - I have just bought the game on steam after not playing for a year, since I was unable to get it to run otherwise on NixOS. I'd still like to fix my game state (have resources available on new location), even if it has been fixed.
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate. This was already fixed in v7, use the Steam beta branch.

**Comment by fkarg** [comment]
Thx!

**Comment by fkarg** [comment]
actually @Anuken , when launching somewhere else even on `steam build 134.1` it still occurs. [Gamedata file](https://drive.google.com/file/d/1WusyX57iD5BJ329EAIdwO7WIYD-nogr5/view?usp=sharing)

**Comment by fkarg** [comment]
Maybe I can be more specific: what I just did was launching from a numbered sector next to 'Ground Zero' (174) to 'The Craters', with Silicon. Upon arrival, I had no resources - no copper, no lead, no silicon.

**Comment by Anuken** [comment]
Works correctly for me. Are you misreading the "3k copper 2k silicon" as *items in the loadout*, when they are just the *cost of the core*? You don't get 2k copper (or other resources) upon arrival by default.

**Comment by fkarg** [comment]
Ah I see. Yeah this seems to be what happened. I think the default loadout used to be nonzero, which is probably why I got confused.
