### ISSUE TITLE
Game Crashed when Ctrl Z Core over Sand

### ISSUE THREAD

**Issue by xBlueDragonFlamex** [Anuken/Mindustry#6427]
**Platform**: `Windows 10 x64`

**Build**: `steam build 135`

**Issue**: *When in the Editor Placing then Ctrl Z-ing a Core that was placed on Sand or Dark Sand(Even on just one sand) will crash the game.*

**Steps to reproduce**: *open the map editor, place sand, place core on sand, Ctrl Z.*

**Note**: *I tested it several times and one time it didn't crash, resizing the map and redoing it still crashed the game*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 3
	at mindustry.ai.BlockIndexer.addIndex(BlockIndexer.java:143)
	at mindustry.ai.BlockIndexer.lambda$new$1(BlockIndexer.java:59)
	at arc.Events.lambda$fire$2(Events.java:31)
	at arc.struct.Seq.each(Seq.java:199)
	at arc.Events.fire(Events.java:31)
	at arc.Events.fire(Events.java:26)
	at mindustry.world.Tile.fireChanged(Tile.java:622)
	at mindustry.editor.EditorTile.fireChanged(EditorTile.java:99)
	at mindustry.world.Tile.preChanged(Tile.java:561)
	at mindustry.world.Tile.setBlock(Tile.java:215)
	at mindustry.world.Tile.setBlock(Tile.java:204)
	at mindustry.editor.EditorTile.setBlock(EditorTile.java:44)
	at mindustry.editor.DrawOperation.lambda$setTile$2(DrawOperation.java:64)
	at mindustry.editor.MapEditor.load(MapEditor.java:72)
	at mindustry.editor.DrawOperation.setTile(DrawOperation.java:57)
	at mindustry.editor.DrawOperation.updateTile(DrawOperation.java:38)
	at mindustry.editor.DrawOperation.undo(DrawOperation.java:25)
	at mindustry.editor.OperationStack.undo(OperationStack.java:40)
	at mindustry.editor.MapEditor.undo(MapEditor.java:308)
	at mindustry.editor.MapEditorDialog.doInput(MapEditorDialog.java:629)
	at mindustry.editor.MapEditorDialog.lambda$new$26(MapEditorDialog.java:201)
	at arc.scene.Element.act(Element.java:79)
	at arc.scene.Group.act(Group.java:37)
	at arc.scene.ui.Dialog.act(Dialog.java:264)
	at arc.scene.Group.act(Group.java:41)
	at arc.scene.Scene.act(Scene.java:194)
	at arc.scene.Scene.act(Scene.java:139)
	at mindustry.core.UI.update(UI.java:142)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:177)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in dev branch.
