### ISSUE TITLE
Radeon driver crashes randomly with the game

### ISSUE THREAD

**Issue by MinirichiPap** [Anuken/Mindustry#6594]
**Platform**: *Windows*

**Build**: *135*

**Issue**: *sometimes it crashes at the loading screen, sometimes it starts flashing wildly soon after loading, sometimes it randomly crashes at some point in the game and sometimes it even crashes my graphics card (radeon RX 560 with the drivers version 22.2.2) and the computer frezees until the radeon open up the crash report*

**Steps to reproduce**: *there's no pattern to when it will happen.*

**Link(s) to mod(s) used**: *no mods*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[saves.zip](https://github.com/Anuken/Mindustry/files/8111503/saves.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crashes.zip](https://github.com/Anuken/Mindustry/files/8111505/crashes.zip)
[last_log.txt](https://github.com/Anuken/Mindustry/files/8111506/last_log.txt)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The provided log is empty, and no other devices (*not even phones*) have this problem. Considering the fact that *your drivers are crashing*, this is a driver issue on your end - not something I can fix.

**Comment by MinirichiPap** [comment]
weird, here the log contains this:

java.lang.IllegalArgumentException: Failed to compile shader: Vertex shader
Vertex shader failed to compile with the following errors:
Fragment shader:
Fragment shader failed to compile with the following errors:

	at arc.graphics.gl.Shader.<init>(Shader.java:125)
	at arc.graphics.g2d.SpriteCache.createDefaultShader(SpriteCache.java:145)
	at arc.graphics.g2d.MultiCacheBatch.<init>(MultiCacheBatch.java:13)
	at mindustry.graphics.FloorRenderer.clearTiles(FloorRenderer.java:230)
	at mindustry.graphics.FloorRenderer.lambda$new$0(FloorRenderer.java:31)
	at arc.Events.lambda$fire$2(Events.java:30)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:30)
	at arc.Events.fire(Events.java:25)
	at mindustry.core.World.endMapLoad(World.java:219)
	at mindustry.graphics.MenuRenderer.generate(MenuRenderer.java:164)
	at mindustry.graphics.MenuRenderer.<init>(MenuRenderer.java:37)
	at mindustry.ui.fragments.MenuFragment.build(MenuFragment.java:29)
	at mindustry.core.UI.init(UI.java:205)
	at mindustry.ClientLauncher.update(ClientLauncher.java:148)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by Anuken** [comment]
What I mean is that *the shader compilation log is empty*, which means the driver isn't even giving me *any* information about what's going wrong. There should be something relevant after the "following errors" text, but there isn't. That (and the crashing) is most definitely a driver bug.

**Comment by MinirichiPap** [comment]
Oh, I see, well I hope the next driver update for radeon solves the problem. I discovered that this is only happening on the 64x version, I'm able to play the 32x version just fine.
