### ISSUE TITLE
Building/unbuilding beside unloaders causes a NullPointerException.

### ISSUE THREAD

**Issue by SimonWoodburyForget** [Anuken/Mindustry#660]
Specific info.
- version: bleeding edge, using `./gradlew desktop:run`;
- os: Ubuntu 18.04.

Exception output:

```
AL lib: (WW) FreeDevice: (0x7fdae053e720) Deleting 2 Buffer(s)
java.lang.NullPointerException
        at io.anuke.mindustry.world.blocks.storage.Unloader.hasItem(Unloader.java:102)
        at io.anuke.mindustry.world.blocks.storage.Unloader.update(Unloader.java:63)
        at io.anuke.mindustry.entities.type.TileEntity.update(TileEntity.java:306)
        at io.anuke.mindustry.entities.EntityGroup.update(EntityGroup.java:47)
        at io.anuke.mindustry.core.Logic.update(Logic.java:204)
        at io.anuke.arc.ApplicationCore.update(ApplicationCore.java:36)
        at io.anuke.mindustry.ClientLauncher.update(ClientLauncher.java:114)
        at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:168)
        at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:148)
        at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:53)
        at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:40)
```

Exception reproducibility:
- exception occurs if anything is being built or unbuilt beside an (empty?) unloader, like:
  - an unloader beside an unloader,
  - a container beside an unloader,
  - a power node beside an unloader,
  - a shock mine beside an unloader,
  - a rock beside an unloader;
- exception only occur if map build speed multiplier is low enough, like 1, 0.1, or 2;
- exception doesn't occur if build speed multiplier is large enough, like 100.

**Comment by Anuken** [comment]
Fixed.
