### ISSUE TITLE
Cannot read field "tags" because "this.lastSchematic" is null

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#6614]
**Platform**: Windows 10

**Build**: v135

**Issue**: 
![image](https://user-images.githubusercontent.com/45698812/156479247-2dd995e5-3117-4470-a37d-78687dd74b92.png)

**Steps to reproduce**: 
select a schematic on a tower defense server right before game over
press the Save Schematic button after the map changes
give your schematic a nice name
press OK
crash

**Link(s) to mod(s) used**: ldb, override-lib

**Save file**: Please don't reap my soul D:

**(Crash) logs**: 
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 135
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Mods: ldb:1.3.2, override-lib:1.0.1

java.lang.NullPointerException: Cannot read field "tags" because "this.lastSchematic" is null
	at mindustry.input.InputHandler.lambda$showSchematicSave$27(InputHandler.java:626)
	at mindustry.core.UI$2.lambda$new$3(UI.java:275)
	at arc.scene.Element$9.changed(Element.java:968)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:366)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:100)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:151)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in private branch.
