### ISSUE TITLE
Server crashes when no players are on a team in PvP when the game ends

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#6789]
**Platform**: Server

**Build**: Erekir

**Issue**: The game crashes when a gameover happens for a team that has no players. I'm not aware of the specifics.

**Steps to reproduce**: 
1. Have a PvP game
2. Have all people on crux ragequit or otherwise disconnect
3. `gameover` to cause crux to win

**Save file**: Could not recover the autosave at the time this issue occured, sending the last one the server had (change extension)  
[auto_cavern_05-08-2022_21-49-47.msav.txt](https://github.com/Anuken/Mindustry/files/8647860/auto_cavern_05-08-2022_21-49-47.msav.txt)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**:
```
gameover                                                                                                                                      
[05-08-2022 21:49:45] [I] Core destroyed.                                                                                                     
[05-08-2022 21:49:45] [I] Game over! Team crux is victorious with 1 players online on map Cavern.
[05-08-2022 21:49:45] [E] java.lang.NullPointerException: Cannot invoke "mindustry.gen.Player.team()" because "mindustry.Vars.player" is null
        at mindustry.core.Logic.updateGameOver(Logic.java:405)     
        at mindustry.gen.Call.updateGameOver(Call.java:1657)
        at mindustry.server.ServerControl.lambda$setup$7(ServerControl.java:189)
        at mindustry.server.ServerControl$$Lambda$1357/0x00000000445ec278.get(Unknown Source)
        at arc.Events.fire(Events.java:53)
        at arc.Events.fire(Events.java:43)                         
        at mindustry.server.ServerControl.lambda$registerCommands$62(ServerControl.java:919)
        at mindustry.server.ServerControl$$Lambda$1347/0x00000000445eb068.get(Unknown Source)
        at arc.util.CommandHandler.lambda$register$1(CommandHandler.java:124)
        at arc.util.CommandHandler$$Lambda$1315/0x00000000445e80d0.accept(Unknown Source)
        at arc.util.CommandHandler.handleMessage(CommandHandler.java:85)
        at arc.util.CommandHandler.handleMessage(CommandHandler.java:29) 
        at mindustry.server.ServerControl.handleCommandString(ServerControl.java:976)
        at mindustry.server.ServerControl.lambda$new$0(ServerControl.java:52)
        at mindustry.server.ServerControl$$Lambda$1448/0x000000004468d178.run(Unknown Source)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:81)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already fixed.
