### ISSUE TITLE
[B93] Crash with NullPointerException 

### ISSUE THREAD

**Issue by matjaeck** [Anuken/Mindustry#700]
Reporting in case you haven't fixed it already in B94.

```
java.lang.NullPointerException
        at io.anuke.mindustry.entities.units.Statuses.update(Statuses.java:89)
        at io.anuke.mindustry.entities.type.Unit.updateVelocityStatus(Unit.java:251)
        at io.anuke.mindustry.entities.type.BaseUnit.update(BaseUnit.java:289)
        at io.anuke.mindustry.entities.type.GroundUnit.update(GroundUnit.java:108)
        at io.anuke.mindustry.entities.EntityGroup.update(EntityGroup.java:47)
        at io.anuke.mindustry.core.Logic.update(Logic.java:198)
        at io.anuke.arc.ApplicationCore.update(ApplicationCore.java:36)
        at io.anuke.mindustry.ClientLauncher.update(ClientLauncher.java:114)
        at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:168)
        at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:148)
        at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:53)
        at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:41)
```

```
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```

**Comment by Anuken** [comment]
I have.
