### ISSUE TITLE
/

### ISSUE THREAD

**Issue by byzp** [Anuken/Mindustry#7168]
ubuntu server 22.04 aarch64 
openjdk-17-jre-headless
server 135.2
There is no plugin installed and a custom map is used. 
(Everyone is disconnected when an error is thrown. )
---------------------------------------------------------------------

[07-13-2022 13:45:02] [E] java.lang.IllegalArgumentException: No enum constant mindustry.world.meta.BlockFlag.resupply
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at mindustry.world.meta.BlockFlag.valueOf(BlockFlag.java:4)
        at mindustry.gen.LogicIO.read(LogicIO.java:343)
        at mindustry.logic.LParser.statement(LParser.java:139)
        at mindustry.logic.LParser.parse(LParser.java:175)
        at mindustry.logic.LParser.parse(LParser.java:31)
        at mindustry.logic.LAssembler.read(LAssembler.java:55)
        at mindustry.logic.LAssembler.assemble(LAssembler.java:38)
        at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateCode(LogicBlock.java:295)
        at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateCode(LogicBlock.java:286)
        at mindustry.world.blocks.logic.LogicBlock$LogicBuild.readCompressed(LogicBlock.java:248)
        at mindustry.world.blocks.logic.LogicBlock.lambda$new$0(LogicBlock.java:47)
        at mindustry.gen.Building.configured(Building.java:1324)
        at mindustry.input.InputHandler.tileConfig(InputHandler.java:348)                                         at mindustry.gen.TileConfigCallPacket.handleServer(TileConfigCallPacket.java:49)
        at mindustry.net.Net.handleServerReceived(Net.java:311)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:128)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:82)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)

[07-13-2022 13:45:02] [E] java.lang.IllegalArgumentException: No enum constant mindustry.world.meta.BlockFlag.resupply
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at mindustry.world.meta.BlockFlag.valueOf(BlockFlag.java:4)
        at mindustry.gen.LogicIO.read(LogicIO.java:343)
        at mindustry.logic.LParser.statement(LParser.java:139)
        at mindustry.logic.LParser.parse(LParser.java:175)
        at mindustry.logic.LParser.parse(LParser.java:31)
        at mindustry.logic.LAssembler.read(LAssembler.java:55)
        at mindustry.logic.LAssembler.assemble(LAssembler.java:38)
        at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateCode(LogicBlock.java:295)
        at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateTile(LogicBlock.java:426)
        at mindustry.gen.Building.update(Building.java:1193)                                                      at mindustry.entities.EntityGroup.update(EntityGroup.java:59)
        at mindustry.gen.Groups.update(Groups.java:75)                                                            at mindustry.core.Logic.update(Logic.java:413)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:88)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)                    
[07-13-2022 13:45:02] [E] java.lang.IllegalArgumentException: No enum constant mindustry.world.meta.BlockFlag.resupply
        at java.base/java.lang.Enum.valueOf(Enum.java:273)                                                        at mindustry.world.meta.BlockFlag.valueOf(BlockFlag.java:4)
        at mindustry.gen.LogicIO.read(LogicIO.java:343)
        at mindustry.logic.LParser.statement(LParser.java:139)
        at mindustry.logic.LParser.parse(LParser.java:175)                                                        at mindustry.logic.LParser.parse(LParser.java:31)
        at mindustry.logic.LAssembler.read(LAssembler.java:55)
        at mindustry.logic.LAssembler.assemble(LAssembler.java:38)
        at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateCode(LogicBlock.java:295)                     at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateTile(LogicBlock.java:426)
        at mindustry.gen.Building.update(Building.java:1193)
        at mindustry.entities.EntityGroup.update(EntityGroup.java:59)
        at mindustry.gen.Groups.update(Groups.java:75)
        at mindustry.core.Logic.update(Logic.java:413)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:88)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)

[07-13-2022 13:45:02] [E] java.lang.IllegalArgumentException: No enum constant mindustry.world.meta.BlockFlag.resupply
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at mindustry.world.meta.BlockFlag.valueOf(BlockFlag.java:4)
        at mindustry.gen.LogicIO.read(LogicIO.java:343)
        at mindustry.logic.LParser.statement(LParser.java:139)
        at mindustry.logic.LParser.parse(LParser.java:175)
        at mindustry.logic.LParser.parse(LParser.java:31)
        at mindustry.logic.LAssembler.read(LAssembler.java:55)
        at mindustry.logic.LAssembler.assemble(LAssembler.java:38)
        at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateCode(LogicBlock.java:295)
        at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateTile(LogicBlock.java:426)
        at mindustry.gen.Building.update(Building.java:1193)
        at mindustry.entities.EntityGroup.update(EntityGroup.java:59)
        at mindustry.gen.Groups.update(Groups.java:75)
        at mindustry.core.Logic.update(Logic.java:413)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:88)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)

**Comment by Anuken** [comment]
Not applicable to BE builds, e.g. latest master.
