### ISSUE TITLE
Repeated crashing on steam release (Build 96)

### ISSUE THREAD

**Issue by sean-gribben** [Anuken/Mindustry#723]
I am experiencing a repeated Null pointer exception on the steam release for a multiplayer game. The error is as follows, and identical across all crash logs:

java.lang.RuntimeException: Failed to to read remote method 'linkPowerNodes'!
	at io.anuke.mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:96)
	at io.anuke.mindustry.core.NetClient.lambda$new$4(NetClient.java:129)
	at io.anuke.mindustry.net.Net.handleClientReceived(Net.java:246)
	at io.anuke.mindustry.desktop.steam.SNet$1.update(SNet.java:90)
	at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:159)
	at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:147)
	at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:42)
Caused by: java.lang.NullPointerException
	at io.anuke.mindustry.world.blocks.power.PowerNode.linkPowerNodes(PowerNode.java:43)
	at io.anuke.mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:94)
	... 7 more

I have uploaded 2 of the crash reports.

[crash-report-09_27_2019_09_40_20.txt](https://github.com/Anuken/Mindustry/files/3660283/crash-report-09_27_2019_09_40_20.txt)
[crash-report-09_27_2019_09_39_15.txt](https://github.com/Anuken/Mindustry/files/3660284/crash-report-09_27_2019_09_39_15.txt)

**Comment by Anuken** [comment]
Already reported and fixed, see other report.
