### ISSUE TITLE
Repeated Crashing on Steam Release

### ISSUE THREAD

**Issue by AerosolNinja** [Anuken/Mindustry#724]
**Platform**: Window
**Build**: Steam Build 96

**Issue**: Imported save data from itch.io version and have repeatable CTD when clicking pre-existing mass drivers:

java.lang.NullPointerException
	at io.anuke.mindustry.world.blocks.distribution.MassDriver.linkMassDriver(MassDriver.java:50)
	at io.anuke.mindustry.gen.Call.linkMassDriver(Call.java:210)
	at io.anuke.mindustry.world.blocks.distribution.MassDriver.onConfigureTileTapped(MassDriver.java:198)
	at io.anuke.mindustry.input.InputHandler.tileTapped(InputHandler.java:164)
	at io.anuke.mindustry.input.DesktopInput.pollInput(DesktopInput.java:217)
	at io.anuke.mindustry.input.DesktopInput.update(DesktopInput.java:154)
	at io.anuke.mindustry.core.Control.update(Control.java:413)
	at io.anuke.arc.ApplicationCore.update(ApplicationCore.java:36)
	at io.anuke.mindustry.ClientLauncher.update(ClientLauncher.java:115)
	at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:159)
	at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:147)
	at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:42)

**Steps to reproduce**: Click different mass drivers when checking their output targets.
[crash-report-09_26_2019_16_39_20.txt](https://github.com/Anuken/Mindustry/files/3660300/crash-report-09_26_2019_16_39_20.txt)
[crash-report-09_26_2019_16_39_50.txt](https://github.com/Anuken/Mindustry/files/3660301/crash-report-09_26_2019_16_39_50.txt)
[crash-report-09_26_2019_16_40_13.txt](https://github.com/Anuken/Mindustry/files/3660302/crash-report-09_26_2019_16_40_13.txt)

**Comment by Anuken** [comment]
Fixed.
