### ISSUE TITLE
Crash when Joining multiplayer game in V7

### ISSUE THREAD

**Issue by Priohm** [Anuken/Mindustry#7264]
Version: steam build 136.1
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 8176mb
Cores: 12
Mods: none (vanilla)

java.lang.NullPointerException: Cannot invoke "arc.math.geom.Position.getX()" because "other" is null
	at arc.math.geom.Position.within(Position.java:41)
	at mindustry.gen.PayloadUnit.activelyBuilding(PayloadUnit.java:487)
	at mindustry.gen.PayloadUnit.updateBuildLogic(PayloadUnit.java:2051)
	at mindustry.gen.PayloadUnit.update(PayloadUnit.java:1832)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
	at mindustry.gen.Groups.update(Groups.java:79)
	at mindustry.core.Logic.update(Logic.java:495)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by Anuken** [comment]
This was already fixed.
