### ISSUE TITLE
Game crash (null pointer exception) when launching to Impact 078

### ISSUE THREAD

**Issue by theosherman** [Anuken/Mindustry#7359]
Version: steam build 126.3
OS: Windows 11
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

**Issue**:  Game crashes when launching to Impact 078

**Steps to reproduce**: Load the attached game data export. Launch to Impact 078. BOOM!!!

[mindustry_data.zip](https://github.com/Anuken/Mindustry/files/9332431/mindustry_data.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
java.lang.NullPointerException
	at mindustry.core.Control.lambda$new$22(Control.java:219)
	at arc.struct.Seq.toString(Seq.java:1004)
	at mindustry.core.Control.lambda$new$23(Control.java:219)
	at arc.util.Time.update(Time.java:82)
	at mindustry.core.Logic.update(Logic.java:384)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:164)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
126.3 is more than a year old, use the beta.
