### ISSUE TITLE
Can't load saves after updating Mindustry

### ISSUE THREAD

**Issue by Froggo8311** [Anuken/Mindustry#7373]
**Platform**: Arch Linux (I have tried the bundled java (OpenJDK JRE Zulu 1.8.0_275-b01), OpenJDK JRE 1.8.0_345-b01, and OpenJDK JRE 18.0.2+9 with no changes.)

**Build**: Previous Version was 22,739. Current version is 126.2 (downloaded from GitHub releases), alpha is 7.0 build 137 (also from GitHub).

**Issue**: I checked to see if the game had an update since I had last played it, and of course it did. So I went ahead and downloaded the new .jar from the latest non-pre release on GitHub, and deleted the previous jar file. I went into campaign and found that all of my data was missing. I tried both individually importing tme *.msave files (Play > Load Game), but that would just create new files named `[0, 1, 2...].msav` in my `~/.local/share/Mindustry/saves` folder. I then compressed everything from `~/.local/share/Mindustry/` into a zip file (the same one uploaded) and then tried importing the zip file (Settings > Game Data > Import Data). I downloaded the latest alpha build 7.0-137, and it **did** have all of my data. I hope this helps, although it seems this will not be an issue in the future.

**Steps to reproduce**: See above

**Link(s) to mod(s) used**: None

**Save file**: I doubt it will help much as they were working previously, but I uploaded a zip of all of the contents of `~/.local/share/Mindustry`
[save.zip](https://github.com/Anuken/Mindustry/files/9339557/save.zip)

**(Crash) logs**: It didn't crash, but here's the output anyway (`java -Xmx8G -jar Mindustry.jar > ~/Desktop/mindustry-log.txt`):
```
Initialized Discord rich presence.
[Audio] Initialized SoLoud 202002 using MiniAudio at 44100hz / 128 samples / 2 channels
[GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / NVIDIA GeForce GTX 960/PCIe/SSE2
[GL] Max texture size: 16384
[GL] Using OpenGL 2 context.
[JAVA] Version: 18.0.2
java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.getMeta(java.io.DataInput)" because the return value of "arc.struct.IntMap.get(int)" is null
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.getMeta(java.io.DataInput)" because the return value of "arc.struct.IntMap.get(int)" is null
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.getMeta(java.io.DataInput)" because the return value of "arc.struct.IntMap.get(int)" is null
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.getMeta(java.io.DataInput)" because the return value of "arc.struct.IntMap.get(int)" is null
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.getMeta(java.io.DataInput)" because the return value of "arc.struct.IntMap.get(int)" is null
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.getMeta(java.io.DataInput)" because the return value of "arc.struct.IntMap.get(int)" is null
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.getMeta(java.io.DataInput)" because the return value of "arc.struct.IntMap.get(int)" is null
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.getMeta(java.io.DataInput)" because the return value of "arc.struct.IntMap.get(int)" is null
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Sector serpulo#175 (175) has two corresponding saves: /home/froggo/.local/share/Mindustry/saves/1.msav and /home/froggo/.local/share/Mindustry/saves/sector-serpulo-175.msav
Sector serpulo#175 (175) has two corresponding saves: /home/froggo/.local/share/Mindustry/saves/sector-serpulo-175.msav and /home/froggo/.local/share/Mindustry/saves/0.msav
Total time to load: 2560ms
Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
Fetched 37 community servers.
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You can't downgrade versions. Once you use the alpha, there is no going back.
