### ISSUE TITLE
Game crashes after 2 minutes in main menu

### ISSUE THREAD

**Issue by 5UP3R-D1N** [Anuken/Mindustry#7444]
**Platform**: Windows

**Build**: v137

**Issue**: The game crashes with this error : `at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:182)` after 2 minutes in main menu

**Steps to reproduce**: I don't know how it happen I tried deleted all data, reinstalling the game but its seem to be my windows, then I completely reinstall it, still error

**Link(s) to mod(s) used**: nope

**Save file**: not in game

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 5UP3R-D1N** [comment]
Here's the one in \crashes\
[crash-report-08_22_2022_20_15_49.txt](https://github.com/Anuken/Mindustry/files/9425254/crash-report-08_22_2022_20_15_49.txt)
And here's the one in last_log : 
```
[E] java.nio.BufferUnderflowException
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:182)
	at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:771)
	at mindustry.client.utils.ClientUtilsKt.bytes(ClientUtils.kt:51)
	at mindustry.client.communication.Packets$Header.<init>(Packets.kt:78)
	at mindustry.client.communication.Packets$CommunicationClient.handle(Packets.kt:174)
	at mindustry.client.communication.Packets$CommunicationClient.access$handle(Packets.kt:124)
	at mindustry.client.communication.Packets$CommunicationClient$1.invoke(Packets.kt:140)
	at mindustry.client.communication.Packets$CommunicationClient$1.invoke(Packets.kt:140)
	at mindustry.client.communication.BlockCommunicationSystem.logicEvent(BlockCommunicationSystem.kt:87)
	at mindustry.client.communication.BlockCommunicationSystem.init$lambda-8(BlockCommunicationSystem.kt:119)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.input.InputHandler.lambda$tileConfig$21(InputHandler.java:490)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:195)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:74)

[I] Saved on exit.
```

**Comment by buthed010203** [comment]
@blahblahbloopster i blame you for this

**Comment by buthed010203** [comment]
Its the auto-updater 0.6 mod that you're using, not only is that wayy out of date but its also entirely useless while using foo's as it will just uninstall the client not to mention it already has an auto updater builtin. I will be adding this mod to the auto disabled mod list i guess

**Comment by 5UP3R-D1N** [comment]
Thx I'll update the game as soon as I get into my computer!
