### ISSUE TITLE
Crashes every time I try to start it. No idea what these errors are.

### ISSUE THREAD

**Issue by Arya1234343** [Anuken/Mindustry#7697]
Here is the error: 
```
Mindustry has crashed. How unfortunate.
Version: beta build 139
OS: Windows 10 x64 (amd64)
Java Version: 18.0.2
Runtime Available Memory: 4078mb
Cores: 4
Mods: ui-lib:3.16.6, unit-factory:3.5.0, [#25f12f]vanilla-extended[]:1.82, better-menders:1, me:1.09, unit-cap-modifier:1

rhino.WrappedException: Wrapped java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1 (areas#154)
	at rhino.Context.throwAsScriptRuntimeEx(Context.java:1538)
	at rhino.MemberBox.invoke(MemberBox.java:126)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.areas_5._c_anonymous_24(areas:154)
	at rhino.gen.areas_5.call(areas)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.areas_5._c_anonymous_28(areas:171)
	at rhino.gen.areas_5.call(areas)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.areas_5.call(areas)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy2/jdk.proxy2.$Proxy1.run(Unknown Source)
	at arc.util.Time.update(Time.java:82)
	at mindustry.core.Control.update(Control.java:659)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
	at arc.struct.Seq.get(Seq.java:456)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at rhino.MemberBox.invoke(MemberBox.java:104)
	... 26 more

```

**Comment by Arya1234343** [comment]
Just took a closer look at it. my mods caused errors. Used 138 to disable them. work now. Sorry!
