### ISSUE TITLE
F-Droid wrong version name

### ISSUE THREAD

**Issue by linsui** [Anuken/Mindustry#7700]
The version name in https://raw.githubusercontent.com/Anuken/MindustryBuilds/master/version_fdroid.txt is 7-fdroid-139 but I get 7-fdroid-1050. Could you please take a look? Thanks!

**Comment by linsui** [comment]
In the past the version name and the version code correspond to the tag name so they should be 7-fdroid-139 and 139. I want to know if the 1050 is correct. Should we set the buildversion to 139 instead of the version code?

**Comment by Anuken** [comment]
Yes, the build version (`-Pbuildversion`) should be 139. I don't remember what the `versionCode` is for - Android internal build code? Again, it's been a long time since I've had anything to do with this, so I don't really remember why things are the way they are.

**Comment by linsui** [comment]
Got it. Thanks!

**Comment by linsui** [comment]
It builds but crashes...

```
FATAL EXCEPTION: GLThread 13676
Process: io.anuke.mindustry, PID: 9478
arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Error reading pack file: sprites/sprites.aatls
    at arc.assets.AssetManager.handleTaskError(AssetManager.java:12)
    at arc.assets.AssetManager.update(AssetManager.java:6)
    at arc.assets.AssetManager.update(AssetManager.java:9)
    at mindustry.ClientLauncher.update(ClientLauncher.java:4)
    at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:22)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
Caused by: arc.util.ArcRuntimeException: Error reading pack file: sprites/sprites.aatls
    at arc.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:39)
    at arc.assets.loaders.TextureAtlasLoader.getDependencies(TextureAtlasLoader.java:4)
    at arc.assets.loaders.TextureAtlasLoader.getDependencies(TextureAtlasLoader.java:1)
    at arc.assets.AssetLoadingTask.handleSyncLoader(AssetLoadingTask.java:4)
    at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:3)
    at arc.assets.AssetManager.updateTask(AssetManager.java:2)
    at arc.assets.AssetManager.update(AssetManager.java:5)
    ... 5 more
Caused by: arc.util.ArcRuntimeException: Error reading file: sprites/sprites.aatls (internal)
    at arc.backend.android.AndroidFi.read(AndroidFi.java:5)
    at arc.files.Fi.read(Fi.java:29)
    at arc.files.Fi.reads(Unknown Source:6)
    at arc.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:4)
    ... 11 more
Caused by: java.io.FileNotFoundException: sprites/sprites.aatls
    at android.content.res.AssetManager.nativeOpenAsset(Native Method)
    at android.content.res.AssetManager.open(AssetManager.java:876)
    at android.content.res.AssetManager.open(AssetManager.java:853)
    at arc.backend.android.AndroidFi.read(AndroidFi.java:2)
    ... 14 more
```

The apk is https://gitlab.com/linsui/fdroiddata/-/jobs/3163544394/artifacts/raw/tmp/io.anuke.mindustry_1050.apk, the build log is https://gitlab.com/linsui/fdroiddata/-/jobs/3163544394. The apk is smaller that yours. I guess something is missed. Could you please take a look? Thanks!

**Comment by Anuken** [comment]
It looks like the sprites aren't being included in the APK. Try invoking `./gradlew pack` **before** the apk creation build command, looking at the log, Gradle is doing something funny with the APK creation steps occurring before it's packed.

**Comment by linsui** [comment]
Thanks! Trying...

**Comment by linsui** [comment]
It works! Thanks!

**Comment by licaon-kter** [comment]
it happened again: https://github.com/Anuken/MindustryBuilds/commit/241ae5ec60027adabf05105ff0bc34b7580e242f

we can fix it in our metadata for now

**Comment by Anuken** [comment]
Fix what? I'm not sure "what" happened again.
