### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by AxoCat** [Anuken/Mindustry#7743]
**Platform**: Windows

**Build**: steam build 139

**Issue**: game crashes on startup with error IndexOutOfBounds: index can't be >= size: 1 >= 1

**Steps to reproduce**: i have no idea what i did, it just started happening

**Link(s) to mod(s) used**: none

**(Crash) logs**: Mindustry has crashed. How unfortunate.
Version: steam build 139
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 8176mb
Cores: 12

rhino.WrappedException: Wrapped java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1 (areas#154)
	at rhino.Context.throwAsScriptRuntimeEx(Context.java:1538)
	at rhino.MemberBox.invoke(MemberBox.java:126)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.areas_12._c_anonymous_24(areas:154)
	at rhino.gen.areas_12.call(areas)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.areas_12._c_anonymous_28(areas:171)
	at rhino.gen.areas_12.call(areas)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.areas_12.call(areas)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy2/jdk.proxy2.$Proxy5.run(Unknown Source)
	at arc.util.Time.update(Time.java:82)
	at mindustry.core.Control.update(Control.java:659)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
	at arc.struct.Seq.get(Seq.java:456)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at rhino.MemberBox.invoke(MemberBox.java:104)
	... 26 more

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Link(s) to mod(s) used: none

No. That crash is caused by mods. Uninstall them.
