### ISSUE TITLE
Caused by: java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1

### ISSUE THREAD

**Issue by noverd** [Anuken/Mindustry#7753]
Im running 139
And got a error
[E] rhino.WrappedException: Wrapped java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1 (areas#154)
	at rhino.Context.throwAsScriptRuntimeEx(Context.java:1538)
	at rhino.MemberBox.invoke(MemberBox.java:126)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.areas_12._c_anonymous_24(areas:154)
	at rhino.gen.areas_12.call(areas)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.areas_12._c_anonymous_28(areas:171)
	at rhino.gen.areas_12.call(areas)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.areas_12.call(areas)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at com.sun.proxy.$Proxy1.run(Unknown Source)
	at arc.util.Time.update(Time.java:82)
	at mindustry.core.Control.update(Control.java:659)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
	at arc.struct.Seq.get(Seq.java:456)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at rhino.MemberBox.invoke(MemberBox.java:104)
	... 26 more
Platform: linux64
java:
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

**Comment by BlueWolf3682** [comment]
This is caused by mods. Disable them.

**Comment by noverd** [comment]
Ok thx
