### ISSUE TITLE
Upgrading server to v140 Network I/O error when client joins.

### ISSUE THREAD

**Issue by Larofeticus** [Anuken/Mindustry#7792]
dedicated servers run on an ubuntu 22.04 LTS, the java is 17.01

client i use is a v140 binary i just downloaded from itch to a windows machine

starting with v139 servers and client that worked fine.

Rebuilt servers with a ./gradlew server:dist -Pbuildversion=140

No errors or warnings with rebuild, restarted servers and from the server perspective everything looks good

Connect with my v140 client, i can get the map and initial welcome dialog, then it crashes out with "Connection error: Network I/O error."

I don't see any other v140 servers yet, so I can't check my client against that.

I have a crash log I'll post it in a second comment shortly

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Larofeticus** [comment]
last log:
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / NVIDIA GeForce RTX 3060/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 16.0.1
[I] [RAM] Available: 3.9 GB
[I] [Mindustry] Version: 140
[I] Total time to load: 2088ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 35 community servers.
[I] Connecting to server: /165.232.137.170:6568
[I] Received world data: 72666 bytes.
[I] Disconnecting.
[E] java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.b(Reads.java:73)
	at mindustry.io.TypeIO.readString(TypeIO.java:758)
	at mindustry.gen.SendMessageCallPacket2.handled(SendMessageCallPacket2.java:34)
	at mindustry.net.Net.handleClientReceived(Net.java:263)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(Unknown Source)
	at arc.util.io.Reads.b(Reads.java:71)
	... 8 more

[E] java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.i(Reads.java:46)
	at mindustry.io.TypeIO.readInts(TypeIO.java:808)
	at mindustry.gen.SetUnitCommandCallPacket.handled(SetUnitCommandCallPacket.java:39)
	at mindustry.net.Net.handleClientReceived(Net.java:263)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(Unknown Source)
	at arc.util.io.Reads.i(Reads.java:44)
	... 8 more

[E] java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.i(Reads.java:46)
	at mindustry.io.TypeIO.readInts(TypeIO.java:808)
	at mindustry.gen.SetUnitCommandCallPacket.handled(SetUnitCommandCallPacket.java:39)
	at mindustry.net.Net.handleClientReceived(Net.java:263)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(Unknown Source)
	at arc.util.io.Reads.i(Reads.java:44)
	... 8 more

[E] java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.i(Reads.java:46)
	at mindustry.gen.SetMapAreaCallPacket.handled(SetMapAreaCallPacket.java:37)
	at mindustry.net.Net.handleClientReceived(Net.java:263)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(Unknown Source)
	at arc.util.io.Reads.i(Reads.java:44)
	... 7 more

[E] java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.i(Reads.java:46)
	at mindustry.gen.SetMapAreaCallPacket.handled(SetMapAreaCallPacket.java:37)
	at mindustry.net.Net.handleClientReceived(Net.java:263)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(Unknown Source)
	at arc.util.io.Reads.i(Reads.java:44)
	... 7 more

[E] java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.i(Reads.java:46)
	at mindustry.gen.SetMapAreaCallPacket.handled(SetMapAreaCallPacket.java:37)
	at mindustry.net.Net.handleClientReceived(Net.java:263)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(Unknown Source)
	at arc.util.io.Reads.i(Reads.java:44)
	... 7 more

[E] java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.i(Reads.java:46)
	at mindustry.gen.SetMapAreaCallPacket.handled(SetMapAreaCallPacket.java:37)
	at mindustry.net.Net.handleClientReceived(Net.java:263)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(Unknown Source)
	at arc.util.io.Reads.i(Reads.java:44)
	... 7 more

[E] java.lang.RuntimeException: java.io.EOFException
	at arc.util.io.Reads.i(Reads.java:46)
	at mindustry.io.TypeIO.readInts(TypeIO.java:808)
	at mindustry.gen.SetUnitCommandCallPacket.handled(SetUnitCommandCallPacket.java:39)
	at mindustry.net.Net.handleClientReceived(Net.java:263)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(Unknown Source)
	at arc.util.io.Reads.i(Reads.java:44)
	... 8 more

**Comment by Larofeticus** [comment]
The same process on my test server (just a macbook) of reusing the existing server folder also failed, but If I start with a completely fresh clone then I can connect. Must be some artifact that the build fails to update... might be a valuable piece of information to share with other server operators.

**Comment by Larofeticus** [comment]
Yeah, can confirm on the main servers too: building v140 in a fresh clone does not have the network error.
