### ISSUE TITLE
Crashes when I try to join sector

### ISSUE THREAD

**Issue by TheAirBlow** [Anuken/Mindustry#7821]
**Platform**: Linux

**Build**: 25341

**Issue**: *it just crashes LOL*

**Steps to reproduce**: Join a damn sector. BTW, it doesn't crash if the game is paused the time you join (minimized window), it does it only after you unpause.

**Link(s) to mod(s) used**: All of them are listed in crash log.

**Save file**: [bugustry.zip](https://github.com/Anuken/Mindustry/files/9941828/bugustry.zip)

**(Crash) logs**:
```
Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 23541
OS: Linux x64 (amd64)
Java Version: 11.0.17
Runtime Available Memory: 2458mb
Cores: 4
Mods: newconsole:1.8.1, time-control:0.2

java.lang.NullPointerException
        at mindustry.graphics.BlockRenderer.drawShadows(BlockRenderer.java:293)
        at arc.graphics.g2d.SortedSpriteBatch.flushRequests(SortedSpriteBatch.java:158)
        at arc.graphics.g2d.SortedSpriteBatch.flush(SortedSpriteBatch.java:138)
        at arc.graphics.g2d.Draw.flush(Draw.java:375)
        at mindustry.core.Renderer.draw(Renderer.java:373)
        at mindustry.core.Renderer.update(Renderer.java:224)
        at arc.ApplicationCore.update(ApplicationCore.java:37)
        at mindustry.ClientLauncher.update(ClientLauncher.java:230)
        at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheAirBlow** [comment]
It crashes since 23540, 23539 works without any problem. f9d7c17 is the commit that breaks shadows.
