### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#7893]
**Platform**: *Headless server*

**Build**: *Release v140.3*

**Issue**: *The server without mods crashed with this exception:*

`[E] java.lang.NullPointerException: Cannot invoke "mindustry.world.Tile.relativeTo(int, int)" because "facing" is null
        at mindustry.world.blocks.distribution.Conveyor$ConveyorBuild.acceptItem(Conveyor.java:
353)
        at mindustry.world.blocks.distribution.Conveyor$ConveyorBuild.pass(Conveyor.java:298)
        at mindustry.world.blocks.distribution.Conveyor$ConveyorBuild.updateTile(Conveyor.java:
275)
        at mindustry.gen.Building.update(Building.java:2115)
        at mindustry.gen.Building.updatePayload(Building.java:2159)
        at mindustry.world.blocks.payloads.BuildPayload.update(BuildPayload.java:51)
        at mindustry.gen.PayloadUnit.update(PayloadUnit.java:1926)
        at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
        at mindustry.gen.Groups.update(Groups.java:83)
        at mindustry.core.Logic.update(Logic.java:472)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:87)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)`

**Steps to reproduce**: *Idk, it just crashed.* BUT before it i enabled experimental rule "Units Update In Payloads"

**Link(s) to mod(s) used**: *No mods.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Darkness6030** [comment]
Steps to reproduce:
rules.unitPayloadUpdate -> true
put a chain of item-source, conveyor and item-void
choose any item in item-source
pick up conveyor with mega
mindustry crashes
