### ISSUE TITLE
java.lang.ClassCastException from drop payload code

### ISSUE THREAD

**Issue by Larofeticus** [Anuken/Mindustry#7902]
Dedicated server, running v140.3

Noticed an exception on the terminal by the luck of checking before it scrolled too far past:

[11-12-2022 19:01:40] [E] java.lang.ClassCastException: class mindustry.gen.NullUnit cannot be cast to class mindustry.gen.Payloadc (mindustry.gen.NullUnit and mindustry.gen.Payloadc are in unnamed module of loader 'app')
        at mindustry.input.InputHandler.requestDropPayload(InputHandler.java:420)
        at mindustry.gen.RequestDropPayloadCallPacket.handleServer(RequestDropPayloadCallPacket.java:48)
        at mindustry.net.Net.handleServerReceived(Net.java:310)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:151)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:81)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)

Nobody reported a gameplay problem at the time, and the problem didn't crash the server. I'm not aware of any direct or indirect links between this code and something that my plugin touches.

I don't know if or where a dedicated server leaves crash logs, is it just extracted from the regular logs or is there another mechanism?

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LeoSko** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

How about actually doing that?

**Comment by LeoSko** [comment]
@Anuken, I'm so confused now. This is a clear duplicate of #4929, which was left as is, but that one was ignored. What changed?

**Comment by Larofeticus** [comment]
@LeoSko Searching for requestDropPayload is not going to find an issue with requestBuildPayload. So no it's not a guarantee that a resonable scan of the issue history will find something from 1.5 years and 3000 issues ago.

**Comment by Anuken** [comment]
It's still of no consequence, but if it keeps coming up, might as well suppress the error. Doesn't actually change any behavior.
