### ISSUE TITLE
ArrayIndexOutOfBoundsException in Pathfinder

### ISSUE THREAD

**Issue by Pointifix** [Anuken/Mindustry#7952]
**Platform**: Linux v2202202169319180514 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64

**Build**: 140.4

**Issue**: Bug causes server application to exit and server to restart (wrapped in a shell script loop)

```
java.lang.ArrayIndexOutOfBoundsException: Index -1847 out of bounds for length 360000
	at mindustry.ai.Pathfinder.get(Pathfinder.java:194)
	at mindustry.gen.LegsUnit.isPathImpassable(LegsUnit.java:697)
	at mindustry.ai.types.CommandAI.updateUnit(CommandAI.java:147)
	at mindustry.gen.LegsUnit.update(LegsUnit.java:2101)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:476)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:87)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```

**Steps to reproduce**: It happened on the Sectorized server several times in the past week. Since the stack trace does not contain any of the server plugin classes i assume that the bug is unrelated to the server plugin but i am not certain about that.

**Link(s) to mod(s) used**: (https://github.com/Pointifix/SectorizedPlugin)

**Save file**: Cannot create a map save since server restarts instantly and i don´t know how to deliberatly cause the error.

**(Crash) logs**: [log-0.txt](https://github.com/Anuken/Mindustry/files/10046246/log-0.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Pointifix** [comment]
![image](https://user-images.githubusercontent.com/35230128/202892839-416dd1e7-21ae-40d1-8aab-d35d42278d5c.png)

I got sent this picture today from a player on my server shortly before the bug happened, maybe it helps
