### ISSUE TITLE
Cannot open the game

### ISSUE THREAD

**Issue by Bell2U** [Anuken/Mindustry#7962]
**Platform**: Windows 10 pro

**Build**: steam build 140.4

**Issue**: When I tried to open the game, it crashed, a window poped up said:  
> A crash has occured. It has been saved in:  
C:\Users\49505\AppData\Roaming\Mindustry\crashes\crash-report-11_20_2022_15_23_32.txt  
IllegalArgument:
key cannot be null.

**Steps to reproduce**: Just launched the game from steam.

**Link(s) to mod(s) used**: None

**Save file**: no saved game file since I cannot open the game..

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Here is the crash log:  
> Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md
>
> Version: steam build 140.4
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4078mb
Cores: 12
Mods: none (vanilla)
>
> arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: Vars
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:208)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: Vars
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:104)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key cannot be null.
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:102)
	... 9 more
Caused by: java.lang.IllegalArgumentException: key cannot be null.
	at arc.struct.ObjectMap.put(ObjectMap.java:116)
	at mindustry.mod.Mods.resolveDependencies(Mods.java:817)
	at mindustry.mod.Mods.load(Mods.java:421)
	at mindustry.Vars.init(Vars.java:335)
	at mindustry.Vars.loadAsync(Vars.java:256)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:352)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:52)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:16)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Dragoncode333** [comment]
Same problem :(

**Comment by DamnCyberStickman** [comment]
Got the same problem, and I think I know how to fix it.
Have you installed any mods? If yes, remember mod, what you downloaded, before the problem appeared. try to launch Mindustry with opened mods folder. Before Mindustry launches, delete this mod from folder. Mindustry will not find it, and thats all - problem fixed! If it didn't work or you didn't downloaded any mods, I don't know how to fix it.
(Sorry for bad english, I don't know it. I used Google translate.)

**Comment by Bell2U** [comment]
> Got the same problem, and I think I know how to fix it. Have you installed any mods? If yes, remember mod, what you downloaded, before the problem appeared. try to launch Mindustry with opened mods folder. Before Mindustry finally launches, delete this mod from folder as fast, as you can. Mindustry will not find it, and thats all - problem fixed! If it didn't work or you didn't downloaded any mods, I don't know how to fix it. I hope that helped. (Sorry for bad english, I don't know it. I used Google translate.)

This works!!! How do you find it? it's awesome! Thank you for letting me play this game again and save my game data.
p.s. The path of the mod folder is __<where you install the steam>\Steam\steamapps\common\Mindustry\saves\mods__ for windows

**Comment by DamnCyberStickman** [comment]
> > Got the same problem, and I think I know how to fix it. Have you installed any mods? If yes, remember mod, what you downloaded, before the problem appeared. try to launch Mindustry with opened mods folder. Before Mindustry finally launches, delete this mod from folder as fast, as you can. Mindustry will not find it, and thats all - problem fixed! If it didn't work or you didn't downloaded any mods, I don't know how to fix it. I hope that helped. (Sorry for bad english, I don't know it. I used Google translate.)
> 
> This works!!! How do you find it? it's awesome! Thank you for letting me play this game again and saving my game data. p.s. The path of the mod folder is **<where you install the steam>\Steam\steamapps\common\Mindustry\saves\mods** for windows

I'm glad I could help you. I came up with this method myself. I had this problem after installing the mod. Apparently, it became the limit for my PC, so he decided to close Mindustry. I tried to remove the mod from the folder, and the game opened. That's all.
