### ISSUE TITLE
oh no

### ISSUE THREAD

**Issue by Sussy919** [Anuken/Mindustry#8013]
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at mindustry.net.Net.pingHost(Net.java:331)
	at mindustry.ui.dialogs.JoinDialog.refreshCommunity(JoinDialog.java:422)
	at mindustry.ui.dialogs.JoinDialog.refreshAll(JoinDialog.java:124)
	at mindustry.ui.dialogs.JoinDialog.lambda$new$7(JoinDialog.java:102)
	at arc.scene.ui.Dialog$5.shown(Dialog.java:397)
	at arc.scene.event.VisibilityListener.handle(VisibilityListener.java:11)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Dialog.show(Dialog.java:468)
	at arc.scene.ui.Dialog.show(Dialog.java:507)
	at arc.scene.ui.Dialog.show(Dialog.java:502)
	at mindustry.ui.fragments.MenuFragment.checkPlay(MenuFragment.java:220)
	at mindustry.ui.fragments.MenuFragment.lambda$buildDesktop$24(MenuFragment.java:190)
	at mindustry.ui.fragments.MenuFragment.lambda$buttons$32(MenuFragment.java:261)
	at arc.scene.Element.lambda$clicked$2(Element.java:913)
	at arc.scene.Element$4.clicked(Element.java:922)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Phinner** [comment]
1. the template :skull:
2. You ran out of memory, are you sure you did not have top many programs open at the same time ?
