### ISSUE TITLE
❗ NullPointerException at  mindustry.entities.bullet.BulletType.lambda$updateHoming

### ISSUE THREAD

**Issue by Agzam-Ar** [Anuken/Mindustry#8065]
**Platform**: Windows 10

**Build**: 140.4

**Issue**: *Explain your issue in detail.*
The `bat` file is closing with server.
Error in logs: 
```
java.lang.NullPointerException
	at mindustry.entities.bullet.BulletType.lambda$updateHoming$6(BulletType.java:584)
	at mindustry.ai.BlockIndexer.lambda$findEnemyTile$8(BlockIndexer.java:358)
	at mindustry.ai.BlockIndexer.findTile(BlockIndexer.java:392)
	at mindustry.ai.BlockIndexer.findEnemyTile(BlockIndexer.java:358)
	at mindustry.entities.Units.findEnemyTile(Units.java:206)
	at mindustry.entities.Units.closestTarget(Units.java:252)
	at mindustry.entities.bullet.BulletType.updateHoming(BulletType.java:584)
	at mindustry.entities.bullet.BulletType.update(BulletType.java:553)
	at mindustry.gen.Bullet.update(Bullet.java:871)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:476)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:87)

	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: I made mod what make "melting ice and snow": (good idea for new planet: see P.S 2)
The class. that can make problem: https://github.com/Agzam4/Mindustry-plugin/blob/main/src/example/ServerEventsManager.java
Mod: https://github.com/Agzam4/Mindustry-plugin/
To active event in chat write `/event new_year on` and then skip map: `/skipmap` to activate event

**Save file**: 
[SaveToIssue.zip](https://github.com/Anuken/Mindustry/files/10251828/SaveToIssue.zip)

P.S: I was trying to cause another error that occurred on the SynapseOS server: 
![image](https://user-images.githubusercontent.com/90514725/208245253-7e43fe04-e68a-410d-b16b-228491fccbce.png)

P.S 2: how about ice planet, that have melting ice and snow by powered blocks (some ores under snow,to get they melt snow)?

maybe add null check?

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

EDIT: see version before `1.6` (on 1.6+ make error is harder)

**Comment by Agzam-Ar** [comment]
Also, i m get this error:
```java.lang.ArrayIndexOutOfBoundsException: 49
	at mindustry.world.blocks.power.PowerGraph.getPowerNeeded(PowerGraph.java:110)
	at mindustry.world.blocks.power.PowerGraph.update(PowerGraph.java:228)
	at mindustry.gen.PowerGraphUpdater.update(PowerGraphUpdater.java:167)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:476)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:87)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```

then create something like this:
![image](https://user-images.githubusercontent.com/90514725/209430941-3b8276a8-901b-42cd-b08b-1c4eff4bb9ad.png)

and destroy some regenerators
