### ISSUE TITLE
Mindustry has crashed | NullPointerException

### ISSUE THREAD

**Issue by Agzam-Ar** [Anuken/Mindustry#8092]
>Mindustry has crashed. How unfortunate.
> Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 140.4
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_351
Runtime Available Memory: 900mb
Cores: 4
Mods: none (vanilla)
```
java.lang.NullPointerException
	at mindustry.world.blocks.payloads.PayloadConveyor$PayloadConveyorBuild.updateTile(PayloadConveyor.java:158)
	at mindustry.world.blocks.payloads.PayloadRouter$PayloadRouterBuild.updateTile(PayloadRouter.java:142)
	at mindustry.gen.Building.update(Building.java:2121)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:476)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```

**Comment by Xasmedy** [comment]
The same bug but threw server side. (Before it crashing)
```console
[E] java.lang.NullPointerException: Cannot invoke "mindustry.gen.Building.acceptPayload(mindustry.gen.Building, mindustry.world.blocks.payloads.Payload)" because "this.next" is null
        at mindustry.world.blocks.payloads.PayloadConveyor$PayloadConveyorBuild.updateTile(PayloadConveyor.java:158)
        at mindustry.world.blocks.payloads.PayloadRouter$PayloadRouterBuild.updateTile(PayloadRouter.java:142)
        at mindustry.gen.Building.update(Building.java:2121)
        at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
        at mindustry.gen.Groups.update(Groups.java:83)
        at mindustry.core.Logic.update(Logic.java:476)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:87)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```

**Comment by Agzam-Ar** [comment]
You are the owner of the server you were on at the time of the crash?
If so, which server are you from?

**Comment by Xasmedy** [comment]
> > The same bug but threw server side. (Before it crashing)
> > ```
> > [E] java.lang.NullPointerException: Cannot invoke "mindustry.gen.Building.acceptPayload(mindustry.gen.Building, mindustry.world.blocks.payloads.Payload)" because "this.next" is null
> >         at mindustry.world.blocks.payloads.PayloadConveyor$PayloadConveyorBuild.updateTile(PayloadConveyor.java:158)
> >         at mindustry.world.blocks.payloads.PayloadRouter$PayloadRouterBuild.updateTile(PayloadRouter.java:142)
> >         . . .
> > ```
> 
> You are the owner of the server you were on at the time of the crash? If so, which server are you from?

Not the owner but directly under it, and `mindustry.ddns.net`.

**Comment by Agzam-Ar** [comment]
> Not the owner but directly under it, and `mindustry.ddns.net`.

Yes, I was on this server

I think the problem is in the plugin. When I made the plugin I had a lot of `NullPointerException` not leading on plugin code . I have tried to fix the problems many times and it seems that the server no longer crashes

I'm from `SynapseOS` server (and now playing on it)

**Comment by Xasmedy** [comment]
> Yes, I was on this server
> 
> I think the problem is in the plugin. When I made the plugin I had a lot of `NullPointerException` not leading on plugin code . I have tried to fix (editing the plugin) the problems many times and it seems that the server no longer crashes
> 
> I'm from `SynapseOS` server (and now playing on it)

We almost have no plugins, and the only one we have, does not interact with the world at all, except for a command that just views a tile info (but it is running since november and never gave problems).

**Comment by Agzam-Ar** [comment]
maybe you have saves?

**Comment by Dark-Diamond** [comment]
the reason for the crash is the processor logic

https://user-images.githubusercontent.com/79577330/209723378-3caed56a-1dcc-4136-a960-515be7c06dc5.mp4

**Comment by Agzam-Ar** [comment]
![image](https://user-images.githubusercontent.com/90514725/209723909-30d99631-5587-48c0-9cc4-a3acb195218d.png)
I'm make "ghost" blocks (they are not building)

**Comment by Agzam-Ar** [comment]
I'm make plugin, that fix it, but only on server-side 

PS: (тут все по русски говорят или только Dark-Diamond?)

**Comment by Agzam-Ar** [comment]
> I'm make plugin, that fix it, but only on server-side
> 
> PS: (тут все по русски говорят или только Dark-Diamond?)

Download here: https://github.com/Agzam4/Mindustry-bugfixes-plugin/releases

Maybe need add the destroying of this building? (then `next` is `null` in `FixedPayloadConveyor$PayloadConveyorBuild.updateTile()`)

**Comment by Agzam-Ar** [comment]
Result: 


https://user-images.githubusercontent.com/90514725/209851913-d99f7e5c-68b2-4e4c-872c-2213e3c7bb01.mp4
