### ISSUE TITLE
[crash report] mindustry.gen.Building.acceptPayload

### ISSUE THREAD

**Issue by vince2010091** [Anuken/Mindustry#8098]
Hello,

Please find below a crash report, hope this is useful:

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 140.4
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 2012mb
Cores: 4
Mods: none (vanilla)

java.lang.NullPointerException: Cannot invoke "mindustry.gen.Building.acceptPayload(mindustry.gen.Building, mindustry.world.blocks.payloads.Payload)" because "this.next" is null
	at mindustry.world.blocks.payloads.PayloadConveyor$PayloadConveyorBuild.updateTile(PayloadConveyor.java:158)
	at mindustry.world.blocks.payloads.PayloadRouter$PayloadRouterBuild.updateTile(PayloadRouter.java:142)
	at mindustry.gen.Building.update(Building.java:2121)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:476)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

Regards,

**Comment by Xasmedy** [comment]
Same issue from [here](https://github.com/Anuken/Mindustry/issues/8092)
