### ISSUE TITLE
 Mindustry has crashed. How unfortunate.

### ISSUE THREAD

**Issue by VETARUK** [Anuken/Mindustry#8114]
Version: steam build 140.4
OS: Windows 10 x32 (x86)
Java Version: 1.8.0_151-1-ojdkbuild
Runtime Available Memory: 622mb
Cores: 4
Mods: none (vanilla)

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:208)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: sprites/sprites.png
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:104)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: arc.util.ArcRuntimeException: Error loading pixmap from image data: Out of memory (sprites/sprites.png)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:102)
	... 9 more
Caused by: arc.util.ArcRuntimeException: Error loading pixmap from image data: Out of memory (sprites/sprites.png)
	at arc.graphics.Pixmap.load(Pixmap.java:734)
	at arc.graphics.Pixmap.<init>(Pixmap.java:74)
	at arc.graphics.TextureData.load(TextureData.java:75)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:35)
	at arc.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:16)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:52)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Kieaer** [comment]
https://github.com/Anuken/Mindustry/issues/8099#issuecomment-1368140248
