### ISSUE TITLE
Game crash when enter multiplayer server list

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#8161]
**Platform**: Windows 11

**Build**: Build 141

**Issue**: Same title.

**Steps to reproduce**: Turn on game -> Join game -> crash

**Link(s) to mod(s) used**: No mods.

**Save file**: [save.txt](https://github.com/Anuken/Mindustry/files/10404897/save.txt)

**(Crash) logs**
```
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 141
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 16368mb
Cores: 24
Mods: none (vanilla)

java.lang.IndexOutOfBoundsException: start 7, end 3, length 3
	at java.base/java.lang.AbstractStringBuilder.checkRange(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.base/java.lang.StringBuffer.append(Unknown Source)
	at java.base/java.text.MessageFormat.subformat(Unknown Source)
	at java.base/java.text.MessageFormat.format(Unknown Source)
	at java.base/java.text.Format.format(Unknown Source)
	at arc.util.TextFormatter.format(TextFormatter.java:48)
	at arc.util.I18NBundle.format(I18NBundle.java:463)
	at mindustry.ui.dialogs.JoinDialog.buildServer(JoinDialog.java:245)
	at mindustry.ui.dialogs.JoinDialog.lambda$addCommunityHost$46(JoinDialog.java:468)
	at arc.scene.ui.layout.Table.button(Table.java:431)
	at mindustry.ui.dialogs.JoinDialog.addCommunityHost(JoinDialog.java:468)
	at mindustry.ui.dialogs.JoinDialog.lambda$refreshCommunity$44(JoinDialog.java:454)
	at mindustry.net.ArcNetProvider.lambda$pingHost$6(ArcNetProvider.java:218)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kieaer** [comment]
New crash log when enter server list

```
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 141
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 16368mb
Cores: 24
Mods: none (vanilla)

java.lang.IllegalStateException: Array is empty.
	at arc.struct.Seq.peek(Seq.java:728)
	at arc.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:122)
	at arc.scene.ui.Label.computePrefSize(Label.java:148)
	at arc.scene.ui.Label.scaleAndComputePrefSize(Label.java:135)
	at arc.scene.ui.Label.getPrefWidth(Label.java:234)
	at arc.scene.ui.Label.<init>(Label.java:66)
	at arc.scene.ui.Label.<init>(Label.java:55)
	at arc.scene.ui.layout.Table.add(Table.java:317)
	at mindustry.ui.dialogs.JoinDialog.lambda$buildServer$21(JoinDialog.java:266)
	at arc.scene.ui.layout.Table.table(Table.java:275)
	at arc.scene.ui.layout.Table.table(Table.java:269)
	at mindustry.ui.dialogs.JoinDialog.buildServer(JoinDialog.java:262)
	at mindustry.ui.dialogs.JoinDialog.lambda$addCommunityHost$46(JoinDialog.java:468)
	at arc.scene.ui.layout.Table.button(Table.java:431)
	at mindustry.ui.dialogs.JoinDialog.addCommunityHost(JoinDialog.java:468)
	at mindustry.ui.dialogs.JoinDialog.lambda$refreshCommunity$44(JoinDialog.java:454)
	at mindustry.net.ArcNetProvider.lambda$pingHost$6(ArcNetProvider.java:218)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```
