### ISSUE TITLE
Crash upon entering map

### ISSUE THREAD

**Issue by nrombes** [Anuken/Mindustry#8185]
**Platform**: `Mac OS X x64`

**Build**: `steam build 141.2`

**Issue**: Game crashes when I try to enter a map on the mod world Midantha.

**Steps to reproduce**:  I just entered the map.

**Link(s) to mod(s) used**: `[Yuria/new-horizon:0.2.3]`

**Save file**: 
[mindustry_save_2.zip](https://github.com/Anuken/Mindustry/files/10421249/mindustry_save_2.zip)

**Crash report**: Mindustry has crashed. How unfortunate.
Version: steam build 141.2
OS: Mac OS X x64 (x86_64)
Java Version: 16.0.1
Runtime Available Memory: 4096mb
Cores: 16
Mods: new-horizon:0.2.3

java.lang.NullPointerException: Cannot invoke "mindustry.entities.EntityIndexer.change(mindustry.gen.Entityc, int)" because "this.indexer" is null
	at mindustry.entities.EntityGroup.remove(EntityGroup.java:209)
	at newhorizon.expand.entities.WorldEvent.remove(WorldEvent.java:130)
	at newhorizon.expand.eventsys.WorldEventType.trigger(WorldEventType.java:132)
	at newhorizon.expand.eventsys.ObjectiveEventType.trigger(ObjectiveEventType.java:69)
	at newhorizon.expand.eventsys.ObjectiveEventType.updateEvent(ObjectiveEventType.java:54)
	at newhorizon.expand.eventsys.ReachWaveObjective.updateEvent(ReachWaveObjective.java:22)
	at newhorizon.expand.entities.WorldEvent.update(WorldEvent.java:66)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:83)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:466)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Slotterleet** [comment]
I assume that's an issue with the mod since the stack trace contains `newhorizon`'s classes. Ask a mod developer to fix it.
