### ISSUE TITLE
crashing error in 142.2

### ISSUE THREAD

**Issue by arin-prashar** [Anuken/Mindustry#8390]
Last_og.txt file contents: --

[I] [GL] Version: OpenGL 4.6.0 / Intel / Intel(R) Iris(R) Xe Graphics
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 19.0.2
[I] [RAM] Available: 1.9 GB
[E] java.lang.ClassFormatError: Incompatible magic value 1734898746 in class file sun/nio/ch/WEPollSelectorProvider
	at java.base/sun.nio.ch.DefaultSelectorProvider.<clinit>(DefaultSelectorProvider.java:39)
	at java.base/java.nio.channels.spi.SelectorProvider$Holder.lambda$provider$0(SelectorProvider.java:106)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base/java.nio.channels.spi.SelectorProvider$Holder.provider(SelectorProvider.java:108)
	at java.base/java.nio.channels.spi.SelectorProvider$Holder.<clinit>(SelectorProvider.java:96)
	at java.base/java.nio.channels.spi.SelectorProvider.provider(SelectorProvider.java:183)
	at java.base/java.nio.channels.Selector.open(Selector.java:295)
	at arc.net.Client.<init>(Client.java:71)
	at mindustry.net.ArcNetProvider.<init>(ArcNetProvider.java:54)
	at mindustry.desktop.DesktopLauncher.getNet(DesktopLauncher.java:263)
	at mindustry.ClientLauncher.setup(ClientLauncher.java:139)
	at mindustry.ClientLauncher.init(ClientLauncher.java:256)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:162)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

crash.txt contents:
Mindustry has crashed. How unfortunate.
Version: release build 141.2
OS: Windows 11 x64 (amd64)
Java Version: 19.0.2
Runtime Available Memory: 1966mb
Cores: 12
<no mod init>

java.lang.ClassFormatError: Incompatible magic value 1734898746 in class file sun/nio/ch/WEPollSelectorProvider
	at java.base/sun.nio.ch.DefaultSelectorProvider.<clinit>(DefaultSelectorProvider.java:39)
	at java.base/java.nio.channels.spi.SelectorProvider$Holder.lambda$provider$0(SelectorProvider.java:106)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base/java.nio.channels.spi.SelectorProvider$Holder.provider(SelectorProvider.java:108)
	at java.base/java.nio.channels.spi.SelectorProvider$Holder.<clinit>(SelectorProvider.java:96)
	at java.base/java.nio.channels.spi.SelectorProvider.provider(SelectorProvider.java:183)
	at java.base/java.nio.channels.Selector.open(Selector.java:295)
	at arc.net.Client.<init>(Client.java:71)
	at mindustry.net.ArcNetProvider.<init>(ArcNetProvider.java:54)
	at mindustry.desktop.DesktopLauncher.getNet(DesktopLauncher.java:263)
	at mindustry.ClientLauncher.setup(ClientLauncher.java:139)
	at mindustry.ClientLauncher.init(ClientLauncher.java:256)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:162)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

[crash-report-03_12_2023_14_31_54.txt](https://github.com/Anuken/Mindustry/files/10950401/crash-report-03_12_2023_14_31_54.txt)
[last_log.txt](https://github.com/Anuken/Mindustry/files/10950402/last_log.txt)

please do something related to it

**Comment by Slotterleet** [comment]
Did you have mods installed?

**Comment by arin-prashar** [comment]
All mods are disabled then also it crashed.

**Comment by arin-prashar** [comment]
now when i am launching it i am getting this error
[hs_err_pid17612.log](https://github.com/Anuken/Mindustry/files/10959209/hs_err_pid17612.log)

**Comment by Anuken** [comment]
> Java Version: 19.0.2

This is not supported, use the bundled JDK version.
