### ISSUE TITLE
run_server.bat error

### ISSUE THREAD

**Issue by Sneezy123** [Anuken/Mindustry#8439]
I downloaded the `Server.zip` file from [itch.io](https://itch.io/anuken/mindustry) but when I want to run the `run_server.bat` file, I get this error:

```bash
[03-27-2023 13:59:56] [E] Failed to write settings log: arc.util.ArcRuntimeException: Error writing file: config\settings.log (local)
        at arc.files.Fi.writeString(Fi.java:518)
        at arc.files.Fi.writeString(Fi.java:502)
        at arc.Settings.writeLog(Settings.java:451)
        at arc.Settings.loadValues(Settings.java:125)
        at arc.Settings.load(Settings.java:72)
        at mindustry.Vars.loadSettings(Vars.java:432)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:46)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
Caused by: arc.util.ArcRuntimeException: Error writing file: config\settings.log (local)
        at arc.files.Fi.writer(Fi.java:478)
        at arc.files.Fi.writeString(Fi.java:515)
        ... 8 more
Caused by: java.io.FileNotFoundException: config\settings.log (Das System kann den angegebenen Pfad nicht finden)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at arc.files.Fi.writer(Fi.java:470)
        ... 9 more

[03-27-2023 13:59:59] [I] Server loaded. Type 'help' for help.
[03-27-2023 13:59:59] [E] arc.util.ArcRuntimeException: Error writing file: config\logs\log-0.txt (local)
        at arc.files.Fi.writeString(Fi.java:518)
        at arc.files.Fi.writeString(Fi.java:502)
        at mindustry.server.ServerControl.logToFile(ServerControl.java:1110)
        at mindustry.server.ServerControl.lambda$setup$2(ServerControl.java:98)
        at arc.util.Log.log(Log.java:16)
        at arc.util.Log.info(Log.java:42)
        at mindustry.server.ServerControl.lambda$setup$18(ServerControl.java:288)
        at arc.Events.fire(Events.java:53)
        at arc.Events.fire(Events.java:43)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:76)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
Caused by: arc.util.ArcRuntimeException: Error writing file: config\logs\log-0.txt (local)
        at arc.files.Fi.writer(Fi.java:478)
        at arc.files.Fi.writeString(Fi.java:515)
        ... 11 more
Caused by: java.io.FileNotFoundException: config\logs\log-0.txt (Das System kann den angegebenen Pfad nicht finden)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at arc.files.Fi.writer(Fi.java:470)
        ... 12 more

arc.util.ArcRuntimeException: Error writing file: config\logs\log-0.txt (local)
        at arc.files.Fi.writeString(Fi.java:518)
        at arc.files.Fi.writeString(Fi.java:502)
        at mindustry.server.ServerControl.logToFile(ServerControl.java:1110)
        at mindustry.server.ServerControl.lambda$setup$2(ServerControl.java:98)
        at arc.util.Log.log(Log.java:16)
        at arc.util.Log.info(Log.java:42)
        at mindustry.server.ServerControl.lambda$setup$18(ServerControl.java:288)
        at arc.Events.fire(Events.java:53)
        at arc.Events.fire(Events.java:43)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:76)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
Caused by: arc.util.ArcRuntimeException: Error writing file: config\logs\log-0.txt (local)
        at arc.files.Fi.writer(Fi.java:478)
        at arc.files.Fi.writeString(Fi.java:515)
        ... 11 more
Caused by: java.io.FileNotFoundException: config\logs\log-0.txt (The System cannot find the given path)
        at java. Base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at arc.files.Fi.writer(Fi.java:470)
        ... 12 more
[03-27-2023 13:59:59] [E] Failed to write settings log: arc.util.ArcRuntimeException: Error writing file: config\settings.log (local)
        at arc.files.Fi.writeString(Fi.java:518)
        at arc.files.Fi.writeString(Fi.java:502)
        at arc.Settings.writeLog(Settings.java:451)
        at arc.Settings.forceSave(Settings.java:95)
        at arc.Settings.manualSave(Settings.java:109)
        at mindustry.net.CrashSender.send(CrashSender.java:57)
        at mindustry.server.ServerLauncher.lambda$main$2(ServerLauncher.java:34)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
Caused by: arc.util.ArcRuntimeException: Error writing file: config\settings.log (local)
        at arc.files.Fi.writer(Fi.java:478)
        at arc.files.Fi.writeString(Fi.java:515)
        ... 7 more
Caused by: java.io.FileNotFoundException: config\settings.log (The System cannot find the given path)
        at java. Base/java.io.FileOutputStream.open0(Native Method)
        at java. Base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at arc.files.Fi.writer(Fi.java:470)
        ... 8 more


```

Do you know what that means or how to fix it. I think the program wants to write into a `config` file but can't find it.

**Comment by Anuken** [comment]
Never seen this issue before, cannot reproduce. Something is preventing it from creating the directory.

**Comment by Sneezy123** [comment]
Maybe it has to to something with that that it is in my `C:\Program Files\MindustryServer` directory and it needs admin privileges to create the directory, which it doesn't have…
