### ISSUE TITLE
Mindustry won't open

### ISSUE THREAD

**Issue by Zinuxus** [Anuken/Mindustry#8483]
**Platform**: Windows (Steam Version) 

**Build**: Game won't open so propably the latest version but i can't see it without opening Mindustry

**Issue**: When I start Mindustry (by clicking play on Steam) the game starts and the first 2 -3 seconds of the starting animation work good but then the game closes and there is a crash report. The crash report has a link to the Mindustry data files and I followed it this is the full crash report:

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 143
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 2046mb
Cores: 8
Mods: none (vanilla)

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: No cap character found in font
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:206)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: No cap character found in font
	at arc.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:382)
	at arc.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:205)
	at arc.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:194)
	at arc.freetype.FreetypeFontLoader.loadSync(FreetypeFontLoader.java:34)
	at mindustry.ui.Fonts$3.loadSync(Fonts.java:189)
	at mindustry.ui.Fonts$3.loadSync(Fonts.java:171)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:124)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more

**Steps to reproduce**: Mindustry worked good before and than all of the sudden it doesnt start anymore. I changed the GUI level to the lowest (probalbly 5) but I cant really imagine that that crashed the game but its the only thing I've done

**Link(s) to mod(s) used**: No mods (Vanilla)

**Save file**: full game problem

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 143
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 2046mb
Cores: 8
Mods: none (vanilla)

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: No cap character found in font
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:206)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: No cap character found in font
	at arc.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:382)
	at arc.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:205)
	at arc.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:194)
	at arc.freetype.FreetypeFontLoader.loadSync(FreetypeFontLoader.java:34)
	at mindustry.ui.Fonts$3.loadSync(Fonts.java:189)
	at mindustry.ui.Fonts$3.loadSync(Fonts.java:171)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:124)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
 (same as above)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [I cant open the game so ... ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [I literally deleted everything even close related to Mindsutry on my whole pc and it still crashes... ] **I have searched the closed and open issues to make sure that this problem has not already been reported.** - I have found nothing related to this bug

**Comment by Anuken** [comment]
> I changed the GUI level to the lowest (probalbly 5) but I cant really imagine that that crashed the game but its the only thing I've done

That is indeed the cause - 5% UI scale basically makes the UI so small that it's invisible. You will have to navigate into your game files and delete `settings.bin` to fix it - this will wipe all your campaign progress and settings. Or, you can wait for a new release.

(meep did it again...)

**Comment by Zinuxus** [comment]
Well... The thing is I already deleted everything in the midustry folder and it still doesn't work. I have the same problem again when I only delete the settings.bin

**Comment by Anuken** [comment]
> Well... The thing is I already deleted everything in the midustry folder and it still doesn't work. 

You must have deleted the wrong files. Did you delete inside the steam saves/ directory?

**Comment by MEEPofFaith** [comment]
Why *did* I make the min 5%.

**Comment by Zinuxus** [comment]
C:\Program Files (x86)\Steam\steamapps\common\Mindustry\saves

**Comment by Anuken** [comment]
Delete the entire saves folder and try again.

**Comment by MEEPofFaith** [comment]
Open BE with the fix, set ui scaling to a reasonable value, then switch back to original version.

**Comment by Anuken** [comment]
~~I hope they have Java installed then~~

**Comment by Lone-Ra** [comment]
Time is running out - the error is **not being corrected**.
Dedicated to all the guys who have the game running, but do not want to open the window with the game itself (No errors flew out), yes, the problem is in the interface and it helped me personally That:

1. Changing the resolution on the Windows itself:  "keyboard shortcut **"win+i"** -> **system** -> **display** -> change to any lower than your original one (I had enough to drop to **1280x1024**)", 

2. Then start the Game _(if it crashes again, just be more persistent and click many times on the game icon at the bottom of the taskbar or whatever her)_, 

3. And you should have the Game open, then **Settings** -> **Graphics** -> **Interface size** (_the very first slider and you will have 100%, reset it to 50-60%_), re-enter the game and everything should work, have a nice game to everyone.
