### ISSUE TITLE
Sdl Error (custom-build)

### ISSUE THREAD

**Issue by sibainu2** [Anuken/Mindustry#8545]
**Platform**: Windows

**Build**:It is a custom_build of V7, but it crashed and I cannot see the build number on the home screen. If you could tell me how to check it, I would appreciate it.

**Issue**:
Custom build crashes when running desctop run command. Crash report is below.

Other Information
The system was running until the previous day.
One thing that has changed is that we have upgraded the intel graphics.

**Steps to reproduce**: 
. \gradlew desktop:run
Run

**Link(s) to mod(s) used**: 
No mods used

**Data File**: 
This one, too, has crashed and data cannot be retrieved.
I would appreciate it if you could tell me where you saved the game data.

**(Crash) logs**: 
```
Mindustry has crashed. How unfortunate.
Version: custom build
OS: Windows 11 x64 (amd64)
Java Version: 17.0.7
Runtime Available Memory: 8128mb
Cores: 12
<no mod init>

arc.backend.sdl.SdlApplication$SdlError: Could not create GL context: 
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:35)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```
cmd log:
```
.\gradlew desktop:run
No Android SDK found. Skipping Android module.

> Configure project :
Compiling with build: 'custom build'

> Task :desktop:run
[I] Initialized Discord rich presence.
[E] arc.backend.sdl.SdlApplication$SdlError: Could not create GL context:
        at arc.backend.sdl.SdlApplication.init(SdlApplication.java:148)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:35)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

<============-> 95% EXECUTING [23m 49s]
> :desktop:run
```

![image](https://user-images.githubusercontent.com/84668924/235332174-346e5606-47ed-4091-908b-f718b5d89b9c.png)

**Comment by sibainu2** [comment]
From github it started fine.
Maybe this is the problem here, so I'm closing this question.
![image](https://user-images.githubusercontent.com/84668924/235333863-1961dcae-284b-490e-b790-d2091350b374.png)
