### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "mindustry.gen.Player.toString()" because "mindustry.Vars.player" is null

### ISSUE THREAD

**Issue by Baldur404** [Anuken/Mindustry#8598]
**Platform**: Macbook M2   MacOS: Ventura 13.3.1
**Build**: 144.1

**Issue**: 

myCode:
Events.on(EventType.DepositEvent.class, depositEvent -> {
    Call.sendMessage(depositEvent.player.name);
})

**Steps to reproduce**: run"myCode"on init() func that class extends Plugin,,,when I drop item to core...,,,throw"NPE"

**(Crash) logs**: *java.lang.NullPointerException: Cannot invoke "mindustry.gen.Player.toString()" because "mindustry.Vars.player" is null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Baldur404** [comment]
[05-13-2023 15:53:11] [E] java.lang.NullPointerException: Cannot invoke "mindustry.gen.Player.toString()" because "mindustry.Vars.player" is null
        at cragent.SensitiveOperation.lambda$DepositEventCheck$0(SensitiveOperation.java:24)
        at arc.Events.fire(Events.java:53)
        at arc.Events.fire(Events.java:43)
        at mindustry.input.InputHandler.transferInventory(InputHandler.java:345)
        at mindustry.gen.TransferInventoryCallPacket.handleServer(TransferInventoryCallPacket.java:44)
        at mindustry.net.Net.handleServerReceived(Net.java:312)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:151)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:81)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)

**Comment by Anuken** [comment]
You're accessing Vars.player, which is null.

**Comment by Baldur404** [comment]
how Can I catch player  name when he deposits items to a block.
