### ISSUE TITLE
v145 causing headless server crash

### ISSUE THREAD

**Issue by Larofeticus** [Anuken/Mindustry#8717]
**Platform**: Linux

**Build**: v145

**Issue**: Uploaded the new server.jar restarted server, crash dump immediately follows.

**Steps to reproduce**: Upgraded from v144 to v145. I could do it one more time to my other server.

**Link(s) to mod(s) used**: I am running one plugin. It is not publicly available.

**Save file**: Not applicable.

**(Crash) logs**: Console snip:

Server crashed with exit code 1. Restarting.
[06-18-2023 00:14:53] [I] 1 mods loaded.
[06-18-2023 00:14:53] [I] Server loaded. Type 'help' for help.
[06-18-2023 00:14:53] [I] Found 2 command-line arguments to parse.
[06-18-2023 00:14:53] [I] port set to 6567.
[06-18-2023 00:14:53] [I] initFallen
[06-18-2023 00:14:53] [I] Generating map.
[06-18-2023 00:14:53] [I] after constructor
[06-18-2023 00:14:55] [I] Map generated.
[06-18-2023 00:14:55] [E] arc.util.serialization.SerializationException: Serialization trace:
{}.planet
planet (mindustry.game.Rules)
        at arc.util.serialization.Json.readFields(Json.java:914)
        at arc.util.serialization.Json.readValue(Json.java:1095)
        at arc.util.serialization.Json.readValue(Json.java:990)
        at arc.util.serialization.Json.fromJson(Json.java:831)
        at mindustry.io.JsonIO.read(JsonIO.java:61)
        at mindustry.io.JsonIO.copy(JsonIO.java:57)
        at mindustry.game.Rules.copy(Rules.java:199)
        at eviction.EvictionMod.startEviction(EvictionMod.java:270)
        at eviction.EvictionMod.lambda$registerServerCommands$22(EvictionMod.java:400)
        at arc.util.CommandHandler.lambda$register$1(CommandHandler.java:125)
        at arc.util.CommandHandler.handleMessage(CommandHandler.java:86)
        at arc.util.CommandHandler.handleMessage(CommandHandler.java:30)
        at mindustry.server.ServerControl.lambda$setup$5(ServerControl.java:153)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:81)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
        at arc.struct.ObjectMap.get(ObjectMap.java:340)
        at mindustry.core.ContentLoader.getByName(ContentLoader.java:206)
        at mindustry.io.JsonIO$10.read(JsonIO.java:198)
        at mindustry.io.JsonIO$10.read(JsonIO.java:190)
        at arc.util.serialization.Json.readValue(Json.java:1102)
        at arc.util.serialization.Json.readFields(Json.java:907)
        ... 15 more

Server crashed with exit code 1. Restarting.

The location where this passes through my code, I initialize a Rules instance when starting the server:

private final Rules rules = new Rules();

Then later on (the line 270), at the start of each game I copy that master rules object into state:

state.rules = rules.copy();

Nowhere in my codebase do i touch a "planet" field in a Rules instance.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> The location where this passes through my code, I initialize a Rules instance when starting the server:
> private final Rules rules = new Rules();

You are likely doing this in the wrong place, which is to say, before content is loaded. This should be initialized on demand.

**Comment by Larofeticus** [comment]
Since November I have been doing this:

rules.env = Planets.serpulo.defaultEnv;

(or the erekir variant)

**Comment by Anuken** [comment]
That isn't related. I'm saying you should not call `new Rules()` in a plugin constructor. It should be initialized in `init()`.

While this can be fixed to not crash, the real issue is in your code. By initializing a Rules instance before content is loaded, you get other invalid state (a broken loadout, for example, as it refers to the copper item, which is null).

**Comment by Larofeticus** [comment]
I moved the new Rules() to later on and it works now.
