### ISSUE TITLE
A bug about modding

### ISSUE THREAD

**Issue by Jiawens** [Anuken/Mindustry#873]
**Platform**: (Android/iOS/Mac/Windows/Linux)
Windows
**Build**: (The build number under the title in the main menu. Required.)
steam build 97 and 98.1
**Issue**: (Explain your issue in detail.)
I installed the "Example Mod",and I succeed in starting a campaign.
But when I wanted to join a game(he also has this mod),the game crashed.
It dispalyed "Loading game data",and then it crashed.
It created a crash-report and this is the report:
```
java.lang.RuntimeException: java.io.IOException: Failed to read tile entity of block: example-mod-electrum-conveyor
	at io.anuke.mindustry.net.NetworkIO.loadWorld(NetworkIO.java:56)
	at io.anuke.mindustry.core.NetClient.lambda$new$3(NetClient.java:124)
	at io.anuke.mindustry.net.Net.handleClientReceived(Net.java:247)
	at io.anuke.mindustry.net.Net.handleClientReceived(Net.java:240)
	at io.anuke.mindustry.desktop.steam.SNet$1.update(SNet.java:89)
	at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:158)
	at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:146)
	at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:52)
Caused by: java.io.IOException: Failed to read tile entity of block: example-mod-electrum-conveyor
	at io.anuke.mindustry.io.SaveVersion.readMap(SaveVersion.java:194)
	at io.anuke.mindustry.net.NetworkIO.loadWorld(NetworkIO.java:54)
	... 8 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at io.anuke.mindustry.world.blocks.distribution.Conveyor$ConveyorEntity.read(Conveyor.java:370)
	at io.anuke.mindustry.io.SaveVersion.lambda$readMap$3(SaveVersion.java:191)
	at io.anuke.mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:72)
	at io.anuke.mindustry.io.SaveVersion.readMap(SaveVersion.java:189)
	... 9 more
```
**Steps to reproduce**: (How you happened across the issue, and what you were doing at the time.)
1. Install the mod "Example mod";
2. Join a game that has this mod.

**Comment by Anuken** [comment]
Are you sure both of you were using the same version of 'example mod'? Where did both of you get the mod?

**Comment by Jiawens** [comment]
I think this mod has only one version:1.0,so we probably use the same version.We both get it by "import github mod".And,several gamers succeed in joining the game.I don't know their situations.
But when I update the game to 98.1,I succeed in joining other's game in the local network instead of Steam network.Does it mean this bug is fixed?I couldn't check if it will be succeed through the Steam network because there isn't anyone playing games with this mod.I will try to check if it will succeed.

**Comment by Jiawens** [comment]
I checked it just now.It failed through Steam multiplayer.
I couldn't join other's game,but other gamers could join my game.
And not only I but also a few gamers couldn't join other's games.
I tried to reinstall the game,to my surprise,it succeed!(join other's game)But when I use the command"/sync",it crashed again:I couldn't join other's game.I reinstalled it again,but I still couldn't join.

**Comment by Jiawens** [comment]
I forgot a piece of information:the crash report.
It is:
```
java.lang.NullPointerException
	at io.anuke.mindustry.core.World.prepareTiles(World.java:408)
	at io.anuke.mindustry.core.World.endMapLoad(World.java:165)
	at io.anuke.mindustry.core.World$Context.end(World.java:474)
	at io.anuke.mindustry.io.SaveVersion.readMap(SaveVersion.java:208)
	at io.anuke.mindustry.net.NetworkIO.loadWorld(NetworkIO.java:54)
	at io.anuke.mindustry.core.NetClient.lambda$new$3(NetClient.java:124)
	at io.anuke.mindustry.net.Net.handleClientReceived(Net.java:247)
	at io.anuke.mindustry.net.Net.handleClientReceived(Net.java:240)
	at io.anuke.mindustry.desktop.steam.SNet$1.update(SNet.java:90)
	at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:158)
	at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:146)
	at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:52)
```

**Comment by Jiawens** [comment]
When I use another computer(also win10,mindustry 98.1),it crashed again.The error is "Array Index Out Of Bounds".

**Comment by Anuken** [comment]
Should be fixed next release.

**Comment by TheTinkerer3** [comment]
Still happens to me on release 104.10, On windows 10.
