### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#8741]
### Platforms

Windows

### Build

145.1

### Issue

Game crash.

### Steps to reproduce

Unknown. surrendly crashed.

Crashed during multiplayer.
Other players have all received the same error reports.

### Mods used

No mods.

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/11833865/save.zip)

### (Crash) logs

```
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 145.1
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 16368mb
Cores: 24
Mods: none (vanilla)

java.lang.NullPointerException: Cannot read field "size" because "this.plans" is null
	at mindustry.gen.ElevationMoveUnit.isBuilding(ElevationMoveUnit.java:391)
	at mindustry.gen.ElevationMoveUnit.clipSize(ElevationMoveUnit.java:529)
	at mindustry.entities.EntityGroup.draw(EntityGroup.java:109)
	at mindustry.core.Renderer.draw(Renderer.java:375)
	at mindustry.core.Renderer.update(Renderer.java:229)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:228)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Kieaer** [comment]
> ~save file means you save the played map and then export the save not export whole game data~

lol my mistake. must be add save file upload description

**Comment by Anuken** [comment]
Crash log doesn't make sense, cannot fix without specific steps to reproduce.
