### ISSUE TITLE
Mindustry crash

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry#8767]
### Platforms

Windows

### Build

145.1

### Issue

Map on server crashed down with error area out of bounds.

### Steps to reproduce

Got a save file from server but it won't open 

### Mods used

none

### Save file

[error.zip](https://github.com/Anuken/Mindustry/files/11892965/error.zip)

### (Crash) logs

Map on server crashed down with area out of bounds.

```[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] [Textures] Async: sprites/rays.png in 9.1605ms
[I] [Textures] Async: sprites/distortAlpha.png in 2.0737ms
[I] [Textures] Async: sprites/clouds.png in 7.8132ms
[I] [Textures] Async: sprites/planets/serpulo.png in 14.746ms
[I] [Textures] Async: sprites/planets/erekir.png in 13.6062ms
[I] Fetched 45 community servers.
[I] [Textures] Async: sprites/schematic-background.png in 1.1321ms
[I] Connecting to server: /160.16.207.141:23527
[I] Received world data: 306420 bytes.
[I] Disconnecting.
[E] java.lang.ArrayIndexOutOfBoundsException: Index 185760 out of bounds for length 185760
	at mindustry.world.Tiles.geti(Tiles.java:77)
	at mindustry.core.World$Context.tile(World.java:583)
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:327)
	at mindustry.net.NetworkIO.loadWorld(NetworkIO.java:82)
	at mindustry.core.NetClient.lambda$new$6(NetClient.java:165)
	at mindustry.net.Net.handleClientReceived(Net.java:293)
	at mindustry.net.Net.handleClientReceived(Net.java:285)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:195)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:57)
```

Server logs display tcp disconnection:
```[06-28-2023 18:26:56] [D] Packed 306436 bytes of world data.
[06-28-2023 18:26:57] [D] arc.net.ArcNetException: Error reading TCP from connection: Connection -244755681
        at arc.net.Server.update(Server.java:229)
        at arc.net.Server.run(Server.java:357)
        at mindustry.net.ArcNetProvider.lambda$hostServer$13(ArcNetProvider.java:300)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.SocketException: Connection is closed.
        at arc.net.TcpConnection.readObject(TcpConnection.java:97)
        at arc.net.Server.update(Server.java:223)
        ... 3 more
```

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by mahdiyadiilavi1** [comment]
#### why are you reporting a minecraft bug at here?

**Comment by rekokoro** [comment]
Okay, mistype

**Comment by Anuken** [comment]
The save file attached is invalid/corrupt.
