### ISSUE TITLE
"Local players cannot be traced and do not have info" crash when hosting

### ISSUE THREAD

**Issue by nekit508** [Anuken/Mindustry#8944]
### Platforms

Windows

### Build

145.1

### Issue

The game crashes when the block is configured.

### Steps to reproduce

1) start the game
2) play
3) custom map
4) select any map (I chose Fortress)
5) survival
6) play
7) mine some lead
8) place sorter
9) go to menu (esc)
10) host multiplayer game
11) host
12) back
13) select any resource in placed sorter (I choose copper)
14) sucks

### Mods used

null

### Save file

The save has not been saved.

### (Crash) logs

[I] Initialized Discord rich presence.
[I] [Core] Initialized SDL v2.0.20
[I] [Audio] Initialized SoLoud 202002 using MiniAudio at 44100hz / 2048 samples / 2 channels
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / GeForce 610M/PCIe/SSE2
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 16.0.2
[I] [RAM] Available: 1.4 GB
[I] [Mindustry] Version: 145.1
[I] Total time to load: 19997ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 54 community servers.
[E] java.lang.IllegalArgumentException: Local players cannot be traced and do not have info.
	at mindustry.gen.Player.getInfo(Player.java:607)
	at mindustry.net.Administration.lambda$new$1(Administration.java:73)
	at mindustry.net.Administration.allowAction(Administration.java:167)
	at mindustry.net.Administration.allowAction(Administration.java:154)
	at mindustry.input.InputHandler.tileConfig(InputHandler.java:479)
	at mindustry.gen.Call.tileConfig(Call.java:1545)
	at mindustry.gen.Building.configure(Building.java:1471)
	at mindustry.world.blocks.ItemSelection.lambda$buildTable$2(ItemSelection.java:73)
	at arc.scene.Element$9.changed(Element.java:988)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Submission

- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.

**Comment by camelStyleUser** [comment]
doesnt crash on linux x64 vanilla mindustry(not foos) 145.1

**Comment by Anuken** [comment]
> Save:
THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.
