### ISSUE TITLE
"Local players cannot be traced and do not have info" crash when hosting.. again

### ISSUE THREAD

**Issue by nekit508** [Anuken/Mindustry#8947]
### Platforms

Windows

### Build

145.1

### Issue

The game crashes when the block is configured.

### Steps to reproduce

1) start the game on custom map
2) open local server
3) change the configuration of any block

### Save file

[save](https://github.com/Anuken/Mindustry/files/12371093/specially.for.Anuke.zip)

### (Crash) logs

[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / GeForce 610M/PCIe/SSE2
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 1.8.0_311
[I] [RAM] Available: 1.3 GB
[I] [Mindustry] Version: 145.1
[I] Total time to load: 16543ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 54 community servers.
[I] Saved on exit.
[E] java.lang.IllegalArgumentException: Local players cannot be traced and do not have info.
	at mindustry.gen.Player.getInfo(Player.java:607)
	at mindustry.net.Administration.lambda$new$1(Administration.java:73)
	at mindustry.net.Administration.allowAction(Administration.java:167)
	at mindustry.net.Administration.allowAction(Administration.java:154)
	at mindustry.input.InputHandler.tileConfig(InputHandler.java:479)
	at mindustry.gen.Call.tileConfig(Call.java:1545)
	at mindustry.gen.Building.configure(Building.java:1471)
	at mindustry.world.blocks.ItemSelection.lambda$buildTable$2(ItemSelection.java:73)
	at arc.scene.Element$9.changed(Element.java:988)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
![2023-08-17-11-39-22](https://github.com/Anuken/Mindustry/assets/10100000/143605fc-2a1c-475a-80b4-07089c09a220)

Does not happen for me; if this were a common crash, it would have been reported before now. The only way this *could* happen is if you have a modified client, or somehow enabled a very specific configuration property in the *headless server* and then copied it over into the client.
