### ISSUE TITLE
[Bug]When declaring too many variables, Mindustry throws an error.

### ISSUE THREAD

**Issue by unanmed** [Anuken/Mindustry#9180]
### Platforms

Windows

### Build

Build 146

### Issue

In javascript mod, when I declare too many variables (2649 on my device), and there's a function call, the game throws an error saying that the function parameters have already been declared. Since I'm not very familiar with Java, I'm not sure if this issue is to Rhino or Mindustry. It seems unrelated to scope and modules. I consider this issue serious, especially when mod authors use JavaScript and declare many variables in a big mod, or when authors use compilers like Rollup or Babel to transform new syntax into ES5 syntax. This will cause a difficult-to-resolve problem.

### Steps to reproduce

1. Create a mod, with a scripts folder and a mod.json.
2. Create main.js in scripts/
3. Write main.js with a generated code:
```javascript
function test(test) {
    return test;
}
test();
var variable1 = 1;
var variable2 = 2;
// ......
var variavle2649 = 2649; // Crash count maybe different on different device.
```
4. Load the mod in game, and an error will be thrown.
5. If you delete the function call, this will not hapen however, even if you declare 1,000,000 variables.

### Mods used

None.

### Save file

None.

### (Crash) logs

[crash.txt](https://github.com/Anuken/Mindustry/files/13053441/crash.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JasonP01** [comment]
rhino.EvaluatorException: TypeError: redeclaration of var test. (main.js#2)
	at rhino.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:68)
	at rhino.Context.reportRuntimeError(Context.java:756)
	at rhino.Context.reportRuntimeError(Context.java:802)
	at rhino.Context.reportRuntimeError1(Context.java:770)
	at rhino.Interpreter.doSetConstVar(Interpreter.java:2396)
	at rhino.Interpreter.interpretLoop(Interpreter.java:1710)
	at script.test(main.js:2)
	at script(main.js:5)
	at script(main.js)
	at rhino.Interpreter.interpret(Interpreter.java:947)
	at rhino.InterpretedFunction.call(InterpretedFunction.java:68)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.InterpretedFunction.exec(InterpretedFunction.java:79)
	at rhino.Context.evaluateString(Context.java:989)
	at mindustry.mod.Scripts.run(Scripts.java:86)
	at mindustry.mod.Scripts.run(Scripts.java:76)
	at mindustry.mod.Mods.lambda$loadScripts$24(Mods.java:648)
	at arc.struct.Seq.each(Seq.java:182)
	at mindustry.mod.Mods.eachEnabled(Mods.java:790)
	at mindustry.mod.Mods.loadScripts(Mods.java:636)
	at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:159)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:333)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:215)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
	
	@unanmed its rhino according to the crash log

**Comment by Anuken** [comment]
I don't maintain the JS system anymore. Use Java.
