### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by brlinf-06398** [Anuken/Mindustry#9183]
### Platforms

Windows

### Build

Version: release build 146 (Foo's Client Version: a854598, Oct. 20, 2023 Unstable)

### Issue

Can't initialize the game. the game closes when it's loading. I updated the mod and still crashes.

### Steps to reproduce

Starting up the game. it loads till I get an error message.

### Mods used

(https://github.com/Mythril382/ThisThing)

### Save file

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. You can save the game to a slot even if you're playing on someone's server.

### (Crash) logs

[crash-report-10_21_2023_14_52_20.txt](https://github.com/Mythril382/ThisThing/files/13060132/crash-report-10_21_2023_14_52_20.txt)

Version: release build 146
(Foo's Client Version: a854598, Oct. 20, 2023 Unstable)
Source: mindustry-antigrief/mindustry-client-v7-builds
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 8176mb
Cores: 12
Mods: betamindy:1.1, camod:135, this-thing:1.6.0, toggle-editor-mode:2.2, yr2-logic-debugger:1.7.1

arc.util.ArcRuntimeException: java.lang.NullPointerException: Cannot invoke "arc.files.Fi.nameWithoutExtension()" because "file" is null
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:672)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:228)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:205)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:193)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:57)
Caused by: java.lang.NullPointerException: Cannot invoke "arc.files.Fi.nameWithoutExtension()" because "file" is null
	at thing.logic.TTLogic.setupConstants(TTLogic.java:31)
	at thing.logic.TTLogic.load(TTLogic.java:22)
	at thing.ThisThing.loadContent(ThisThing.java:35)
	at mindustry.mod.Mods.loadContent(Mods.java:724)
	at mindustry.core.ContentLoader.createModContent(ContentLoader.java:83)
	at mindustry.ClientLauncher.lambda$setup$5(ClientLauncher.java:170)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:334)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	... 6 more

### Submission

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by BasedUser** [comment]
This is a mod issue.

**Comment by SITUVNgcd** [comment]
```
Caused by: java.lang.NullPointerException: Cannot invoke "arc.files.Fi.nameWithoutExtension()" because "file" is null
at thing.logic.TTLogic.setupConstants(TTLogic.java:31)
```
Mod' issue.
