### ISSUE TITLE
Can't start in Raspberry PI 5 with current Raspberry OS

### ISSUE THREAD

**Issue by lutz-fechner** [Anuken/Mindustry#9238]
### Platforms

Linux

### Build

6.0 Build 126.2

### Issue

java -jar MindustryPi.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:315)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$8(DesktopLauncher.java:176)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:176)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:44)
Caused by: java.lang.ExceptionInInitializerError: Exception arc.util.ArcRuntimeException: Couldn't load shared library 'libsdl-arcarm64.so' for target: Linux, 64-bit [in thread "main"]
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
	at arc.backend.sdl.jni.SDL.<clinit>(SDL.java:148)
	at arc.backend.sdl.SdlApplication.lambda$init$0(SdlApplication.java:73)
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:181)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:73)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:29)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

### Steps to reproduce

Just download the Release JAR and try to lauch it.

I have anything SQL related installed from the add/Remove software panel of Rasperry OS.

### (Crash) logs

java -jar MindustryPi.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:315)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$8(DesktopLauncher.java:176)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:176)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:44)
Caused by: java.lang.ExceptionInInitializerError: Exception arc.util.ArcRuntimeException: Couldn't load shared library 'libsdl-arcarm64.so' for target: Linux, 64-bit [in thread "main"]
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
	at arc.backend.sdl.jni.SDL.<clinit>(SDL.java:148)
	at arc.backend.sdl.SdlApplication.lambda$init$0(SdlApplication.java:73)
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:181)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:73)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:29)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
you cant start the desktop because there is no arm64 linux native arc

**Comment by camelStyleUser** [comment]
but you can start the server

**Comment by Anuken** [comment]
ARM is not supported.
