### ISSUE TITLE
Mindustry keeps crashing

### ISSUE THREAD

**Issue by naren932** [Anuken/Mindustry#9327]
### Platforms

Windows

### Build

7.0 build 146

### Issue

When i opened the .jar, it just said: "
A crash has occured. it has been saved in: 
C:\bla bla, its just the error directory
Zip:
error reading zip file" _without the quotes obviously_
![Screenshot_216](https://github.com/Anuken/Mindustry/assets/69348844/8f09b6ec-2eb6-438b-9e58-bae2780aed1d)

### Steps to reproduce

download mindustry 7.0 build 146 (windows, jar file)
open the .jar

### (Crash) logs

Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_331
Runtime Available Memory: 3639mb
Cores: 8
<no mod init>

java.lang.NoClassDefFoundError: arc/util/serialization/UBJsonReader
	at arc.Settings.<init>(Settings.java:37)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:41)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.ClassNotFoundException: arc.util.serialization.UBJsonReader
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more
Caused by: java.util.zip.ZipException: error reading zip file
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(Unknown Source)
	at java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at sun.misc.Resource.getBytes(Unknown Source)
	at sun.misc.URLClassPath$JarLoader$2.getBytes(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	... 10 more

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by naren932** [comment]
i also recently just deleted the C:\Users\User\Appdata\Roaming\Mindustry folder

**Comment by naren932** [comment]
ill just play 7.0 145.1 for now

**Comment by Anuken** [comment]
Your game is corrupted in some way, an internal file is missing.

You're also using a very old version of Java to run the game, update it?
