### ISSUE TITLE
building read(writes){} & read(writes,revision){}

### ISSUE THREAD

**Issue by YmStrip** [Anuken/Mindustry#9389]
### Platforms

Windows

### Build

Version: 146 [Core] Initialized SDL v2.0.20

### Issue

Override  building 's read(r) read(r,revision) , write(w),
If overridden with only one argment, then 
... error ...

### Steps to reproduce

A building class in block class, override the write and read

### (Crash) logs

[E] mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveIO.load(SaveIO.java:170)
        at mindustry.io.SaveIO.load(SaveIO.java:145)
        at mindustry.io.SaveIO.load(SaveIO.java:139)
        at mindustry.game.Saves$SaveSlot.load(Saves.java:211)
        at mindustry.core.Control.lambda$playSector$33(Control.java:418)
        at mindustry.core.UI.lambda$loadAnd$10(UI.java:268)
        at arc.util.Timer$1.run(Timer.java:88)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:98)
        at mindustry.io.SaveVersion.read(SaveVersion.java:75)
        at mindustry.io.SaveIO.load(SaveIO.java:167)
        ... 10 more
Caused by: java.io.IOException: Could not skip bytes. Expected length: 24929; Actual length: 14737
        at mindustry.io.SaveFileReader.skipChunk(SaveFileReader.java:177)
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:321)
        at mindustry.io.SaveVersion.lambda$read$1(SaveVersion.java:75)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:164)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:157)
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:96)
        ... 12 more
[E] mindustry.io.SaveIO$SaveException: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
        at mindustry.game.Saves$SaveSlot.load(Saves.java:217)
        at mindustry.core.Control.lambda$playSector$33(Control.java:418)
        at mindustry.core.UI.lambda$loadAnd$10(UI.java:268)
        at arc.util.Timer$1.run(Timer.java:88)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveIO.load(SaveIO.java:170)
        at mindustry.io.SaveIO.load(SaveIO.java:150)
        at mindustry.io.SaveIO.load(SaveIO.java:139)
        at mindustry.game.Saves$SaveSlot.load(Saves.java:211)
        ... 7 more
Caused by: java.io.IOException: Error reading region "map".
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:98)
        at mindustry.io.SaveVersion.read(SaveVersion.java:75)
        at mindustry.io.SaveIO.load(SaveIO.java:167)
        ... 10 more
Caused by: java.io.IOException: Could not skip bytes. Expected length: 24929; Actual length: 14737
        at mindustry.io.SaveFileReader.skipChunk(SaveFileReader.java:177)
        at mindustry.io.SaveVersion.readMap(SaveVersion.java:321)
        at mindustry.io.SaveVersion.lambda$read$1(SaveVersion.java:75)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:164)
        at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:157)
        at mindustry.io.SaveFileReader.region(SaveFileReader.java:96)
        ... 12 more

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> If overridden with only one argment, then

Then don't override it! Many methods aren't supposed to be overridden.
