### ISSUE TITLE
Game crash on removing Mech Pad

### ISSUE THREAD

**Issue by WilhelmW** [Anuken/Mindustry#958]
**Platform**: *Windows*

**Build**: *99.3.*

**Issue**: *Game crashes if you try to remove an Mech Pad*

**Steps to reproduce**: *Place Mech Pad, remove Mech Pad*

java.lang.ClassCastException: io.anuke.mindustry.world.blocks.BuildBlock cannot be cast to io.anuke.mindustry.world.blocks.units.MechPad
	at io.anuke.mindustry.graphics.OverlayRenderer.drawTop(OverlayRenderer.java:71)
	at io.anuke.mindustry.core.Renderer.draw(Renderer.java:297)
	at io.anuke.mindustry.core.Renderer.update(Renderer.java:139)
	at io.anuke.arc.ApplicationCore.update(ApplicationCore.java:36)
	at io.anuke.mindustry.ClientLauncher.update(ClientLauncher.java:130)
	at io.anuke.arc.backends.sdl.SdlApplication.listen(SdlApplication.java:158)
	at io.anuke.arc.backends.sdl.SdlApplication.loop(SdlApplication.java:146)
	at io.anuke.arc.backends.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:52)

**Comment by Quezler** [comment]
Is the block flag present even while con/de structing or something? 🤔
