### ISSUE TITLE
Unable to launch to Ruinous Shores (Custom build)

### ISSUE THREAD

**Issue by Rundll86** [Anuken/Mindustry#9607]
### Platforms

Windows

### Build

Custom build

### Issue

Code cloned by `git clone` command, without submodules.I modified some blocks and entities (At `Blocks.java` and `UnitTypes.java` of `core/src/mindustry/content`) then run `gradlew.bat desktop:dist`,but the builded result unable to launch to `Ruinous Shores`.

### Steps to reproduce

git clone,
modified some blocks and entities,
build,
try launching to Ruinous Shores

### (Crash) logs

Mindustry has crashed. How unfortunate.
Version: custom build
OS: Windows 11 x64 (amd64)
Java Version: 1.8.0_391
Runtime Available Memory: 3600mb
Cores: 12
Mods: none (vanilla)

mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveIO.load(SaveIO.java:157)
	at mindustry.maps.generators.FileMapGenerator.generate(FileMapGenerator.java:47)
	at mindustry.core.World.lambda$loadSector$2(World.java:266)
	at mindustry.core.World.loadGenerator(World.java:251)
	at mindustry.core.World.loadSector(World.java:264)
	at mindustry.core.World.loadSector(World.java:257)
	at mindustry.core.Control.playNewSector(Control.java:522)
	at mindustry.core.Control.lambda$playSector$33(Control.java:515)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:270)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:98)
	at mindustry.io.versions.LegacyRegionSaveVersion.read(LegacyRegionSaveVersion.java:24)
	at mindustry.io.SaveIO.load(SaveIO.java:172)
	at mindustry.io.SaveIO.load(SaveIO.java:150)
	... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 90000
	at mindustry.world.Tiles.geti(Tiles.java:95)
	at mindustry.core.World$Context.tile(World.java:580)
	at mindustry.core.World$FilterContext.tile(World.java:612)
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:347)
	at mindustry.io.versions.LegacyRegionSaveVersion.lambda$read$1(LegacyRegionSaveVersion.java:24)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:164)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:157)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:96)
	... 16 more

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I provide no support for crashes caused by your modifications of the game.
