### ISSUE TITLE
Mindustry keeps crashing

### ISSUE THREAD

**Issue by thomasdn** [Anuken/Mindustry#9728]
### Platforms

Mac

### Build

24911

### Issue

Mindustry keeps crashing in sector 223.

I seem to have lost my builds in this sector. I hope my other saved games are intact... But not sure how to check to be sure...

Below is crash report.

### Steps to reproduce

1. Start mindustry.
2. Open Campaign
3. Doubleclick sector 223
4. Wait a few moments and it will crash

### Mods used

none

### Save file

[mindustry-saves.zip](https://github.com/Anuken/Mindustry/files/14911638/mindustry-saves.zip)

### (Crash) logs

```
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: bleeding-edge build 24911
OS: Mac OS X x64 (aarch64)
Java Version: 21.0.2
Runtime Available Memory: 6144mb
Cores: 8
Mods: none (vanilla)

java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Error writing region "map".
    at mindustry.io.SaveIO.save(SaveIO.java:46)
    at mindustry.game.Saves$SaveSlot.save(Saves.java:224)
    at mindustry.core.Control.lambda$playSector$30(Control.java:395)
    at mindustry.core.UI.lambda$loadAnd$10(UI.java:270)
    at arc.util.Timer$1.run(Timer.java:88)
    at arc.util.TaskQueue.run(TaskQueue.java:17)
    at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
    at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
    at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.RuntimeException: java.io.IOException: Error writing region "map".
    at mindustry.io.SaveIO.write(SaveIO.java:135)
    at mindustry.io.SaveIO.write(SaveIO.java:115)
    at mindustry.io.SaveIO.write(SaveIO.java:119)
    at mindustry.io.SaveIO.save(SaveIO.java:43)
    ... 8 more
Caused by: java.io.IOException: Error writing region "map".
    at mindustry.io.SaveFileReader.region(SaveFileReader.java:110)
    at mindustry.io.SaveVersion.write(SaveVersion.java:88)
    at mindustry.io.SaveVersion.write(SaveVersion.java:67)
    at mindustry.io.SaveIO.write(SaveIO.java:130)
    ... 11 more
Caused by: java.lang.NullPointerException: Cannot load from int array because "this.itemsLeft" is null
    at mindustry.world.blocks.ConstructBlock$ConstructBuild.write(ConstructBlock.java:467)
    at mindustry.gen.Building.writeAll(Building.java:2317)
    at mindustry.io.SaveVersion.lambda$writeMap$5(SaveVersion.java:247)
    at mindustry.io.SaveFileReader.writeChunk(SaveFileReader.java:134)
    at mindustry.io.SaveVersion.writeMap(SaveVersion.java:245)
    at mindustry.io.SaveFileReader.writeChunk(SaveFileReader.java:134)
    at mindustry.io.SaveFileReader.writeChunk(SaveFileReader.java:115)
    at mindustry.io.SaveFileReader.region(SaveFileReader.java:108)
    ... 14 more
```

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by thomasdn** [comment]
@Anuken excellent that this is fixed so quickly! 
If the fix works, this is incredibly fast. Less than 10 minutes from bug report to fix!
I am looking forward to an update being available to install.

Is there any chance I can get my build from sector 223 back? 
Or at least ensure that my saves are "uncorrupted" - if they are corrupted at all by this?

**Comment by Anuken** [comment]
The game should be able to load your backup save files, if your original ones are corrupted.
