### ISSUE TITLE
Why is my archive bad or invalid? I recreate and reselect the region as well

### ISSUE THREAD

**Issue by farish-awa** [Anuken/Mindustry#9811]
### Platforms

Windows

### Build

146

### Issue

Why is my archive bad or invalid? I recreate and reselect the region as well

### Steps to reproduce

I re-enter the archive

### Mods used

not

### Save file

[data.zip](https://github.com/Anuken/Mindustry/files/15211623/data.zip)

### (Crash) logs

last log:
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / NVIDIA GeForce GTX 1650/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 16.0.1
[I] [RAM] Available: 7.9 GB
[I] [Mindustry] Version: 146
[I] Total time to load: 1660ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[E] Failed to fetch community servers: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at arc.util.Http$HttpRequest.block(Http.java:297)
	at arc.util.Http$HttpRequest.lambda$submit$0(Http.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 22 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 27 more

[E] mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "entities": read length mismatch. Expected: 160; Actual: 120
	at mindustry.io.SaveIO.load(SaveIO.java:170)
	at mindustry.io.SaveIO.load(SaveIO.java:145)
	at mindustry.io.SaveIO.load(SaveIO.java:139)
	at mindustry.game.Saves$SaveSlot.load(Saves.java:211)
	at mindustry.core.Control.lambda$playSector$33(Control.java:418)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:268)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.IOException: Error reading region "entities": read length mismatch. Expected: 160; Actual: 120
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:102)
	at mindustry.io.SaveVersion.read(SaveVersion.java:76)
	at mindustry.io.SaveIO.load(SaveIO.java:167)
	... 10 more

[E] mindustry.io.SaveIO$SaveException: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "entities".
	at mindustry.game.Saves$SaveSlot.load(Saves.java:217)
	at mindustry.core.Control.lambda$playSector$33(Control.java:418)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:268)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "entities".
	at mindustry.io.SaveIO.load(SaveIO.java:170)
	at mindustry.io.SaveIO.load(SaveIO.java:150)
	at mindustry.io.SaveIO.load(SaveIO.java:139)
	at mindustry.game.Saves$SaveSlot.load(Saves.java:211)
	... 7 more
Caused by: java.io.IOException: Error reading region "entities".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:98)
	at mindustry.io.SaveVersion.read(SaveVersion.java:76)
	at mindustry.io.SaveIO.load(SaveIO.java:167)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Unknown object type: -1
	at mindustry.io.TypeIO.readObjectBoxed(TypeIO.java:207)
	at mindustry.io.TypeIO.readObjectBoxed(TypeIO.java:203)
	at mindustry.io.TypeIO.readObject(TypeIO.java:141)
	at mindustry.io.TypeIO.readPlan(TypeIO.java:427)
	at mindustry.io.TypeIO.readPlansQueue(TypeIO.java:395)
	at mindustry.gen.UnitEntityLegacyAlpha.read(UnitEntityLegacyAlpha.java:94)
	at mindustry.io.SaveVersion.lambda$readWorldEntities$8(SaveVersion.java:430)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:164)
	at mindustry.io.SaveVersion.readWorldEntities(SaveVersion.java:418)
	at mindustry.io.SaveVersion.readEntities(SaveVersion.java:453)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:164)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:157)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:96)
	... 12 more

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I'm not sure what you're reporting here due to bad translation; the data zip file is valid. You appear to have a corrupt save somewhere, but that can be for any number of reasons.
