### ISSUE TITLE
Mindustry has crashed java.lang.IllegalArgumentException: initialCapacity is too large: 64 Help please

### ISSUE THREAD

**Issue by vadim556** [Anuken/Mindustry#9860]
### Platforms

Windows

### Build

1.8.0_391

### Issue

java.lang.IllegalArgumentException: initialCapacity is too large: 64
	at arc.struct.ObjectMap.<init>(ObjectMap.java:76)
	at arc.struct.ObjectMap.<init>(ObjectMap.java:56)
	at mindustry.ai.types.LogicAI.<init>(LogicAI.java:29)
	at mindustry.logic.LExecutor$UnitControlI.checkLogicAI(LExecutor.java:385)
	at mindustry.logic.LExecutor$UnitControlI.run(LExecutor.java:402)
	at mindustry.logic.LExecutor.runOnce(LExecutor.java:84)
	at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateTile(LogicBlock.java:515)
	at mindustry.gen.Building.update(Building.java:2199)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:83)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:483)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:237)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Steps to reproduce

захожу на сервер проходит пару минут и вылетает с этой ошибкой помогите

### (Crash) logs

java.lang.IllegalArgumentException: initialCapacity is too large: 64
	at arc.struct.ObjectMap.<init>(ObjectMap.java:76)
	at arc.struct.ObjectMap.<init>(ObjectMap.java:56)
	at mindustry.ai.types.LogicAI.<init>(LogicAI.java:29)
	at mindustry.logic.LExecutor$UnitControlI.checkLogicAI(LExecutor.java:385)
	at mindustry.logic.LExecutor$UnitControlI.run(LExecutor.java:402)
	at mindustry.logic.LExecutor.runOnce(LExecutor.java:84)
	at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateTile(LogicBlock.java:515)
	at mindustry.gen.Building.update(Building.java:2199)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:83)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:483)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:237)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by vadim556** [comment]
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_391
Runtime Available Memory: 1736mb
Cores: 2
Mods: none (vanilla)

java.lang.IllegalArgumentException: initialCapacity is too large: 64
	at arc.struct.ObjectMap.<init>(ObjectMap.java:76)
	at arc.struct.ObjectMap.<init>(ObjectMap.java:56)
	at mindustry.ai.types.LogicAI.<init>(LogicAI.java:29)
	at mindustry.logic.LExecutor$UnitControlI.checkLogicAI(LExecutor.java:385)
	at mindustry.logic.LExecutor$UnitControlI.run(LExecutor.java:402)
	at mindustry.logic.LExecutor.runOnce(LExecutor.java:84)
	at mindustry.world.blocks.logic.LogicBlock$LogicBuild.updateTile(LogicBlock.java:515)
	at mindustry.gen.Building.update(Building.java:2199)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:83)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:483)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:237)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by Anuken** [comment]
You are using a very outdated Java version. I don't know where you got it, but you need to update it.

**Comment by mahdoosh1** [comment]
> You are using a very outdated Java version. I don't know where you got it, but you need to update it. 

just a fact to tell you, i have tried playing the game without having java installed, and  the game is perfectly fine, are you sure the game requires java to be installed?

**Comment by Anuken** [comment]
Mindustry comes with Java packaged, but the version of Java reported in this crash is *not* the version that it's packaged with, which implies it's being run with a different version.
