### ISSUE TITLE
mindustry crashed

### ISSUE THREAD

**Issue by glotok** [Anuken/Mindustry#9862]
### Platforms

Windows

### Build

146

### Issue

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 2028mb
Cores: 6
Mods: none (vanilla)

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: Vars
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:215)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: Vars
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:104)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: arc.util.ArcRuntimeException: Cannot open a stream to a directory: locales (internal)
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:102)
	... 9 more
Caused by: arc.util.ArcRuntimeException: Cannot open a stream to a directory: locales (internal)
	at arc.files.Fi.read(Fi.java:206)
	at arc.files.Fi.readString(Fi.java:281)
	at arc.files.Fi.readString(Fi.java:266)
	at mindustry.Vars.init(Vars.java:266)
	at mindustry.Vars.loadAsync(Vars.java:258)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:352)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:52)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:16)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: locales (Отказано в доступе)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at arc.files.Fi.read(Fi.java:203)
	... 11 more

### Steps to reproduce

running the file mindastry.exe and it gives an error

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
either something is reading the jar at the same time or the jar/in-jar permissions are wrong

**Comment by camelStyleUser** [comment]
make sure you dont have an antivirus scanning the file

**Comment by Anuken** [comment]
Delete a folder named `locales` in the mindustry directory, if it exists. Otherwise, validate your game files.
