### ISSUE TITLE
Mods not loading

### ISSUE THREAD

**Issue by PsyNyde** [Anuken/Mindustry#9895]
### Platforms

Linux

### Build

Release build 146?

### Issue

I get this error after I installed mod and mods aren't loading as a result.

```sh
[E] Failed to load mod file null. Skipping.
[E] java.lang.NullPointerException: Cannot invoke "arc.files.Fi.isDirectory()" because "sourceFile" is null
```
also I'm using [mindustry-wayland](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/mindustry/default.nix#L243) from nix repo if it helps. and the issue seems to be only with `itembridgeX` mod.

### Steps to reproduce

Install ItemBridgeX from mod menu & restart (not loaded).. run via shell to see the error

### Mods used

ItemBridgeX

### (Crash) logs

~ mindustry          
[I] Initialized Discord rich presence.
[I] [Core] Initialized SDL v2.30.2
[I] [Audio] Initialized SoLoud 202111 using MiniAudio at 44100hz / 900 samples / 2 channels
[I] [GL] Version: OpenGL 4.6.0 / Intel / Mesa Intel(R) HD Graphics 630 (KBL GT2)
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 17.0.7
[I] [RAM] Available: 1.9 GB
[I] [Mindustry] Version: 146
[E] Failed to load mod file null. Skipping.
[E] java.lang.NullPointerException: Cannot invoke "arc.files.Fi.isDirectory()" because "sourceFile" is null
	at mindustry.mod.Mods.loadMod(Mods.java:889)
	at mindustry.mod.Mods.load(Mods.java:465)
	at mindustry.Vars.init(Vars.java:337)
	at mindustry.Vars.loadAsync(Vars.java:258)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:352)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:52)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:16)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[I] Total time to load: 3554ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 78 community servers.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [ ] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
This should have already been fixed in `master`.
