### ISSUE TITLE
Mod not deleted

### ISSUE THREAD

**Issue by Xusk947** [Anuken/Mindustry#992]
**Platform**: *Android*

**Build**: *99.8*

**Issue**: *I try to delete mod and my game crash*

**Steps to reproduce**: *java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.zip.ZipFile.close()' on a null object reference
	at io.anuke.arc.files.ZipFileHandle.delete(ZipFileHandle.java:77)
	at io.anuke.mindustry.mod.Mods.removeMod(Mods.java:154)
	at io.anuke.mindustry.ui.dialogs.ModsDialog.lambda$null$20$ModsDialog(ModsDialog.java:140)
	at io.anuke.mindustry.ui.dialogs.-$$Lambda$ModsDialog$KLnPGTczuneNhU8uMQUejgqEOxI.run(Unknown Source:4)
	at io.anuke.mindustry.core.UI.lambda$showConfirm$12(UI.java:415)
	at io.anuke.mindustry.core.-$$Lambda$UI$VNZKuk5PdN_JF2JpAlX7toGmWi4.run(Unknown Source:4)
	at io.anuke.arc.scene.Element$8.changed(Element.java:1074)
	at io.anuke.arc.scene.event.ChangeListener.handle(ChangeListener.java:12)
	at io.anuke.arc.scene.Element.notify(Element.java:172)
	at io.anuke.arc.scene.Element.fire(Element.java:143)
	at io.anuke.arc.scene.ui.Button.setChecked(Button.java:106)
	at io.anuke.arc.scene.ui.Button$1.clicked(Button.java:92)
	at io.anuke.arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at io.anuke.arc.scene.event.InputListener.handle(InputListener.java:33)
	at io.anuke.arc.scene.Scene.touchUp(Scene.java:314)
	at io.anuke.arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:115)
	at io.anuke.arc.backends.android.surfaceview.AndroidInput.processEvents(AndroidInput.java:272)
	at io.anuke.arc.backends.android.surfaceview.AndroidGraphics.onDrawFrame(AndroidGraphics.java:429)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
.*

**Comment by Anuken** [comment]
Already fixed.
