### ISSUE TITLE
bug crashing when loading an map

### ISSUE THREAD

**Issue by oskarvello** [Anuken/Mindustry#9997]
### Platforms

Windows

### Build

146 build

### Issue

when trying do load into "ruinous shores" sector then the game crashes for whatever reason

### Steps to reproduce

after capturing "the craters" sector i went do go and land on "ruinouse shores" sector and then it crashes

### Mods used

Mods: auto-drill:1, item-bridge-x:2, letter-sound-effect:1, multi-crafter:1.8, scheme-size:2.7.79, v-scheme-pack:1.0.0, xelos-pixel-texturepack:0.4.1

### Save file

sector "ruinous shores" [save.zip](https://github.com/user-attachments/files/16069822/save.zip)

### (Crash) logs

Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 996mb
Cores: 4
Mods: auto-drill:1, item-bridge-x:2, letter-sound-effect:1, multi-crafter:1.8, scheme-size:2.7.79, v-scheme-pack:1.0.0, xelos-pixel-texturepack:0.4.1

mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveIO.load(SaveIO.java:152)
	at mindustry.maps.generators.FileMapGenerator.generate(FileMapGenerator.java:47)
	at mindustry.core.World.lambda$loadSector$2(World.java:266)
	at mindustry.core.World.loadGenerator(World.java:251)
	at mindustry.core.World.loadSector(World.java:264)
	at mindustry.core.World.loadSector(World.java:257)
	at mindustry.core.Control.playNewSector(Control.java:515)
	at mindustry.core.Control.lambda$playSector$33(Control.java:508)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:268)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:98)
	at mindustry.io.versions.LegacyRegionSaveVersion.read(LegacyRegionSaveVersion.java:24)
	at mindustry.io.SaveIO.load(SaveIO.java:167)
	at mindustry.io.SaveIO.load(SaveIO.java:145)
	... 13 more
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readShort(Unknown Source)
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:291)
	at mindustry.io.versions.LegacyRegionSaveVersion.lambda$read$1(LegacyRegionSaveVersion.java:24)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:164)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:157)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:96)
	... 16 more

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
the game data you sent doesnt even have a ruinous shores save file and you have a lot of mods

**Comment by camelStyleUser** [comment]
including scheme size

**Comment by Mythril382** [comment]
> the game data you sent doesnt even have a ruinous shores save file and you have a lot of mods

Probably because they can't go in it.

**Comment by Mythril382** [comment]
Have you tried disabling all mods and seeing if it still crashes?

**Comment by camelStyleUser** [comment]
> > the game data you sent doesnt even have a ruinous shores save file and you have a lot of mods
> 
> Probably because they can't go in it.

the map isnt broken because i can go into it

**Comment by mahdoosh1** [comment]
> 
> the map isnt broken because i can go into it

what if you somehow corrupt it just after losing to enemies?

**Comment by oskarvello** [comment]
> Have you tried disabling all mods and seeing if it still crashes?

Yeah it was the mods proplem

**Comment by camelStyleUser** [comment]
> > Have you tried disabling all mods and seeing if it still crashes?
> 
> Yeah it was the mods proplem

THEN WHY DID YOU CHECK THE BOX THAT IT WAS NOT CAUSED BY ANY MODS

**Comment by camelStyleUser** [comment]
NO ONE FORCED YOU TO CHECK IT

**Comment by camelStyleUser** [comment]
YOU VOULD HAVE JUST NOT SUBMITTED THE BUG REPORT

**Comment by mahdoosh1** [comment]
> YOU COULD HAVE JUST NOT SUBMITTED THE BUG REPORT

they don't understand that, they think the boxes are something like terms of service and dont read it.
